#!/usr/bin/env python3
"""Generate bridge_words.json for the Word Weaver crossword.

Adds ~140 short, vowel-rich, kid-friendly words that act as bridges between
longer anchor words in crossword generation. Matches lexicon_seed.json schema
exactly. Filters out any words already present in the seed lexicon.
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
LEXICON_PATH = os.path.join(SCRIPT_DIR, "lexicon_seed.json")
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "bridge_words.json")


def E(word, pos, grade, diff, definition, tags, root_lang, root_word, emergence,
      etym_note, synonyms=None, antonyms=None, families=None, related=None):
    """tags is a dict {tag: relevance_score}."""
    return {
        "word": word,
        "part_of_speech": pos,
        "grade_level": grade,
        "difficulty": diff,
        "senses": [{
            "definition": definition,
            "tags": list(tags.keys()),
            "relevance": dict(tags),
        }],
        "history": {
            "root_language": root_lang,
            "root_word": root_word,
            "emergence": emergence,
            "etymology_note": etym_note,
        },
        "associations": {
            "synonyms": synonyms or [],
            "antonyms": antonyms or [],
            "families": families or [],
            "related_concepts": related or [],
        },
    }


ENTRIES = [
    # ============ ANIMALS ============
    E("bat", "noun", "preK", 1,
      "A furry animal that flies at night and uses sound to find its way.",
      {"animals": 10, "mammals": 9, "night": 8},
      "Middle English", "bakke", "Middle English",
      "From Middle English 'bakke', a name for the night-flying mammal of uncertain Scandinavian origin.",
      synonyms=[], antonyms=[], families=["Animals", "Mammals"],
      related=["wing", "night", "cave", "owl"]),

    E("eel", "noun", "1", 2,
      "A long, snake-like fish that lives in water.",
      {"animals": 10, "fish": 10, "water": 8},
      "Old English", "ǣl", "Old English era",
      "From Old English 'ǣl', the same word in many old Germanic languages for this snake-like fish.",
      families=["Animals", "Fish"], related=["fish", "river", "ocean", "snake"]),

    E("elk", "noun", "1", 2,
      "A very large deer with wide, branching antlers.",
      {"animals": 10, "mammals": 9, "forest": 7},
      "Old English", "eolh", "Old English era",
      "From Old English 'eolh', related to other Germanic words for large deer.",
      families=["Animals", "Mammals"], related=["deer", "antler", "forest"]),

    E("fox", "noun", "K", 1,
      "A wild animal with red-orange fur, pointed ears, and a bushy tail.",
      {"animals": 10, "mammals": 9, "forest": 7},
      "Old English", "fox", "Old English era",
      "From Old English 'fox', unchanged in form for over a thousand years.",
      synonyms=["vixen"], families=["Animals", "Mammals"],
      related=["wolf", "forest", "tail", "den"]),

    E("hen", "noun", "preK", 1,
      "A female chicken that lays eggs.",
      {"animals": 10, "farm": 10, "birds": 9},
      "Old English", "henn", "Old English era",
      "From Old English 'henn', the feminine form of 'hana' meaning rooster.",
      synonyms=["chicken"], families=["Animals", "Birds", "Farm"],
      related=["egg", "chicken", "farm", "rooster"]),

    E("owl", "noun", "preK", 1,
      "A bird with large round eyes that hunts at night.",
      {"animals": 10, "birds": 10, "night": 8},
      "Old English", "ūle", "Old English era",
      "From Old English 'ūle', imitative of the bird's hooting call.",
      families=["Animals", "Birds"], related=["bird", "night", "hoot", "feather"]),

    E("rat", "noun", "K", 2,
      "A small rodent with a long, thin tail.",
      {"animals": 10, "mammals": 9, "rodents": 10},
      "Old English", "ræt", "Old English era",
      "From Old English 'ræt', shared with other Germanic languages.",
      families=["Animals", "Rodents"], related=["mouse", "tail", "cheese"]),

    E("deer", "noun", "K", 1,
      "A graceful forest animal with thin legs, often with antlers.",
      {"animals": 10, "mammals": 9, "forest": 8},
      "Old English", "dēor", "Old English era",
      "From Old English 'dēor', which originally meant any wild animal before narrowing to the antlered ruminant.",
      families=["Animals", "Mammals"], related=["antler", "forest", "elk", "fawn"]),

    E("goat", "noun", "K", 1,
      "A farm animal with horns and a beard that loves to climb.",
      {"animals": 10, "farm": 10, "mammals": 9},
      "Old English", "gāt", "Old English era",
      "From Old English 'gāt', meaning she-goat, with cognates throughout the Germanic languages.",
      families=["Animals", "Farm"], related=["sheep", "horn", "farm", "milk"]),

    E("lamb", "noun", "K", 1,
      "A baby sheep with soft, woolly fur.",
      {"animals": 10, "farm": 10, "mammals": 9},
      "Old English", "lamb", "Old English era",
      "From Old English 'lamb', the same form in Old High German and Old Norse.",
      families=["Animals", "Farm"], related=["sheep", "wool", "farm"]),

    E("mole", "noun", "1", 2,
      "A small furry animal that digs tunnels underground.",
      {"animals": 10, "mammals": 9, "earth": 7},
      "Middle English", "molle", "14th Century",
      "From Middle English 'molle', possibly related to mold or the verb to grind, since moles burrow through soil.",
      families=["Animals", "Mammals"], related=["tunnel", "dig", "ground", "blind"]),

    E("moth", "noun", "1", 2,
      "A night insect that looks like a butterfly with duller wings.",
      {"animals": 10, "insects": 10, "night": 7},
      "Old English", "moððe", "Old English era",
      "From Old English 'moððe', name for the winged insect, related to similar words across Germanic languages.",
      families=["Animals", "Insects"], related=["butterfly", "night", "wing", "lamp"]),

    E("seal", "noun", "K", 2,
      "A sleek ocean mammal with flippers, found on rocky shores.",
      {"animals": 10, "mammals": 9, "ocean": 9},
      "Old English", "seolh", "Old English era",
      "From Old English 'seolh', the marine mammal, an ancient Germanic word.",
      families=["Animals", "Mammals", "Ocean"], related=["ocean", "flipper", "fish", "shore"]),

    E("swan", "noun", "1", 2,
      "A large, graceful white water bird with a long, curved neck.",
      {"animals": 10, "birds": 10, "water": 8},
      "Old English", "swan", "Old English era",
      "From Old English 'swan', unchanged since the early Middle Ages.",
      families=["Animals", "Birds"], related=["duck", "lake", "feather", "goose"]),

    E("toad", "noun", "1", 2,
      "A hopping animal like a frog with bumpy, dry skin.",
      {"animals": 10, "amphibians": 10, "nature": 7},
      "Old English", "tāde", "Old English era",
      "From Old English 'tāde' or 'tādige', of uncertain origin but used in English for over a thousand years.",
      families=["Animals", "Amphibians"], related=["frog", "pond", "hop", "skin"]),

    E("worm", "noun", "preK", 1,
      "A long, soft creature with no legs that wiggles through dirt.",
      {"animals": 10, "nature": 8, "garden": 7},
      "Old English", "wyrm", "Old English era",
      "From Old English 'wyrm', which originally meant any serpent or dragon before narrowing to the soft burrowing creature.",
      families=["Animals", "Garden"], related=["dirt", "garden", "bird", "wiggle"]),

    E("goose", "noun", "1", 2,
      "A big water bird with a long neck and a loud honk.",
      {"animals": 10, "birds": 10, "water": 8},
      "Old English", "gōs", "Old English era",
      "From Old English 'gōs', shared with Old High German 'gans' and Old Norse 'gás'.",
      families=["Animals", "Birds"], related=["duck", "swan", "honk", "flock"]),

    E("mouse", "noun", "preK", 1,
      "A tiny rodent with round ears and a long thin tail.",
      {"animals": 10, "mammals": 9, "rodents": 10},
      "Old English", "mūs", "Old English era",
      "From Old English 'mūs', an ancient word shared across Indo-European languages, including Latin 'mus'.",
      families=["Animals", "Rodents"], related=["rat", "cheese", "cat", "tail"]),

    # ============ FOOD ============
    E("pea", "noun", "preK", 1,
      "A tiny round green vegetable that grows inside a pod.",
      {"food": 10, "vegetables": 10, "plants": 7},
      "Latin", "pisum", "17th Century",
      "Back-formed from the older English word 'pease', which was thought to be plural, from Latin 'pisum'.",
      families=["Food", "Vegetables"], related=["bean", "pod", "garden", "green"]),

    E("nut", "noun", "preK", 1,
      "A hard-shelled snack that grows on trees and is full of seeds.",
      {"food": 10, "plants": 8, "trees": 7},
      "Old English", "hnutu", "Old English era",
      "From Old English 'hnutu', shared with Old Norse 'hnot' and other Germanic languages.",
      families=["Food", "Plants"], related=["acorn", "tree", "shell", "seed"]),

    E("jam", "noun", "preK", 1,
      "A sweet, sticky fruit spread you put on toast.",
      {"food": 10, "breakfast": 8, "fruit": 8},
      "English", "jam", "18th Century",
      "From the verb 'jam', meaning to press tightly, since fruit is crushed to make the spread.",
      synonyms=["preserves", "jelly"], families=["Food"],
      related=["toast", "fruit", "bread", "sugar"]),

    E("pie", "noun", "preK", 1,
      "A baked treat with a crust and a sweet or savory filling.",
      {"food": 10, "dessert": 8, "baking": 8},
      "Middle English", "pie", "14th Century",
      "Possibly named after the magpie, whose habit of collecting random things resembled the mix of fillings in early pies.",
      families=["Food", "Desserts"], related=["cake", "fruit", "crust", "bake"]),

    E("tea", "noun", "K", 1,
      "A warm drink made by soaking leaves in hot water.",
      {"food": 8, "drinks": 10, "plants": 6},
      "Min Nan Chinese", "tê", "17th Century",
      "From Min Nan Chinese 'tê', brought to Europe by Dutch traders. The word followed the spread of the drink.",
      families=["Drinks", "Food"], related=["coffee", "cup", "leaf", "warm"]),

    E("ham", "noun", "K", 1,
      "Salty meat that comes from a pig.",
      {"food": 10, "meat": 10, "farm": 7},
      "Old English", "hamm", "Old English era",
      "From Old English 'hamm', originally meaning the back of the knee or thigh, and later the cured meat from that part of a pig.",
      families=["Food", "Meat"], related=["pig", "meat", "sandwich", "farm"]),

    E("fig", "noun", "1", 2,
      "A soft, sweet fruit with tiny seeds inside.",
      {"food": 10, "fruit": 10, "plants": 7},
      "Latin", "ficus", "12th Century",
      "From Latin 'ficus', through Old French 'figue', for the soft sweet fruit grown around the Mediterranean.",
      families=["Food", "Fruit"], related=["fruit", "tree", "seed", "date"]),

    E("bun", "noun", "K", 1,
      "A small, round bread roll, often with sugar or fruit inside.",
      {"food": 10, "baking": 9, "bread": 9},
      "Middle English", "bunne", "14th Century",
      "From Middle English 'bunne', possibly from Old French 'bugne' meaning a swelling or lump.",
      families=["Food", "Bread"], related=["bread", "roll", "bake", "sugar"]),

    E("bean", "noun", "K", 1,
      "A small seed used for food, growing inside a long green pod.",
      {"food": 10, "vegetables": 10, "plants": 8},
      "Old English", "bēan", "Old English era",
      "From Old English 'bēan', an ancient Germanic word for the protein-rich seed.",
      families=["Food", "Vegetables"], related=["pea", "pod", "plant", "soup"]),

    E("milk", "noun", "preK", 1,
      "A white drink that comes from cows, goats, and other mammals.",
      {"food": 10, "drinks": 10, "farm": 8},
      "Old English", "meoluc", "Old English era",
      "From Old English 'meoluc', meaning milk, with cognates across the Germanic languages.",
      families=["Food", "Drinks"], related=["cow", "cheese", "cup", "white"]),

    E("rice", "noun", "K", 1,
      "Small white grains that we cook and eat as food.",
      {"food": 10, "grains": 10, "plants": 7},
      "Greek", "oryza", "13th Century",
      "From Greek 'oryza' through Latin and Old French, reaching English in the Middle Ages as the grain spread through Europe.",
      families=["Food", "Grains"], related=["grain", "soup", "field", "bowl"]),

    E("soup", "noun", "preK", 1,
      "A hot liquid meal often with vegetables, meat, or noodles.",
      {"food": 10, "meals": 9, "cooking": 8},
      "Old French", "soupe", "17th Century",
      "From Old French 'soupe', meaning broth poured over bread. Related to 'sop' in English.",
      families=["Food", "Meals"], related=["bowl", "spoon", "warm", "broth"]),

    E("pear", "noun", "K", 1,
      "A sweet, juicy fruit shaped like a teardrop.",
      {"food": 10, "fruit": 10, "plants": 7},
      "Latin", "pirum", "Old English era",
      "From Latin 'pirum' through Old English 'peru', for the soft sweet fruit related to the apple.",
      families=["Food", "Fruit"], related=["apple", "fruit", "tree", "garden"]),

    E("lime", "noun", "1", 2,
      "A small green sour fruit related to the lemon.",
      {"food": 10, "fruit": 10, "plants": 7},
      "Arabic", "līma", "17th Century",
      "From Arabic 'līma' through Spanish and French, naming the small green citrus fruit.",
      families=["Food", "Fruit"], related=["lemon", "fruit", "sour", "citrus"]),

    E("plum", "noun", "1", 2,
      "A small purple fruit with a pit inside.",
      {"food": 10, "fruit": 10, "plants": 7},
      "Latin", "prunum", "Old English era",
      "From Latin 'prunum' through Old English 'plūme', for the smooth-skinned stone fruit.",
      families=["Food", "Fruit"], related=["peach", "fruit", "tree", "pit"]),

    E("honey", "noun", "K", 1,
      "A sweet, sticky food that bees make from flower nectar.",
      {"food": 10, "insects": 7, "nature": 6},
      "Old English", "hunig", "Old English era",
      "From Old English 'hunig', shared across the Germanic languages, the oldest sweetener used by humans.",
      families=["Food", "Sweeteners"], related=["bee", "flower", "sweet", "sticky"]),

    E("lemon", "noun", "K", 1,
      "A bright yellow sour fruit.",
      {"food": 10, "fruit": 10, "plants": 7},
      "Arabic", "līmūn", "15th Century",
      "From Arabic 'līmūn' through Old French 'limon', for the yellow citrus fruit.",
      families=["Food", "Fruit"], related=["lime", "sour", "yellow", "citrus"]),

    E("olive", "noun", "1", 2,
      "A small green or black fruit used to make oil.",
      {"food": 10, "fruit": 10, "plants": 7},
      "Latin", "oliva", "13th Century",
      "From Latin 'oliva' through Old French, the fruit of the olive tree native to the Mediterranean.",
      families=["Food", "Fruit"], related=["oil", "tree", "fruit", "salty"]),

    E("peach", "noun", "K", 1,
      "A round, fuzzy, sweet fruit with a pit inside.",
      {"food": 10, "fruit": 10, "plants": 7},
      "Latin", "persicum", "14th Century",
      "From Latin 'persicum', meaning 'Persian apple', through Old French 'pesche'.",
      families=["Food", "Fruit"], related=["plum", "fruit", "tree", "pit"]),

    E("grape", "noun", "K", 1,
      "A small, round, sweet fruit that grows in bunches on a vine.",
      {"food": 10, "fruit": 10, "plants": 7},
      "Old French", "grape", "13th Century",
      "From Old French 'grape', meaning a cluster, possibly from a Germanic root meaning to hook or pick.",
      families=["Food", "Fruit"], related=["vine", "fruit", "bunch", "wine"]),

    E("melon", "noun", "K", 1,
      "A big, sweet fruit with juicy flesh inside a thick rind.",
      {"food": 10, "fruit": 10, "plants": 7},
      "Greek", "mēlon", "14th Century",
      "From Greek 'mēlopepōn', meaning 'apple-shaped gourd', shortened through Latin and Old French.",
      families=["Food", "Fruit"], related=["fruit", "watermelon", "seed", "rind"]),

    # ============ NATURE / WEATHER ============
    E("sea", "noun", "preK", 1,
      "A very large body of salty water.",
      {"water": 10, "nature": 9, "geography": 8},
      "Old English", "sǣ", "Old English era",
      "From Old English 'sǣ', a core Germanic word for a large body of water.",
      synonyms=["ocean"], families=["Water", "Nature"],
      related=["ocean", "wave", "shore", "fish"]),

    E("air", "noun", "preK", 1,
      "The invisible gas all around us that we breathe.",
      {"science": 9, "weather": 9, "nature": 8},
      "Greek", "aēr", "13th Century",
      "From Greek 'aēr' through Latin 'aer' and Old French 'air', meaning the atmosphere we breathe.",
      synonyms=["atmosphere"], families=["Science", "Nature"],
      related=["wind", "breath", "sky", "weather"]),

    E("fog", "noun", "K", 1,
      "A thick cloud close to the ground that makes it hard to see.",
      {"weather": 10, "nature": 8, "water": 7},
      "Scandinavian", "fok", "16th Century",
      "Likely from a Scandinavian source related to Danish 'fog' meaning spray or shower.",
      synonyms=["mist", "haze"], families=["Weather"],
      related=["mist", "cloud", "morning", "rain"]),

    E("dew", "noun", "1", 2,
      "Tiny drops of water that form on grass and leaves in the morning.",
      {"weather": 9, "nature": 9, "water": 9},
      "Old English", "dēaw", "Old English era",
      "From Old English 'dēaw', shared with Old High German 'tou' and Old Norse 'dögg'.",
      families=["Weather", "Nature"], related=["grass", "morning", "water", "drop"]),

    E("oak", "noun", "K", 1,
      "A big, strong tree with leaves and acorns.",
      {"plants": 10, "trees": 10, "nature": 8},
      "Old English", "āc", "Old English era",
      "From Old English 'āc', a name shared across the Germanic languages for the sturdy hardwood tree.",
      families=["Plants", "Trees"], related=["acorn", "tree", "forest", "wood"]),

    E("hail", "noun", "1", 2,
      "Little balls of ice that fall from storm clouds.",
      {"weather": 10, "science": 7, "water": 7},
      "Old English", "hægel", "Old English era",
      "From Old English 'hægel', shared with Old High German 'hagal' for the icy precipitation.",
      families=["Weather"], related=["ice", "storm", "rain", "snow"]),

    E("hill", "noun", "preK", 1,
      "A raised area of land smaller than a mountain.",
      {"geography": 10, "nature": 8, "landform": 10},
      "Old English", "hyll", "Old English era",
      "From Old English 'hyll', an ancient word for a raised piece of land.",
      families=["Geography", "Nature"], related=["mountain", "slope", "valley", "field"]),

    E("pond", "noun", "preK", 1,
      "A small body of still water, smaller than a lake.",
      {"water": 10, "nature": 8, "geography": 7},
      "Middle English", "pond", "13th Century",
      "From Middle English 'pond', a variant of 'pound', meaning an enclosed area, since ponds were often dammed water enclosures.",
      families=["Water", "Nature"], related=["lake", "frog", "duck", "water"]),

    # ============ BODY ============
    E("ear", "noun", "preK", 1,
      "The part of your body that you use to hear.",
      {"body": 10, "senses": 10, "health": 7},
      "Old English", "ēare", "Old English era",
      "From Old English 'ēare', an ancient body word with cognates in Latin 'auris' and Greek 'ous'.",
      families=["Body", "Senses"], related=["hear", "head", "sound", "listen"]),

    E("eye", "noun", "preK", 1,
      "The part of your body that you use to see.",
      {"body": 10, "senses": 10, "health": 7},
      "Old English", "ēage", "Old English era",
      "From Old English 'ēage', an ancient Germanic word, related to Latin 'oculus' and Greek 'ophthalmos'.",
      families=["Body", "Senses"], related=["see", "face", "look", "tear"]),

    E("lip", "noun", "preK", 1,
      "The soft pink edges of your mouth.",
      {"body": 10, "face": 9, "health": 5},
      "Old English", "lippa", "Old English era",
      "From Old English 'lippa', a core body word in the Germanic languages.",
      families=["Body", "Face"], related=["mouth", "smile", "kiss", "face"]),

    E("arm", "noun", "preK", 1,
      "The part of your body between your shoulder and your hand.",
      {"body": 10, "health": 7},
      "Old English", "earm", "Old English era",
      "From Old English 'earm', an ancient body word with cognates throughout Indo-European languages.",
      families=["Body"], related=["hand", "elbow", "shoulder", "strong"]),

    E("leg", "noun", "preK", 1,
      "The part of your body that you walk and run with.",
      {"body": 10, "health": 7},
      "Old Norse", "leggr", "13th Century",
      "From Old Norse 'leggr', meaning leg or limb, replacing older Old English words.",
      families=["Body"], related=["foot", "knee", "walk", "run"]),

    E("toe", "noun", "preK", 1,
      "One of the five small parts at the end of your foot.",
      {"body": 10, "health": 6},
      "Old English", "tā", "Old English era",
      "From Old English 'tā', a small body word shared across the Germanic languages.",
      families=["Body"], related=["foot", "finger", "nail", "shoe"]),

    E("jaw", "noun", "K", 2,
      "The bone that holds your teeth and helps you chew.",
      {"body": 10, "face": 8, "health": 6},
      "Middle English", "jowe", "14th Century",
      "From Middle English 'jowe', of uncertain origin, possibly from Old French 'joue' meaning cheek.",
      families=["Body", "Face"], related=["mouth", "teeth", "chin", "chew"]),

    E("hip", "noun", "K", 1,
      "The side of your body where your leg connects to your trunk.",
      {"body": 10, "health": 7},
      "Old English", "hype", "Old English era",
      "From Old English 'hype', a core body word in the Germanic languages.",
      families=["Body"], related=["leg", "waist", "joint", "side"]),

    E("nose", "noun", "preK", 1,
      "The part of your face that you smell with.",
      {"body": 10, "face": 10, "senses": 10},
      "Old English", "nosu", "Old English era",
      "From Old English 'nosu', a core Germanic body word, related to Latin 'nasus'.",
      families=["Body", "Face", "Senses"], related=["smell", "face", "breath", "sneeze"]),

    E("chin", "noun", "preK", 1,
      "The bottom part of your face below your mouth.",
      {"body": 10, "face": 10},
      "Old English", "cinn", "Old English era",
      "From Old English 'cinn', a Germanic body word, related to Latin 'gena' meaning cheek.",
      families=["Body", "Face"], related=["jaw", "face", "mouth", "neck"]),

    E("hand", "noun", "preK", 1,
      "The part of your body with five fingers, at the end of your arm.",
      {"body": 10, "health": 7},
      "Old English", "hand", "Old English era",
      "From Old English 'hand', a core Germanic body word unchanged for over a thousand years.",
      families=["Body"], related=["arm", "finger", "thumb", "wrist"]),

    E("foot", "noun", "preK", 1,
      "The part of your body at the bottom of your leg that you stand on.",
      {"body": 10, "health": 7},
      "Old English", "fōt", "Old English era",
      "From Old English 'fōt', shared with Latin 'pes' and Greek 'pous' in the Indo-European family.",
      families=["Body"], related=["leg", "toe", "shoe", "walk"]),

    E("knee", "noun", "preK", 1,
      "The bendy joint in the middle of your leg.",
      {"body": 10, "health": 7},
      "Old English", "cnēow", "Old English era",
      "From Old English 'cnēow', related to Latin 'genu' and Greek 'gony'.",
      families=["Body"], related=["leg", "joint", "bend", "kneel"]),

    E("head", "noun", "preK", 1,
      "The top part of your body, where your face and brain are.",
      {"body": 10, "health": 7},
      "Old English", "hēafod", "Old English era",
      "From Old English 'hēafod', a core Germanic body word with cognates across Indo-European languages.",
      families=["Body"], related=["face", "hair", "brain", "neck"]),

    E("elbow", "noun", "K", 1,
      "The bendy joint in the middle of your arm.",
      {"body": 10, "health": 7},
      "Old English", "elnboga", "Old English era",
      "From Old English 'elnboga', meaning the bend of the forearm.",
      families=["Body"], related=["arm", "joint", "bend", "wrist"]),

    E("wrist", "noun", "K", 1,
      "The bendy part of your arm right before your hand.",
      {"body": 10, "health": 7},
      "Old English", "wrist", "Old English era",
      "From Old English 'wrist', a core Germanic body word for the joint that turns the hand.",
      families=["Body"], related=["hand", "arm", "joint", "watch"]),

    E("thumb", "noun", "K", 1,
      "The short, thick finger on the side of your hand.",
      {"body": 10, "health": 6},
      "Old English", "þūma", "Old English era",
      "From Old English 'þūma', a core Germanic word for the strong, opposable digit.",
      families=["Body"], related=["finger", "hand", "grip", "nail"]),

    E("mouth", "noun", "preK", 1,
      "The opening in your face that you eat and talk with.",
      {"body": 10, "face": 10},
      "Old English", "mūþ", "Old English era",
      "From Old English 'mūþ', shared with Old High German 'mund' and Latin 'mentum'.",
      families=["Body", "Face"], related=["lip", "tongue", "teeth", "talk"]),

    # ============ HOME ============
    E("cup", "noun", "preK", 1,
      "A small container with a handle that you drink from.",
      {"home": 10, "objects": 9, "kitchen": 9},
      "Latin", "cuppa", "Old English era",
      "From Latin 'cuppa', a drinking vessel, borrowed into Old English as 'cuppe'.",
      families=["Home", "Kitchen"], related=["drink", "mug", "tea", "water"]),

    E("jar", "noun", "K", 1,
      "A glass container with a lid, often used for storing food.",
      {"home": 10, "kitchen": 9, "objects": 8},
      "Arabic", "jarrah", "16th Century",
      "From Arabic 'jarrah', a large earthen vessel, through French 'jarre'.",
      families=["Home", "Kitchen"], related=["jam", "lid", "glass", "container"]),

    E("bag", "noun", "preK", 1,
      "A soft container with handles for carrying things.",
      {"home": 10, "objects": 9, "school": 7},
      "Old Norse", "baggi", "13th Century",
      "From Old Norse 'baggi', meaning a bundle or pack, brought to English by Norse settlers.",
      synonyms=["sack", "pouch"], families=["Home", "Objects"],
      related=["sack", "backpack", "carry", "shopping"]),

    E("pen", "noun", "preK", 1,
      "A stick you write with using ink.",
      {"school": 10, "writing": 10, "objects": 8},
      "Latin", "penna", "13th Century",
      "From Latin 'penna' meaning feather, since early pens were made from sharpened quill feathers.",
      synonyms=["pencil"], families=["School", "Writing"],
      related=["ink", "write", "paper", "pencil"]),

    E("hat", "noun", "preK", 1,
      "Clothing you wear on top of your head.",
      {"clothing": 10, "objects": 8, "home": 6},
      "Old English", "hætt", "Old English era",
      "From Old English 'hætt', meaning hood or head covering.",
      families=["Clothing"], related=["head", "cap", "scarf", "winter"]),

    E("mat", "noun", "preK", 1,
      "A flat thing on the floor you stand or sit on.",
      {"home": 10, "objects": 9},
      "Latin", "matta", "Old English era",
      "From Latin 'matta' through Old English 'meatte', a woven floor covering.",
      families=["Home"], related=["rug", "floor", "carpet", "doormat"]),

    E("pot", "noun", "preK", 1,
      "A round container used for cooking food or growing plants.",
      {"home": 10, "kitchen": 9, "objects": 8},
      "Old English", "pott", "Old English era",
      "From Old English 'pott', possibly from Late Latin 'pottus', a deep vessel.",
      families=["Home", "Kitchen"], related=["pan", "lid", "cook", "kettle"]),

    E("pan", "noun", "preK", 1,
      "A wide, flat metal pan used for cooking.",
      {"home": 10, "kitchen": 10, "objects": 8},
      "Old English", "panne", "Old English era",
      "From Old English 'panne', a shallow cooking vessel, with cognates throughout the Germanic languages.",
      families=["Home", "Kitchen"], related=["pot", "cook", "stove", "fry"]),

    E("fan", "noun", "preK", 1,
      "A thing that spins to move air and cool you down.",
      {"home": 10, "objects": 9, "weather": 6},
      "Latin", "vannus", "Old English era",
      "From Latin 'vannus' through Old English 'fann', originally a tool for separating grain by moving air.",
      families=["Home", "Objects"], related=["air", "wind", "cool", "blow"]),

    E("lid", "noun", "K", 1,
      "The top cover of a container, like a pot or jar.",
      {"home": 10, "kitchen": 8, "objects": 9},
      "Old English", "hlid", "Old English era",
      "From Old English 'hlid', meaning a covering or gate.",
      synonyms=["cover", "cap"], families=["Home", "Objects"],
      related=["jar", "pot", "cover", "top"]),

    E("rug", "noun", "preK", 1,
      "A soft floor covering smaller than a carpet.",
      {"home": 10, "objects": 8},
      "Scandinavian", "rugga", "16th Century",
      "From a Scandinavian source like Norwegian 'rugga' meaning a coarse coverlet.",
      synonyms=["carpet", "mat"], families=["Home"],
      related=["mat", "floor", "carpet", "wool"]),

    E("desk", "noun", "preK", 1,
      "A flat table used for writing, working, or studying.",
      {"home": 10, "school": 10, "objects": 8},
      "Latin", "desca", "14th Century",
      "From Medieval Latin 'desca', meaning a table or board for writing.",
      families=["Home", "School"], related=["table", "school", "chair", "study"]),

    E("fork", "noun", "preK", 1,
      "A tool with sharp points used for eating food.",
      {"home": 10, "kitchen": 10, "objects": 9},
      "Latin", "furca", "Old English era",
      "From Latin 'furca' through Old English 'forca', a forked tool.",
      families=["Home", "Kitchen"], related=["spoon", "knife", "plate", "eat"]),

    E("soap", "noun", "preK", 1,
      "What you use with water to wash your hands clean.",
      {"home": 10, "health": 9, "objects": 7},
      "Old English", "sāpe", "Old English era",
      "From Old English 'sāpe', a Germanic word for the cleaning substance.",
      families=["Home", "Health"], related=["wash", "water", "bath", "bubble"]),

    E("door", "noun", "preK", 1,
      "What you open to go in or out of a room or building.",
      {"home": 10, "objects": 9, "building": 9},
      "Old English", "duru", "Old English era",
      "From Old English 'duru', a core Germanic word with cognates in Latin 'foris' and Greek 'thyra'.",
      families=["Home", "Building"], related=["room", "open", "knob", "key"]),

    E("roof", "noun", "preK", 1,
      "The top of a house that keeps the rain out.",
      {"home": 10, "building": 10, "objects": 7},
      "Old English", "hrōf", "Old English era",
      "From Old English 'hrōf', meaning the covering of a building.",
      families=["Home", "Building"], related=["house", "wall", "ceiling", "rain"]),

    E("wall", "noun", "preK", 1,
      "The flat side of a room or building.",
      {"home": 10, "building": 10, "objects": 7},
      "Latin", "vallum", "Old English era",
      "From Latin 'vallum' meaning rampart, through Old English 'weall', the upright side of a structure.",
      families=["Home", "Building"], related=["room", "roof", "floor", "paint"]),

    E("bowl", "noun", "preK", 1,
      "A round, deep dish you eat soup or cereal from.",
      {"home": 10, "kitchen": 10, "objects": 8},
      "Old English", "bolla", "Old English era",
      "From Old English 'bolla', a round vessel.",
      families=["Home", "Kitchen"], related=["plate", "soup", "spoon", "dish"]),

    E("sock", "noun", "preK", 1,
      "Soft cloth you wear on your foot inside your shoe.",
      {"clothing": 10, "objects": 7},
      "Latin", "soccus", "Old English era",
      "From Latin 'soccus' meaning a light slipper, through Old English 'socc'.",
      families=["Clothing"], related=["shoe", "foot", "boot", "warm"]),

    E("boot", "noun", "K", 1,
      "A strong, tall shoe for cold or wet weather.",
      {"clothing": 10, "objects": 7},
      "Old French", "bote", "14th Century",
      "From Old French 'bote', for a heavy shoe that covers the foot and lower leg.",
      families=["Clothing"], related=["shoe", "foot", "winter", "rain"]),

    E("ring", "noun", "preK", 1,
      "A small circle of metal you wear on your finger.",
      {"clothing": 8, "objects": 9, "shapes": 8},
      "Old English", "hring", "Old English era",
      "From Old English 'hring', meaning a circular band of any kind.",
      families=["Objects", "Shapes"], related=["circle", "finger", "gold", "wedding"]),

    E("bell", "noun", "preK", 1,
      "A hollow metal cup that rings when you shake it.",
      {"objects": 9, "music": 8, "home": 6},
      "Old English", "belle", "Old English era",
      "From Old English 'belle', possibly imitative of the ringing sound.",
      families=["Objects", "Music"], related=["ring", "sound", "metal", "door"]),

    E("spoon", "noun", "preK", 1,
      "A small tool with a round end for eating or stirring food.",
      {"home": 10, "kitchen": 10, "objects": 9},
      "Old English", "spōn", "Old English era",
      "From Old English 'spōn' meaning a chip of wood, since early spoons were carved from wood.",
      families=["Home", "Kitchen"], related=["fork", "bowl", "stir", "soup"]),

    E("plate", "noun", "preK", 1,
      "A flat round dish you eat food from.",
      {"home": 10, "kitchen": 10, "objects": 9},
      "Old French", "plate", "13th Century",
      "From Old French 'plate' meaning flat, since plates are flat dishes.",
      families=["Home", "Kitchen"], related=["bowl", "fork", "dish", "food"]),

    # ============ COLORS ============
    E("tan", "adj", "K", 1,
      "Having a light brown color, like sand or wheat.",
      {"color": 10, "art": 7},
      "Old French", "tan", "16th Century",
      "From Old French 'tan' meaning oak bark, used to tan leather to a light brown color.",
      synonyms=["beige", "khaki"], families=["Colors"],
      related=["brown", "sand", "wheat", "skin"]),

    # ============ NUMBERS ============
    E("one", "noun", "preK", 1,
      "The number 1, the first counting number.",
      {"math": 10, "numbers": 10},
      "Old English", "ān", "Old English era",
      "From Old English 'ān', the same root that gives us 'an' and 'a'.",
      families=["Numbers", "Math"], related=["two", "first", "single", "count"]),

    E("two", "noun", "preK", 1,
      "The number 2, one more than one.",
      {"math": 10, "numbers": 10},
      "Old English", "twā", "Old English era",
      "From Old English 'twā', shared across the Indo-European language family.",
      families=["Numbers", "Math"], related=["one", "three", "pair", "count"]),

    E("three", "noun", "preK", 1,
      "The number 3, one more than two.",
      {"math": 10, "numbers": 10},
      "Old English", "þrēo", "Old English era",
      "From Old English 'þrēo', shared across the Indo-European languages, related to Latin 'tres'.",
      families=["Numbers", "Math"], related=["two", "four", "triple", "count"]),

    E("four", "noun", "preK", 1,
      "The number 4, one more than three.",
      {"math": 10, "numbers": 10},
      "Old English", "fēower", "Old English era",
      "From Old English 'fēower', related to Latin 'quattuor' and Greek 'tessares'.",
      families=["Numbers", "Math"], related=["three", "five", "square", "count"]),

    E("five", "noun", "preK", 1,
      "The number 5, one more than four.",
      {"math": 10, "numbers": 10},
      "Old English", "fīf", "Old English era",
      "From Old English 'fīf', related to Latin 'quinque' and Greek 'pente'.",
      families=["Numbers", "Math"], related=["four", "six", "hand", "count"]),

    E("six", "noun", "preK", 1,
      "The number 6, one more than five.",
      {"math": 10, "numbers": 10},
      "Old English", "siex", "Old English era",
      "From Old English 'siex', related to Latin 'sex' and Greek 'hex'.",
      families=["Numbers", "Math"], related=["five", "seven", "die", "count"]),

    E("seven", "noun", "preK", 1,
      "The number 7, one more than six.",
      {"math": 10, "numbers": 10},
      "Old English", "seofon", "Old English era",
      "From Old English 'seofon', related to Latin 'septem' and Greek 'hepta'.",
      families=["Numbers", "Math"], related=["six", "eight", "week", "count"]),

    E("eight", "noun", "preK", 1,
      "The number 8, one more than seven.",
      {"math": 10, "numbers": 10},
      "Old English", "eahta", "Old English era",
      "From Old English 'eahta', related to Latin 'octo' and Greek 'okto'.",
      families=["Numbers", "Math"], related=["seven", "nine", "octopus", "count"]),

    E("nine", "noun", "preK", 1,
      "The number 9, one more than eight.",
      {"math": 10, "numbers": 10},
      "Old English", "nigon", "Old English era",
      "From Old English 'nigon', related to Latin 'novem' and Greek 'ennea'.",
      families=["Numbers", "Math"], related=["eight", "ten", "lives", "count"]),

    E("ten", "noun", "preK", 1,
      "The number 10, the count of all your fingers.",
      {"math": 10, "numbers": 10},
      "Old English", "tien", "Old English era",
      "From Old English 'tien', related to Latin 'decem' and Greek 'deka'.",
      families=["Numbers", "Math"], related=["nine", "eleven", "decade", "fingers"]),

    E("zero", "noun", "K", 1,
      "The number 0, meaning none or nothing.",
      {"math": 10, "numbers": 10},
      "Arabic", "ṣifr", "17th Century",
      "From Arabic 'ṣifr' meaning empty, through Italian 'zero'. The same root gives us 'cipher'.",
      synonyms=["nothing", "none"], families=["Numbers", "Math"],
      related=["empty", "none", "count", "math"]),

    # ============ ACTIONS ============
    E("run", "verb", "preK", 1,
      "To move on your feet very quickly.",
      {"action": 10, "sport": 8, "movement": 10},
      "Old English", "rinnan", "Old English era",
      "From Old English 'rinnan', meaning to flow or run, related to Old Norse 'renna'.",
      synonyms=["dash", "sprint"], antonyms=["walk"], families=["Actions", "Sports"],
      related=["jog", "sprint", "race", "fast"]),

    E("eat", "verb", "preK", 1,
      "To put food in your mouth and swallow it.",
      {"action": 10, "food": 9, "body": 8},
      "Old English", "etan", "Old English era",
      "From Old English 'etan', related to Latin 'edere' and Greek 'edein', all from the same Indo-European root.",
      synonyms=["consume", "munch"], families=["Actions", "Food"],
      related=["food", "chew", "swallow", "drink"]),

    E("see", "verb", "preK", 1,
      "To use your eyes to look at something.",
      {"action": 10, "senses": 10, "body": 8},
      "Old English", "sēon", "Old English era",
      "From Old English 'sēon', a core sensory verb shared across the Germanic languages.",
      synonyms=["look", "view"], families=["Actions", "Senses"],
      related=["eye", "look", "watch", "view"]),

    E("hug", "verb", "preK", 1,
      "To hold someone tightly with your arms to show love.",
      {"action": 10, "emotion": 8, "love": 9},
      "Possibly Old Norse", "hugga", "16th Century",
      "Possibly from Old Norse 'hugga' meaning to comfort, of uncertain English origin.",
      synonyms=["embrace", "cuddle"], families=["Actions", "Emotions"],
      related=["love", "embrace", "warm", "arms"]),

    E("hop", "verb", "preK", 1,
      "To jump quickly with one foot, or on the ground.",
      {"action": 10, "movement": 10, "sport": 6},
      "Old English", "hoppian", "Old English era",
      "From Old English 'hoppian', meaning to leap, related to Old Norse 'hoppa'.",
      synonyms=["jump", "skip"], families=["Actions", "Movement"],
      related=["jump", "skip", "frog", "bounce"]),

    E("sit", "verb", "preK", 1,
      "To rest your body on a chair or the ground.",
      {"action": 10, "movement": 7},
      "Old English", "sittan", "Old English era",
      "From Old English 'sittan', a core verb shared across the Indo-European languages.",
      antonyms=["stand"], families=["Actions"],
      related=["stand", "chair", "rest", "lap"]),

    E("bake", "verb", "K", 1,
      "To cook food in an oven.",
      {"action": 10, "food": 9, "cooking": 10},
      "Old English", "bacan", "Old English era",
      "From Old English 'bacan', a Germanic verb for cooking with dry heat.",
      synonyms=["roast"], families=["Actions", "Cooking"],
      related=["oven", "bread", "cake", "cook"]),

    E("make", "verb", "preK", 1,
      "To build or create something.",
      {"action": 10, "creation": 9},
      "Old English", "macian", "Old English era",
      "From Old English 'macian', meaning to make, build, or shape, related to Old High German 'mahhon'.",
      synonyms=["create", "build"], families=["Actions"],
      related=["build", "create", "do", "form"]),

    E("give", "verb", "preK", 1,
      "To hand something to someone.",
      {"action": 10, "sharing": 9},
      "Old English", "giefan", "Old English era",
      "From Old English 'giefan', influenced later by Old Norse 'gefa'.",
      synonyms=["hand", "present"], antonyms=["take"], families=["Actions"],
      related=["take", "share", "gift", "offer"]),

    E("find", "verb", "preK", 1,
      "To discover something you were looking for.",
      {"action": 10, "discovery": 9},
      "Old English", "findan", "Old English era",
      "From Old English 'findan', related to Old Norse 'finna' and Old High German 'findan'.",
      synonyms=["discover", "locate"], antonyms=["lose"], families=["Actions"],
      related=["lose", "search", "discover", "hunt"]),

    E("play", "verb", "preK", 1,
      "To have fun with games or toys.",
      {"action": 10, "fun": 10, "games": 9},
      "Old English", "plegan", "Old English era",
      "From Old English 'plegan', meaning to engage in activity or sport.",
      antonyms=["work"], families=["Actions", "Games"],
      related=["game", "toy", "fun", "sport"]),

    E("read", "verb", "preK", 1,
      "To look at words and understand what they mean.",
      {"action": 10, "learning": 10, "school": 9},
      "Old English", "rædan", "Old English era",
      "From Old English 'rædan', originally meaning to give advice or interpret, narrowing to interpreting written words.",
      families=["Actions", "Learning"], related=["book", "learn", "word", "page"]),

    E("swim", "verb", "K", 1,
      "To move through water using your arms and legs.",
      {"action": 10, "sport": 9, "water": 9},
      "Old English", "swimman", "Old English era",
      "From Old English 'swimman', a core Germanic verb for moving through water.",
      families=["Actions", "Sports"], related=["water", "pool", "fish", "float"]),

    E("skip", "verb", "K", 1,
      "To move forward by hopping from one foot to the other.",
      {"action": 10, "movement": 10},
      "Old Norse", "skopa", "14th Century",
      "Possibly from Old Norse 'skopa' meaning to leap, brought into English by Norse settlers.",
      synonyms=["hop"], families=["Actions", "Movement"],
      related=["hop", "jump", "play", "rope"]),

    E("walk", "verb", "preK", 1,
      "To move on your feet at a slow, steady pace.",
      {"action": 10, "movement": 10, "exercise": 7},
      "Old English", "wealcan", "Old English era",
      "From Old English 'wealcan', originally meaning to roll or toss, later narrowing to mean to move on foot.",
      antonyms=["run"], families=["Actions", "Movement"],
      related=["run", "step", "stroll", "feet"]),

    E("jump", "verb", "preK", 1,
      "To push off the ground with both feet.",
      {"action": 10, "movement": 10, "sport": 7},
      "English", "jump", "16th Century",
      "Of uncertain origin, possibly imitative of the sound of feet landing.",
      synonyms=["leap", "hop"], families=["Actions", "Movement"],
      related=["hop", "leap", "spring", "bounce"]),

    E("sing", "verb", "preK", 1,
      "To make music with your voice.",
      {"action": 10, "music": 10, "voice": 9},
      "Old English", "singan", "Old English era",
      "From Old English 'singan', a core Germanic verb shared with Old High German 'singan'.",
      families=["Actions", "Music"], related=["song", "music", "voice", "choir"]),

    E("dance", "verb", "preK", 1,
      "To move your body in rhythm to music.",
      {"action": 10, "music": 9, "movement": 9},
      "Old French", "dancier", "13th Century",
      "From Old French 'dancier', of uncertain earlier origin, possibly Frankish.",
      families=["Actions", "Music"], related=["music", "rhythm", "move", "ballet"]),

    E("sleep", "verb", "preK", 1,
      "To rest with your eyes closed, usually at night.",
      {"action": 9, "health": 9, "rest": 10},
      "Old English", "slǣpan", "Old English era",
      "From Old English 'slǣpan', a core Germanic verb related to Old High German 'slāfan'.",
      synonyms=["rest", "doze"], antonyms=["wake"], families=["Actions", "Health"],
      related=["bed", "dream", "night", "rest"]),

    E("draw", "verb", "preK", 1,
      "To make a picture with a pencil, pen, or crayon.",
      {"action": 10, "art": 10, "creation": 8},
      "Old English", "dragan", "Old English era",
      "From Old English 'dragan' meaning to pull or carry, later expanding to mean tracing lines on paper.",
      synonyms=["sketch"], families=["Actions", "Art"],
      related=["pencil", "paper", "art", "sketch"]),

    # ============ TIME ============
    E("day", "noun", "preK", 1,
      "The time when the sun is up and the sky is bright.",
      {"time": 10, "weather": 6, "nature": 6},
      "Old English", "dæg", "Old English era",
      "From Old English 'dæg', a core Germanic word related to Old High German 'tag'.",
      antonyms=["night"], families=["Time"],
      related=["sun", "morning", "night", "week"]),

    E("age", "noun", "K", 2,
      "How old someone or something is.",
      {"time": 9, "life": 8},
      "Latin", "aetas", "13th Century",
      "From Latin 'aetas' through Old French 'aage', meaning a length of life.",
      synonyms=["years"], families=["Time"],
      related=["old", "young", "year", "birthday"]),

    E("hour", "noun", "K", 1,
      "Sixty minutes of time, one twenty-fourth of a day.",
      {"time": 10, "math": 6},
      "Greek", "hōra", "13th Century",
      "From Greek 'hōra' through Latin 'hora' and Old French 'ore', meaning a fixed time or season.",
      families=["Time"], related=["minute", "clock", "time", "day"]),

    E("week", "noun", "K", 1,
      "A group of seven days, from Sunday to Saturday.",
      {"time": 10},
      "Old English", "wice", "Old English era",
      "From Old English 'wice', a core Germanic word for a cycle of seven days.",
      families=["Time"], related=["day", "month", "year", "calendar"]),

    E("year", "noun", "K", 1,
      "Three hundred sixty-five days, or twelve months.",
      {"time": 10, "math": 5},
      "Old English", "gēar", "Old English era",
      "From Old English 'gēar', related to Greek 'hōros' meaning a year or season.",
      families=["Time"], related=["month", "season", "birthday", "calendar"]),

    E("noon", "noun", "K", 1,
      "The middle of the day, twelve o'clock.",
      {"time": 10},
      "Latin", "nona", "Old English era",
      "From Latin 'nona' meaning ninth hour. The English meaning shifted from 3 PM to midday over time.",
      synonyms=["midday"], antonyms=["midnight"], families=["Time"],
      related=["day", "morning", "afternoon", "lunch"]),

    E("night", "noun", "preK", 1,
      "The dark time after the sun goes down.",
      {"time": 10, "nature": 7},
      "Old English", "niht", "Old English era",
      "From Old English 'niht', a core Indo-European word related to Latin 'nox' and Greek 'nyx'.",
      antonyms=["day"], families=["Time"],
      related=["day", "sleep", "moon", "dark"]),

    # ============ ADJECTIVES ============
    E("hot", "adj", "preK", 1,
      "Having a high temperature, like fire or a sunny day.",
      {"weather": 8, "senses": 8, "temperature": 10},
      "Old English", "hāt", "Old English era",
      "From Old English 'hāt', a core sensory adjective in the Germanic languages.",
      synonyms=["warm", "burning"], antonyms=["cold"], families=["Senses", "Weather"],
      related=["warm", "fire", "sun", "burn"]),

    E("wet", "adj", "preK", 1,
      "Covered in water or another liquid.",
      {"weather": 7, "water": 9, "senses": 7},
      "Old English", "wǣt", "Old English era",
      "From Old English 'wǣt', meaning damp or moist.",
      synonyms=["damp", "soaked"], antonyms=["dry"], families=["Senses", "Weather"],
      related=["dry", "water", "rain", "splash"]),

    E("dry", "adj", "preK", 1,
      "Without any water or liquid on it.",
      {"weather": 7, "water": 6, "senses": 7},
      "Old English", "drȳge", "Old English era",
      "From Old English 'drȳge', related to Old High German 'trockan'.",
      antonyms=["wet"], families=["Senses", "Weather"],
      related=["wet", "desert", "towel", "thirsty"]),

    E("old", "adj", "preK", 1,
      "Having been around for a long time.",
      {"time": 9, "age": 10},
      "Old English", "eald", "Old English era",
      "From Old English 'eald', related to Old High German 'alt' and Latin 'altus' meaning grown up.",
      synonyms=["aged", "ancient"], antonyms=["new"], families=["Time"],
      related=["new", "age", "ancient", "antique"]),

    E("new", "adj", "preK", 1,
      "Just made, just bought, or just discovered.",
      {"time": 9, "age": 10},
      "Old English", "nīwe", "Old English era",
      "From Old English 'nīwe', related to Latin 'novus' and Greek 'neos'.",
      synonyms=["fresh", "brand-new"], antonyms=["old"], families=["Time"],
      related=["old", "fresh", "modern", "newborn"]),

    E("loud", "adj", "preK", 1,
      "Making a lot of noise that is easy to hear.",
      {"sound": 10, "senses": 9},
      "Old English", "hlūd", "Old English era",
      "From Old English 'hlūd', a core sound word related to Latin 'inclutus' meaning famous.",
      antonyms=["quiet", "soft"], families=["Senses", "Sound"],
      related=["quiet", "noise", "drum", "shout"]),

    E("tiny", "adj", "K", 1,
      "Very, very small.",
      {"size": 10, "senses": 6},
      "Middle English", "tine", "16th Century",
      "From Middle English 'tine' meaning a very small amount or piece, plus the -y ending.",
      synonyms=["small", "little"], antonyms=["huge", "big"], families=["Size"],
      related=["small", "little", "mini", "ant"]),

    E("fast", "adj", "preK", 1,
      "Moving very quickly.",
      {"speed": 10, "sport": 7},
      "Old English", "fæst", "Old English era",
      "From Old English 'fæst', originally meaning firm or fixed, later coming to mean quick.",
      synonyms=["quick", "speedy"], antonyms=["slow"], families=["Speed"],
      related=["slow", "quick", "race", "speed"]),

    E("slow", "adj", "preK", 1,
      "Moving without much speed.",
      {"speed": 10},
      "Old English", "slāw", "Old English era",
      "From Old English 'slāw', meaning sluggish or dull.",
      antonyms=["fast", "quick"], families=["Speed"],
      related=["fast", "turtle", "creep", "snail"]),

    E("kind", "adj", "K", 1,
      "Being nice, caring, and gentle to others.",
      {"emotion": 10, "behavior": 10, "character": 9},
      "Old English", "cynd", "Old English era",
      "From Old English 'cynd' meaning natural or innate, related to 'kin' (family).",
      synonyms=["gentle", "caring"], antonyms=["cruel", "mean"], families=["Character"],
      related=["nice", "gentle", "caring", "friend"]),

    E("full", "adj", "preK", 1,
      "Holding all that can fit, with no more room.",
      {"size": 8, "amount": 10},
      "Old English", "full", "Old English era",
      "From Old English 'full', a core Germanic adjective shared with Old Norse 'fullr'.",
      antonyms=["empty"], families=["Quantity"],
      related=["empty", "filled", "stuffed", "more"]),

    E("round", "adj", "preK", 1,
      "Shaped like a circle or a ball.",
      {"shape": 10, "geometry": 9},
      "Latin", "rotundus", "13th Century",
      "From Latin 'rotundus' meaning wheel-shaped, through Old French 'roond'.",
      synonyms=["circular"], antonyms=["square"], families=["Shapes"],
      related=["circle", "ball", "wheel", "sphere"]),

    E("sharp", "adj", "K", 1,
      "Having a point or edge that can cut.",
      {"senses": 8, "objects": 7},
      "Old English", "scearp", "Old English era",
      "From Old English 'scearp', a core sensory word in the Germanic languages.",
      synonyms=["pointy", "keen"], antonyms=["dull", "blunt"], families=["Senses"],
      related=["knife", "point", "edge", "needle"]),

    # ============ EXTRA: COMMON SINGLE WORDS ============
    E("rose", "noun", "K", 1,
      "A flower with a sweet smell and thorns on its stem.",
      {"plants": 10, "flowers": 10, "nature": 7},
      "Latin", "rosa", "Old English era",
      "From Latin 'rosa' through Old English 'rōse', a name for the thorny flowering plant.",
      families=["Plants", "Flowers"], related=["flower", "thorn", "garden", "petal"]),
]


def main():
    # Load existing lexicon
    if not os.path.exists(LEXICON_PATH):
        print(f"ERROR: lexicon not found at {LEXICON_PATH}", file=sys.stderr)
        sys.exit(1)
    with open(LEXICON_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)
    existing_words = {w["word"].lower() for w in existing}

    # Dedupe
    seen = set()
    output = []
    skipped_dup_lexicon = []
    skipped_dup_self = []
    for entry in ENTRIES:
        w = entry["word"].lower()
        if w in existing_words:
            skipped_dup_lexicon.append(w)
            continue
        if w in seen:
            skipped_dup_self.append(w)
            continue
        seen.add(w)
        output.append(entry)

    # Write
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"Wrote {len(output)} entries to {OUTPUT_PATH}")
    if skipped_dup_lexicon:
        print(f"Skipped {len(skipped_dup_lexicon)} already in lexicon: {sorted(skipped_dup_lexicon)}")
    if skipped_dup_self:
        print(f"Skipped {len(skipped_dup_self)} self-duplicates: {sorted(skipped_dup_self)}")


if __name__ == "__main__":
    main()
