// Road-trip quiz bank. Read aloud by a parent; kid answers verbally, parent taps the match.
// difficulty: 1 (easiest, 4yo) .. 5 (5yo stretch). type: "mc" | "tf" | "open".
const QUESTIONS = [
  // ---------- MATH ----------
  { cat: "Math", type: "mc", diff: 1, q: "What is 2 + 2?", choices: ["3", "4", "5"], answer: "4" },
  { cat: "Math", type: "mc", diff: 1, q: "What is 4 + 7?", choices: ["9", "10", "11"], answer: "11" },
  { cat: "Math", type: "mc", diff: 1, q: "What is 5 + 3?", choices: ["7", "8", "9"], answer: "8" },
  { cat: "Math", type: "mc", diff: 1, q: "What is 3 + 3?", choices: ["5", "6", "7"], answer: "6" },
  { cat: "Math", type: "mc", diff: 1, q: "How many wheels does a car have?", choices: ["2", "3", "4"], answer: "4" },
  { cat: "Math", type: "mc", diff: 1, q: "How many fingers do you have on one hand?", choices: ["4", "5", "6"], answer: "5" },
  { cat: "Math", type: "tf", diff: 1, q: "5 is bigger than 3.", answer: "True" },
  { cat: "Math", type: "tf", diff: 1, q: "1 + 1 = 3", answer: "False" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 6 + 6?", choices: ["11", "12", "13"], answer: "12" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 10 - 4?", choices: ["5", "6", "7"], answer: "6" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 9 - 3?", choices: ["5", "6", "7"], answer: "6" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 8 + 5?", choices: ["12", "13", "14"], answer: "13" },
  { cat: "Math", type: "mc", diff: 2, q: "What number comes right after 19?", choices: ["18", "20", "21"], answer: "20" },
  { cat: "Math", type: "mc", diff: 2, q: "What is half of 10?", choices: ["4", "5", "6"], answer: "5" },
  { cat: "Math", type: "tf", diff: 2, q: "10 - 4 = 6", answer: "True" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 11 - 4?", choices: ["6", "7", "8"], answer: "7" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 7 + 8?", choices: ["14", "15", "16"], answer: "15" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 12 - 5?", choices: ["6", "7", "8"], answer: "7" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 3 x 2?", choices: ["5", "6", "7"], answer: "6" },
  { cat: "Math", type: "mc", diff: 3, q: "How many days are in a week?", choices: ["5", "6", "7"], answer: "7" },
  { cat: "Math", type: "mc", diff: 4, q: "What is 15 - 7?", choices: ["7", "8", "9"], answer: "8" },
  { cat: "Math", type: "mc", diff: 4, q: "What is 4 x 4?", choices: ["12", "14", "16"], answer: "16" },
  { cat: "Math", type: "mc", diff: 4, q: "How many months are in a year?", choices: ["10", "11", "12"], answer: "12" },
  { cat: "Math", type: "open", diff: 4, q: "Can you count backwards from 10 to 1?" },
  { cat: "Math", type: "mc", diff: 5, q: "What is 20 - 8?", choices: ["11", "12", "13"], answer: "12" },
  { cat: "Math", type: "mc", diff: 5, q: "What is 6 x 5?", choices: ["25", "30", "35"], answer: "30" },

  // ---------- VOCABULARY ----------
  { cat: "Words", type: "mc", diff: 1, q: "What does 'happy' mean?", choices: ["Sad", "Feeling good and glad", "Tired"], answer: "Feeling good and glad" },
  { cat: "Words", type: "mc", diff: 1, q: "What does 'big' mean?", choices: ["Small", "Large in size", "Fast"], answer: "Large in size" },
  { cat: "Words", type: "mc", diff: 1, q: "What is the opposite of 'up'?", choices: ["Down", "Left", "Fast"], answer: "Down" },
  { cat: "Words", type: "mc", diff: 1, q: "What is the opposite of 'hot'?", choices: ["Cold", "Loud", "Wet"], answer: "Cold" },
  { cat: "Words", type: "mc", diff: 2, q: "What does 'tough' mean?", choices: ["Soft and easy", "Hard or strong", "Colorful"], answer: "Hard or strong" },
  { cat: "Words", type: "mc", diff: 2, q: "What does 'tiny' mean?", choices: ["Very small", "Very loud", "Very tall"], answer: "Very small" },
  { cat: "Words", type: "mc", diff: 2, q: "What does 'exhausted' mean?", choices: ["Very excited", "Very hungry", "Very tired"], answer: "Very tired" },
  { cat: "Words", type: "mc", diff: 2, q: "What is the opposite of 'full'?", choices: ["Empty", "Heavy", "Round"], answer: "Empty" },
  { cat: "Words", type: "mc", diff: 3, q: "What does 'future' mean?", choices: ["Time that already happened", "Time that hasn't happened yet", "Right now"], answer: "Time that hasn't happened yet" },
  { cat: "Words", type: "mc", diff: 3, q: "What does 'brave' mean?", choices: ["Scared of everything", "Not afraid to do hard things", "Very sleepy"], answer: "Not afraid to do hard things" },
  { cat: "Words", type: "mc", diff: 3, q: "What does 'ancient' mean?", choices: ["Very new", "Very, very old", "Very fast"], answer: "Very, very old" },
  { cat: "Words", type: "mc", diff: 3, q: "What is the opposite of 'begin'?", choices: ["Start", "Finish", "Middle"], answer: "Finish" },
  { cat: "Words", type: "mc", diff: 4, q: "What does 'curious' mean?", choices: ["Wanting to learn or know more", "Feeling angry", "Feeling sleepy"], answer: "Wanting to learn or know more" },
  { cat: "Words", type: "mc", diff: 4, q: "What does 'enormous' mean?", choices: ["Extremely huge", "Extremely tiny", "Extremely quiet"], answer: "Extremely huge" },
  { cat: "Words", type: "mc", diff: 4, q: "What does 'gentle' mean?", choices: ["Rough and loud", "Soft and kind", "Fast and messy"], answer: "Soft and kind" },
  { cat: "Words", type: "mc", diff: 5, q: "What does 'patient' mean?", choices: ["Able to wait calmly", "Always in a hurry", "Always loud"], answer: "Able to wait calmly" },
  { cat: "Words", type: "mc", diff: 5, q: "What does 'generous' mean?", choices: ["Keeping everything for yourself", "Happy to share with others", "Very shy"], answer: "Happy to share with others" },
  { cat: "Words", type: "open", diff: 2, q: "Can you say a word that rhymes with 'cat'?" },
  { cat: "Words", type: "open", diff: 2, q: "Can you say a word that rhymes with 'dog'?" },
  { cat: "Words", type: "open", diff: 3, q: "Can you say a word that means the same as 'happy'?" },

  // ---------- ANIMALS & NATURE ----------
  { cat: "Nature", type: "mc", diff: 1, q: "What sound does a cow make?", choices: ["Moo", "Woof", "Meow"], answer: "Moo" },
  { cat: "Nature", type: "mc", diff: 1, q: "What color is the sky on a sunny day?", choices: ["Green", "Blue", "Red"], answer: "Blue" },
  { cat: "Nature", type: "mc", diff: 1, q: "What do bees make?", choices: ["Milk", "Honey", "Bread"], answer: "Honey" },
  { cat: "Nature", type: "mc", diff: 1, q: "Where do fish live?", choices: ["In trees", "In water", "In the sky"], answer: "In water" },
  { cat: "Nature", type: "tf", diff: 1, q: "A dog says 'moo'.", answer: "False" },
  { cat: "Nature", type: "mc", diff: 2, q: "What do plants need to grow?", choices: ["Water and sunlight", "Rocks and ice", "Only darkness"], answer: "Water and sunlight" },
  { cat: "Nature", type: "mc", diff: 2, q: "Which animal is known as the 'king of the jungle'?", choices: ["Lion", "Elephant", "Zebra"], answer: "Lion" },
  { cat: "Nature", type: "mc", diff: 2, q: "What is a baby dog called?", choices: ["Kitten", "Puppy", "Cub"], answer: "Puppy" },
  { cat: "Nature", type: "mc", diff: 2, q: "What is a baby cat called?", choices: ["Kitten", "Puppy", "Calf"], answer: "Kitten" },
  { cat: "Nature", type: "mc", diff: 2, q: "What do caterpillars turn into?", choices: ["Bees", "Butterflies", "Spiders"], answer: "Butterflies" },
  { cat: "Nature", type: "mc", diff: 3, q: "What is the difference in ocean water and lake water?", choices: ["Ocean water is salty, lake water usually isn't", "Ocean water is blue, lake water is purple", "There is no difference"], answer: "Ocean water is salty, lake water usually isn't" },
  { cat: "Nature", type: "mc", diff: 3, q: "Which of these animals can fly?", choices: ["Penguin", "Eagle", "Whale"], answer: "Eagle" },
  { cat: "Nature", type: "mc", diff: 3, q: "What do we call it when rain, snow, or sunshine happens outside?", choices: ["Weather", "Traffic", "Music"], answer: "Weather" },
  { cat: "Nature", type: "mc", diff: 3, q: "What season comes after winter?", choices: ["Summer", "Spring", "Fall"], answer: "Spring" },
  { cat: "Nature", type: "mc", diff: 4, q: "Which animal is the largest in the whole world?", choices: ["Elephant", "Blue whale", "Giraffe"], answer: "Blue whale" },
  { cat: "Nature", type: "mc", diff: 4, q: "What do we call animals that only eat plants?", choices: ["Carnivores", "Herbivores", "Robots"], answer: "Herbivores" },
  { cat: "Nature", type: "mc", diff: 4, q: "How many legs does a spider have?", choices: ["6", "8", "10"], answer: "8" },
  { cat: "Nature", type: "open", diff: 2, q: "Can you name 3 animals that live on a farm?" },
  { cat: "Nature", type: "open", diff: 3, q: "Can you name 3 animals that live in the ocean?" },
  { cat: "Nature", type: "open", diff: 3, q: "What are the four seasons?" },

  // ---------- SPACE ----------
  { cat: "Space", type: "mc", diff: 2, q: "What do we call the star that gives us light and warmth?", choices: ["The Moon", "The Sun", "A comet"], answer: "The Sun" },
  { cat: "Space", type: "mc", diff: 2, q: "What do we see in the sky at night that changes shape?", choices: ["The Sun", "The Moon", "A rainbow"], answer: "The Moon" },
  { cat: "Space", type: "mc", diff: 3, q: "What planet do we live on?", choices: ["Mars", "Earth", "Jupiter"], answer: "Earth" },
  { cat: "Space", type: "mc", diff: 3, q: "What planet is closest to the sun?", choices: ["Earth", "Mercury", "Mars"], answer: "Mercury" },
  { cat: "Space", type: "mc", diff: 3, q: "Which planet is known as the 'Red Planet'?", choices: ["Mars", "Venus", "Saturn"], answer: "Mars" },
  { cat: "Space", type: "mc", diff: 4, q: "Which planet has big rings around it?", choices: ["Earth", "Saturn", "Mercury"], answer: "Saturn" },
  { cat: "Space", type: "mc", diff: 4, q: "What is the closest star to Earth (besides the sun, this one IS the sun)?", choices: ["The Sun", "The North Star", "Mars"], answer: "The Sun" },
  { cat: "Space", type: "open", diff: 3, q: "Can you name 3 planets?" },
  { cat: "Space", type: "open", diff: 4, q: "Can you name all the planets in order from the sun, starting with Mercury?" },

  // ---------- COLORS & SHAPES ----------
  { cat: "Colors", type: "mc", diff: 1, q: "What are the primary colors?", choices: ["Red, yellow, blue", "Green, purple, orange", "Black, white, gray"], answer: "Red, yellow, blue" },
  { cat: "Colors", type: "mc", diff: 1, q: "If you mix blue and yellow, what color do you get?", choices: ["Green", "Purple", "Orange"], answer: "Green" },
  { cat: "Colors", type: "mc", diff: 1, q: "If you mix red and blue, what color do you get?", choices: ["Purple", "Green", "Yellow"], answer: "Purple" },
  { cat: "Colors", type: "mc", diff: 2, q: "How many sides does a triangle have?", choices: ["2", "3", "4"], answer: "3" },
  { cat: "Colors", type: "mc", diff: 2, q: "How many sides does a square have?", choices: ["3", "4", "5"], answer: "4" },
  { cat: "Colors", type: "mc", diff: 2, q: "What shape is a ball?", choices: ["Circle", "Sphere", "Square"], answer: "Sphere" },
  { cat: "Colors", type: "mc", diff: 3, q: "If you mix red and yellow, what color do you get?", choices: ["Orange", "Green", "Pink"], answer: "Orange" },
  { cat: "Colors", type: "open", diff: 1, q: "Can you name 3 colors you can see right now?" },

  // ---------- GEOGRAPHY ----------
  { cat: "World", type: "mc", diff: 2, q: "What do we call the huge areas of land like North America or Africa?", choices: ["Continents", "Oceans", "Countries"], answer: "Continents" },
  { cat: "World", type: "mc", diff: 2, q: "What is the name of the country we live in?", choices: ["Canada", "United States", "Mexico"], answer: "United States" },
  { cat: "World", type: "mc", diff: 3, q: "What do we call a really big area of ocean?", choices: ["A lake", "A sea", "An ocean"], answer: "An ocean" },
  { cat: "World", type: "mc", diff: 3, q: "What is the tallest mountain in the world called?", choices: ["Mount Everest", "Mount Rushmore", "Mount Fuji"], answer: "Mount Everest" },
  { cat: "World", type: "mc", diff: 4, q: "How many continents are there?", choices: ["5", "7", "9"], answer: "7" },
  { cat: "World", type: "mc", diff: 4, q: "Which continent do lions, elephants, and giraffes mostly live in?", choices: ["Africa", "Europe", "Australia"], answer: "Africa" },
  { cat: "World", type: "open", diff: 4, q: "Can you name the names of the continents?" },
  { cat: "World", type: "open", diff: 2, q: "Can you name 3 countries?" },

  // ---------- BODY & SENSES ----------
  { cat: "Body", type: "mc", diff: 1, q: "What do we use to see?", choices: ["Ears", "Eyes", "Nose"], answer: "Eyes" },
  { cat: "Body", type: "mc", diff: 1, q: "What do we use to hear?", choices: ["Eyes", "Ears", "Feet"], answer: "Ears" },
  { cat: "Body", type: "mc", diff: 1, q: "What do we use to smell?", choices: ["Nose", "Elbow", "Knee"], answer: "Nose" },
  { cat: "Body", type: "mc", diff: 2, q: "How many senses do people have?", choices: ["3", "5", "8"], answer: "5" },
  { cat: "Body", type: "mc", diff: 2, q: "What organ pumps blood through your body?", choices: ["Heart", "Stomach", "Lungs"], answer: "Heart" },
  { cat: "Body", type: "open", diff: 2, q: "Can you name your five senses?" },

  // ---------- FUN / GENERAL ----------
  { cat: "Fun", type: "mc", diff: 1, q: "What do you use to brush your teeth?", choices: ["A toothbrush", "A hairbrush", "A spoon"], answer: "A toothbrush" },
  { cat: "Fun", type: "mc", diff: 1, q: "What meal do you eat in the morning?", choices: ["Breakfast", "Dinner", "Dessert"], answer: "Breakfast" },
  { cat: "Fun", type: "tf", diff: 1, q: "You should look both ways before crossing the street.", answer: "True" },
  { cat: "Fun", type: "mc", diff: 2, q: "What do you call a person who flies an airplane?", choices: ["A pilot", "A doctor", "A chef"], answer: "A pilot" },
  { cat: "Fun", type: "mc", diff: 2, q: "What do you call a person who teaches at school?", choices: ["A teacher", "A firefighter", "A farmer"], answer: "A teacher" },
  { cat: "Fun", type: "mc", diff: 2, q: "What holiday do we celebrate with a decorated tree in December?", choices: ["Halloween", "Christmas", "Thanksgiving"], answer: "Christmas" },
  { cat: "Fun", type: "mc", diff: 3, q: "What do we call the vehicle that puts out fires?", choices: ["A fire truck", "A school bus", "A taxi"], answer: "A fire truck" },
  { cat: "Fun", type: "mc", diff: 3, q: "What instrument has black and white keys?", choices: ["Piano", "Drum", "Guitar"], answer: "Piano" },
  { cat: "Fun", type: "mc", diff: 3, q: "What do bees help flowers do?", choices: ["Pollinate and grow", "Turn blue", "Fall asleep"], answer: "Pollinate and grow" },
  { cat: "Fun", type: "mc", diff: 4, q: "What do we call a story that isn't true, made up for fun?", choices: ["Fiction", "News", "A recipe"], answer: "Fiction" },
  { cat: "Fun", type: "open", diff: 1, q: "Can you name 3 fruits?" },
  { cat: "Fun", type: "open", diff: 2, q: "Can you name 3 things that are round?" },
  { cat: "Fun", type: "open", diff: 3, q: "Can you name 3 jobs people have?" },
];
