// Road-trip quiz bank. Read aloud by a parent; kid answers verbally, parent taps the match.
// difficulty: 1 (easiest, 4yo) .. 5 (5yo stretch). type: "mc" | "tf" | "open".
const QUESTIONS = [
  // ---------- MATH ----------
  { cat: "Math", type: "mc", diff: 1, q: "What is 2 + 2?", choices: ["3", "4", "5"], answer: "4" },
  { cat: "Math", type: "mc", diff: 1, q: "What is 4 + 7?", choices: ["9", "10", "11"], answer: "11" },
  { cat: "Math", type: "mc", diff: 1, q: "What is 5 + 3?", choices: ["7", "8", "9"], answer: "8" },
  { cat: "Math", type: "mc", diff: 1, q: "What is 3 + 3?", choices: ["5", "6", "7"], answer: "6" },
  { cat: "Math", type: "mc", diff: 1, q: "How many wheels does a car have?", choices: ["2", "3", "4"], answer: "4" },
  { cat: "Math", type: "mc", diff: 1, q: "How many fingers do you have on one hand?", choices: ["4", "5", "6"], answer: "5" },
  { cat: "Math", type: "tf", diff: 1, q: "5 is bigger than 3.", answer: "True" },
  { cat: "Math", type: "tf", diff: 1, q: "1 + 1 = 3", answer: "False" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 6 + 6?", choices: ["11", "12", "13"], answer: "12" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 10 - 4?", choices: ["5", "6", "7"], answer: "6" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 9 - 3?", choices: ["5", "6", "7"], answer: "6" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 8 + 5?", choices: ["12", "13", "14"], answer: "13" },
  { cat: "Math", type: "mc", diff: 2, q: "What number comes right after 19?", choices: ["18", "20", "21"], answer: "20" },
  { cat: "Math", type: "mc", diff: 2, q: "What is half of 10?", choices: ["4", "5", "6"], answer: "5" },
  { cat: "Math", type: "tf", diff: 2, q: "10 - 4 = 6", answer: "True" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 11 - 4?", choices: ["6", "7", "8"], answer: "7" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 7 + 8?", choices: ["14", "15", "16"], answer: "15" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 12 - 5?", choices: ["6", "7", "8"], answer: "7" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 3 x 2?", choices: ["5", "6", "7"], answer: "6" },
  { cat: "Math", type: "mc", diff: 3, q: "How many days are in a week?", choices: ["5", "6", "7"], answer: "7" },
  { cat: "Math", type: "mc", diff: 4, q: "What is 15 - 7?", choices: ["7", "8", "9"], answer: "8" },
  { cat: "Math", type: "mc", diff: 4, q: "What is 4 x 4?", choices: ["12", "14", "16"], answer: "16" },
  { cat: "Math", type: "mc", diff: 4, q: "How many months are in a year?", choices: ["10", "11", "12"], answer: "12" },
  { cat: "Math", type: "open", diff: 4, q: "Can you count backwards from 10 to 1?" },
  { cat: "Math", type: "mc", diff: 5, q: "What is 20 - 8?", choices: ["11", "12", "13"], answer: "12" },
  { cat: "Math", type: "mc", diff: 5, q: "What is 6 x 5?", choices: ["25", "30", "35"], answer: "30" },

  // ---------- VOCABULARY ----------
  { cat: "Words", type: "mc", diff: 1, q: "What does 'happy' mean?", choices: ["Sad", "Feeling good and glad", "Tired"], answer: "Feeling good and glad" },
  { cat: "Words", type: "mc", diff: 1, q: "What does 'big' mean?", choices: ["Small", "Large in size", "Fast"], answer: "Large in size" },
  { cat: "Words", type: "mc", diff: 1, q: "What is the opposite of 'up'?", choices: ["Down", "Left", "Fast"], answer: "Down" },
  { cat: "Words", type: "mc", diff: 1, q: "What is the opposite of 'hot'?", choices: ["Cold", "Loud", "Wet"], answer: "Cold" },
  { cat: "Words", type: "mc", diff: 2, q: "What does 'tough' mean?", choices: ["Soft and easy", "Hard or strong", "Colorful"], answer: "Hard or strong" },
  { cat: "Words", type: "mc", diff: 2, q: "What does 'tiny' mean?", choices: ["Very small", "Very loud", "Very tall"], answer: "Very small" },
  { cat: "Words", type: "mc", diff: 2, q: "What does 'exhausted' mean?", choices: ["Very excited", "Very hungry", "Very tired"], answer: "Very tired" },
  { cat: "Words", type: "mc", diff: 2, q: "What is the opposite of 'full'?", choices: ["Empty", "Heavy", "Round"], answer: "Empty" },
  { cat: "Words", type: "mc", diff: 3, q: "What does 'future' mean?", choices: ["Time that already happened", "Time that hasn't happened yet", "Right now"], answer: "Time that hasn't happened yet" },
  { cat: "Words", type: "mc", diff: 3, q: "What does 'brave' mean?", choices: ["Scared of everything", "Not afraid to do hard things", "Very sleepy"], answer: "Not afraid to do hard things" },
  { cat: "Words", type: "mc", diff: 3, q: "What does 'ancient' mean?", choices: ["Very new", "Very, very old", "Very fast"], answer: "Very, very old" },
  { cat: "Words", type: "mc", diff: 3, q: "What is the opposite of 'begin'?", choices: ["Start", "Finish", "Middle"], answer: "Finish" },
  { cat: "Words", type: "mc", diff: 4, q: "What does 'curious' mean?", choices: ["Wanting to learn or know more", "Feeling angry", "Feeling sleepy"], answer: "Wanting to learn or know more" },
  { cat: "Words", type: "mc", diff: 4, q: "What does 'enormous' mean?", choices: ["Extremely huge", "Extremely tiny", "Extremely quiet"], answer: "Extremely huge" },
  { cat: "Words", type: "mc", diff: 4, q: "What does 'gentle' mean?", choices: ["Rough and loud", "Soft and kind", "Fast and messy"], answer: "Soft and kind" },
  { cat: "Words", type: "mc", diff: 5, q: "What does 'patient' mean?", choices: ["Able to wait calmly", "Always in a hurry", "Always loud"], answer: "Able to wait calmly" },
  { cat: "Words", type: "mc", diff: 5, q: "What does 'generous' mean?", choices: ["Keeping everything for yourself", "Happy to share with others", "Very shy"], answer: "Happy to share with others" },
  { cat: "Words", type: "open", diff: 2, q: "Can you say a word that rhymes with 'cat'?" },
  { cat: "Words", type: "open", diff: 2, q: "Can you say a word that rhymes with 'dog'?" },
  { cat: "Words", type: "open", diff: 3, q: "Can you say a word that means the same as 'happy'?" },

  // ---------- ANIMALS & NATURE ----------
  { cat: "Nature", type: "mc", diff: 1, q: "What sound does a cow make?", choices: ["Moo", "Woof", "Meow"], answer: "Moo" },
  { cat: "Nature", type: "mc", diff: 1, q: "What color is the sky on a sunny day?", choices: ["Green", "Blue", "Red"], answer: "Blue" },
  { cat: "Nature", type: "mc", diff: 1, q: "What do bees make?", choices: ["Milk", "Honey", "Bread"], answer: "Honey" },
  { cat: "Nature", type: "mc", diff: 1, q: "Where do fish live?", choices: ["In trees", "In water", "In the sky"], answer: "In water" },
  { cat: "Nature", type: "tf", diff: 1, q: "A dog says 'moo'.", answer: "False" },
  { cat: "Nature", type: "mc", diff: 2, q: "What do plants need to grow?", choices: ["Water and sunlight", "Rocks and ice", "Only darkness"], answer: "Water and sunlight" },
  { cat: "Nature", type: "mc", diff: 2, q: "Which animal is known as the 'king of the jungle'?", choices: ["Lion", "Elephant", "Zebra"], answer: "Lion" },
  { cat: "Nature", type: "mc", diff: 2, q: "What is a baby dog called?", choices: ["Kitten", "Puppy", "Cub"], answer: "Puppy" },
  { cat: "Nature", type: "mc", diff: 2, q: "What is a baby cat called?", choices: ["Kitten", "Puppy", "Calf"], answer: "Kitten" },
  { cat: "Nature", type: "mc", diff: 2, q: "What do caterpillars turn into?", choices: ["Bees", "Butterflies", "Spiders"], answer: "Butterflies" },
  { cat: "Nature", type: "mc", diff: 3, q: "What is the difference in ocean water and lake water?", choices: ["Ocean water is salty, lake water usually isn't", "Ocean water is blue, lake water is purple", "There is no difference"], answer: "Ocean water is salty, lake water usually isn't" },
  { cat: "Nature", type: "mc", diff: 3, q: "Which of these animals can fly?", choices: ["Penguin", "Eagle", "Whale"], answer: "Eagle" },
  { cat: "Nature", type: "mc", diff: 3, q: "What do we call it when rain, snow, or sunshine happens outside?", choices: ["Weather", "Traffic", "Music"], answer: "Weather" },
  { cat: "Nature", type: "mc", diff: 3, q: "What season comes after winter?", choices: ["Summer", "Spring", "Fall"], answer: "Spring" },
  { cat: "Nature", type: "mc", diff: 4, q: "Which animal is the largest in the whole world?", choices: ["Elephant", "Blue whale", "Giraffe"], answer: "Blue whale" },
  { cat: "Nature", type: "mc", diff: 4, q: "What do we call animals that only eat plants?", choices: ["Carnivores", "Herbivores", "Robots"], answer: "Herbivores" },
  { cat: "Nature", type: "mc", diff: 4, q: "How many legs does a spider have?", choices: ["6", "8", "10"], answer: "8" },
  { cat: "Nature", type: "open", diff: 2, q: "Can you name 3 animals that live on a farm?" },
  { cat: "Nature", type: "open", diff: 3, q: "Can you name 3 animals that live in the ocean?" },
  { cat: "Nature", type: "open", diff: 3, q: "What are the four seasons?" },

  // ---------- SPACE ----------
  { cat: "Space", type: "mc", diff: 2, q: "What do we call the star that gives us light and warmth?", choices: ["The Moon", "The Sun", "A comet"], answer: "The Sun" },
  { cat: "Space", type: "mc", diff: 2, q: "What do we see in the sky at night that changes shape?", choices: ["The Sun", "The Moon", "A rainbow"], answer: "The Moon" },
  { cat: "Space", type: "mc", diff: 3, q: "What planet do we live on?", choices: ["Mars", "Earth", "Jupiter"], answer: "Earth" },
  { cat: "Space", type: "mc", diff: 3, q: "What planet is closest to the sun?", choices: ["Earth", "Mercury", "Mars"], answer: "Mercury" },
  { cat: "Space", type: "mc", diff: 3, q: "Which planet is known as the 'Red Planet'?", choices: ["Mars", "Venus", "Saturn"], answer: "Mars" },
  { cat: "Space", type: "mc", diff: 4, q: "Which planet has big rings around it?", choices: ["Earth", "Saturn", "Mercury"], answer: "Saturn" },
  { cat: "Space", type: "mc", diff: 4, q: "What is the closest star to Earth (besides the sun, this one IS the sun)?", choices: ["The Sun", "The North Star", "Mars"], answer: "The Sun" },
  { cat: "Space", type: "open", diff: 3, q: "Can you name 3 planets?" },
  { cat: "Space", type: "open", diff: 4, q: "Can you name all the planets in order from the sun, starting with Mercury?" },

  // ---------- COLORS & SHAPES ----------
  { cat: "Colors", type: "mc", diff: 1, q: "What are the primary colors?", choices: ["Red, yellow, blue", "Green, purple, orange", "Black, white, gray"], answer: "Red, yellow, blue" },
  { cat: "Colors", type: "mc", diff: 1, q: "If you mix blue and yellow, what color do you get?", choices: ["Green", "Purple", "Orange"], answer: "Green" },
  { cat: "Colors", type: "mc", diff: 1, q: "If you mix red and blue, what color do you get?", choices: ["Purple", "Green", "Yellow"], answer: "Purple" },
  { cat: "Colors", type: "mc", diff: 2, q: "How many sides does a triangle have?", choices: ["2", "3", "4"], answer: "3" },
  { cat: "Colors", type: "mc", diff: 2, q: "How many sides does a square have?", choices: ["3", "4", "5"], answer: "4" },
  { cat: "Colors", type: "mc", diff: 2, q: "What shape is a ball?", choices: ["Circle", "Sphere", "Square"], answer: "Sphere" },
  { cat: "Colors", type: "mc", diff: 3, q: "If you mix red and yellow, what color do you get?", choices: ["Orange", "Green", "Pink"], answer: "Orange" },
  { cat: "Colors", type: "open", diff: 1, q: "Can you name 3 colors you can see right now?" },

  // ---------- GEOGRAPHY ----------
  { cat: "World", type: "mc", diff: 2, q: "What do we call the huge areas of land like North America or Africa?", choices: ["Continents", "Oceans", "Countries"], answer: "Continents" },
  { cat: "World", type: "mc", diff: 2, q: "What is the name of the country we live in?", choices: ["Canada", "United States", "Mexico"], answer: "United States" },
  { cat: "World", type: "mc", diff: 3, q: "What do we call a really big area of ocean?", choices: ["A lake", "A sea", "An ocean"], answer: "An ocean" },
  { cat: "World", type: "mc", diff: 3, q: "What is the tallest mountain in the world called?", choices: ["Mount Everest", "Mount Rushmore", "Mount Fuji"], answer: "Mount Everest" },
  { cat: "World", type: "mc", diff: 4, q: "How many continents are there?", choices: ["5", "7", "9"], answer: "7" },
  { cat: "World", type: "mc", diff: 4, q: "Which continent do lions, elephants, and giraffes mostly live in?", choices: ["Africa", "Europe", "Australia"], answer: "Africa" },
  { cat: "World", type: "open", diff: 4, q: "Can you name the names of the continents?" },
  { cat: "World", type: "open", diff: 2, q: "Can you name 3 countries?" },

  // ---------- BODY & SENSES ----------
  { cat: "Body", type: "mc", diff: 1, q: "What do we use to see?", choices: ["Ears", "Eyes", "Nose"], answer: "Eyes" },
  { cat: "Body", type: "mc", diff: 1, q: "What do we use to hear?", choices: ["Eyes", "Ears", "Feet"], answer: "Ears" },
  { cat: "Body", type: "mc", diff: 1, q: "What do we use to smell?", choices: ["Nose", "Elbow", "Knee"], answer: "Nose" },
  { cat: "Body", type: "mc", diff: 2, q: "How many senses do people have?", choices: ["3", "5", "8"], answer: "5" },
  { cat: "Body", type: "mc", diff: 2, q: "What organ pumps blood through your body?", choices: ["Heart", "Stomach", "Lungs"], answer: "Heart" },
  { cat: "Body", type: "open", diff: 2, q: "Can you name your five senses?" },

  // ---------- FUN / GENERAL ----------
  { cat: "Fun", type: "mc", diff: 1, q: "What do you use to brush your teeth?", choices: ["A toothbrush", "A hairbrush", "A spoon"], answer: "A toothbrush" },
  { cat: "Fun", type: "mc", diff: 1, q: "What meal do you eat in the morning?", choices: ["Breakfast", "Dinner", "Dessert"], answer: "Breakfast" },
  { cat: "Fun", type: "tf", diff: 1, q: "You should look both ways before crossing the street.", answer: "True" },
  { cat: "Fun", type: "mc", diff: 2, q: "What do you call a person who flies an airplane?", choices: ["A pilot", "A doctor", "A chef"], answer: "A pilot" },
  { cat: "Fun", type: "mc", diff: 2, q: "What do you call a person who teaches at school?", choices: ["A teacher", "A firefighter", "A farmer"], answer: "A teacher" },
  { cat: "Fun", type: "mc", diff: 2, q: "What holiday do we celebrate with a decorated tree in December?", choices: ["Halloween", "Christmas", "Thanksgiving"], answer: "Christmas" },
  { cat: "Fun", type: "mc", diff: 3, q: "What do we call the vehicle that puts out fires?", choices: ["A fire truck", "A school bus", "A taxi"], answer: "A fire truck" },
  { cat: "Fun", type: "mc", diff: 3, q: "What instrument has black and white keys?", choices: ["Piano", "Drum", "Guitar"], answer: "Piano" },
  { cat: "Fun", type: "mc", diff: 3, q: "What do bees help flowers do?", choices: ["Pollinate and grow", "Turn blue", "Fall asleep"], answer: "Pollinate and grow" },
  { cat: "Fun", type: "mc", diff: 4, q: "What do we call a story that isn't true, made up for fun?", choices: ["Fiction", "News", "A recipe"], answer: "Fiction" },
  { cat: "Fun", type: "open", diff: 1, q: "Can you name 3 fruits?" },
  { cat: "Fun", type: "open", diff: 2, q: "Can you name 3 things that are round?" },
  { cat: "Fun", type: "open", diff: 3, q: "Can you name 3 jobs people have?" },

  // ---------- MORE MATH ----------
  { cat: "Math", type: "mc", diff: 1, q: "What is 1 + 3?", choices: ["3", "4", "5"], answer: "4" },
  { cat: "Math", type: "mc", diff: 1, q: "What is 5 + 5?", choices: ["9", "10", "11"], answer: "10" },
  { cat: "Math", type: "mc", diff: 1, q: "What is 2 + 6?", choices: ["7", "8", "9"], answer: "8" },
  { cat: "Math", type: "mc", diff: 1, q: "How many eyes do you have?", choices: ["1", "2", "3"], answer: "2" },
  { cat: "Math", type: "mc", diff: 1, q: "How many wheels does a bicycle have?", choices: ["1", "2", "3"], answer: "2" },
  { cat: "Math", type: "tf", diff: 1, q: "3 + 1 = 4", answer: "True" },
  { cat: "Math", type: "tf", diff: 1, q: "2 + 2 = 5", answer: "False" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 9 + 4?", choices: ["12", "13", "14"], answer: "13" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 7 - 2?", choices: ["4", "5", "6"], answer: "5" },
  { cat: "Math", type: "mc", diff: 2, q: "What is 8 - 3?", choices: ["4", "5", "6"], answer: "5" },
  { cat: "Math", type: "mc", diff: 2, q: "What number comes right before 10?", choices: ["8", "9", "11"], answer: "9" },
  { cat: "Math", type: "mc", diff: 2, q: "Which number is bigger, 14 or 41?", choices: ["14", "41", "They're the same"], answer: "41" },
  { cat: "Math", type: "tf", diff: 2, q: "9 is an odd number.", answer: "True" },
  { cat: "Math", type: "tf", diff: 2, q: "10 is an odd number.", answer: "False" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 13 - 6?", choices: ["6", "7", "8"], answer: "7" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 9 + 9?", choices: ["16", "17", "18"], answer: "18" },
  { cat: "Math", type: "mc", diff: 3, q: "What is 2 x 5?", choices: ["8", "10", "12"], answer: "10" },
  { cat: "Math", type: "mc", diff: 3, q: "How many minutes are in an hour?", choices: ["30", "60", "100"], answer: "60" },
  { cat: "Math", type: "mc", diff: 3, q: "If you have 10 candies and eat 3, how many are left?", choices: ["6", "7", "8"], answer: "7" },
  { cat: "Math", type: "mc", diff: 4, q: "What is 16 + 9?", choices: ["24", "25", "26"], answer: "25" },
  { cat: "Math", type: "mc", diff: 4, q: "What is 5 x 5?", choices: ["20", "25", "30"], answer: "25" },
  { cat: "Math", type: "mc", diff: 4, q: "What is 18 - 9?", choices: ["8", "9", "10"], answer: "9" },
  { cat: "Math", type: "mc", diff: 4, q: "How many seconds are in a minute?", choices: ["30", "60", "100"], answer: "60" },
  { cat: "Math", type: "mc", diff: 5, q: "What is 7 x 7?", choices: ["42", "49", "56"], answer: "49" },
  { cat: "Math", type: "mc", diff: 5, q: "What is 30 - 12?", choices: ["16", "17", "18"], answer: "18" },
  { cat: "Math", type: "open", diff: 1, q: "Can you count from 1 to 10?" },
  { cat: "Math", type: "open", diff: 3, q: "Can you count by 2s up to 10 (2, 4, 6...)?" },
  { cat: "Math", type: "open", diff: 4, q: "Can you count by 5s up to 50?" },

  // ---------- MORE WORDS ----------
  { cat: "Words", type: "mc", diff: 1, q: "What is the opposite of 'day'?", choices: ["Night", "Sun", "Bright"], answer: "Night" },
  { cat: "Words", type: "mc", diff: 1, q: "What is the opposite of 'fast'?", choices: ["Quick", "Slow", "Loud"], answer: "Slow" },
  { cat: "Words", type: "mc", diff: 1, q: "What is the opposite of 'happy'?", choices: ["Sad", "Silly", "Sleepy"], answer: "Sad" },
  { cat: "Words", type: "mc", diff: 1, q: "What is the opposite of 'wet'?", choices: ["Dry", "Cold", "Soft"], answer: "Dry" },
  { cat: "Words", type: "mc", diff: 2, q: "What does 'quiet' mean?", choices: ["Very loud", "Making little or no noise", "Very colorful"], answer: "Making little or no noise" },
  { cat: "Words", type: "mc", diff: 2, q: "What does 'delicious' mean?", choices: ["Tastes really good", "Smells bad", "Feels rough"], answer: "Tastes really good" },
  { cat: "Words", type: "mc", diff: 2, q: "What is the opposite of 'open'?", choices: ["Closed", "Shiny", "Loud"], answer: "Closed" },
  { cat: "Words", type: "mc", diff: 2, q: "What does 'silly' mean?", choices: ["Very serious", "Playful and funny", "Very quiet"], answer: "Playful and funny" },
  { cat: "Words", type: "mc", diff: 3, q: "What does 'furious' mean?", choices: ["Very calm", "Very angry", "Very sleepy"], answer: "Very angry" },
  { cat: "Words", type: "mc", diff: 3, q: "What does 'delighted' mean?", choices: ["Very upset", "Very pleased and happy", "Very confused"], answer: "Very pleased and happy" },
  { cat: "Words", type: "mc", diff: 3, q: "What is the opposite of 'remember'?", choices: ["Forget", "Recall", "Think"], answer: "Forget" },
  { cat: "Words", type: "mc", diff: 3, q: "What does 'invisible' mean?", choices: ["Can be seen easily", "Cannot be seen", "Very colorful"], answer: "Cannot be seen" },
  { cat: "Words", type: "mc", diff: 4, q: "What does 'fragile' mean?", choices: ["Very strong and hard to break", "Easily broken", "Very heavy"], answer: "Easily broken" },
  { cat: "Words", type: "mc", diff: 4, q: "What does 'enormous' mean, again?", choices: ["Extremely small", "Extremely large", "Extremely quiet"], answer: "Extremely large" },
  { cat: "Words", type: "mc", diff: 4, q: "What does 'clumsy' mean?", choices: ["Graceful and careful", "Awkward and likely to drop things", "Very smart"], answer: "Awkward and likely to drop things" },
  { cat: "Words", type: "mc", diff: 5, q: "What does 'reluctant' mean?", choices: ["Eager and excited", "Not willing to do something", "Very fast"], answer: "Not willing to do something" },
  { cat: "Words", type: "mc", diff: 5, q: "What does 'astonished' mean?", choices: ["Very surprised", "Very bored", "Very sleepy"], answer: "Very surprised" },
  { cat: "Words", type: "open", diff: 2, q: "Can you say a word that rhymes with 'hat'?" },
  { cat: "Words", type: "open", diff: 2, q: "Can you say a word that rhymes with 'ball'?" },
  { cat: "Words", type: "open", diff: 3, q: "Can you say a word that means the opposite of 'big'?" },
  { cat: "Words", type: "open", diff: 3, q: "Can you think of a word that starts with the same sound as your name?" },

  // ---------- MORE NATURE ----------
  { cat: "Nature", type: "mc", diff: 1, q: "What do birds use to fly?", choices: ["Wings", "Fins", "Legs"], answer: "Wings" },
  { cat: "Nature", type: "mc", diff: 1, q: "What color are most leaves in the summer?", choices: ["Green", "Purple", "Blue"], answer: "Green" },
  { cat: "Nature", type: "mc", diff: 1, q: "What does a duck say?", choices: ["Quack", "Oink", "Baa"], answer: "Quack" },
  { cat: "Nature", type: "mc", diff: 1, q: "What does a sheep say?", choices: ["Baa", "Moo", "Quack"], answer: "Baa" },
  { cat: "Nature", type: "tf", diff: 1, q: "Fish can breathe air out of water just like people.", answer: "False" },
  { cat: "Nature", type: "mc", diff: 2, q: "What do we call falling water droplets from the sky?", choices: ["Rain", "Snow", "Wind"], answer: "Rain" },
  { cat: "Nature", type: "mc", diff: 2, q: "What is frozen rain called?", choices: ["Snow", "Fog", "Steam"], answer: "Snow" },
  { cat: "Nature", type: "mc", diff: 2, q: "Which animal has a very long neck?", choices: ["Giraffe", "Pig", "Frog"], answer: "Giraffe" },
  { cat: "Nature", type: "mc", diff: 2, q: "Which animal has a trunk?", choices: ["Elephant", "Horse", "Tiger"], answer: "Elephant" },
  { cat: "Nature", type: "mc", diff: 2, q: "What do you call a baby cow?", choices: ["Calf", "Foal", "Kid"], answer: "Calf" },
  { cat: "Nature", type: "mc", diff: 3, q: "What do we call an animal that only comes out at night?", choices: ["Nocturnal", "Diurnal", "Aquatic"], answer: "Nocturnal" },
  { cat: "Nature", type: "mc", diff: 3, q: "What is it called when snow melts and turns into water?", choices: ["Melting", "Freezing", "Evaporating"], answer: "Melting" },
  { cat: "Nature", type: "mc", diff: 3, q: "Which of these lives in a hive?", choices: ["Bees", "Birds", "Fish"], answer: "Bees" },
  { cat: "Nature", type: "mc", diff: 3, q: "What do spiders spin to catch food?", choices: ["Webs", "Nests", "Shells"], answer: "Webs" },
  { cat: "Nature", type: "mc", diff: 4, q: "What is the process called when a caterpillar changes into a butterfly?", choices: ["Metamorphosis", "Migration", "Hibernation"], answer: "Metamorphosis" },
  { cat: "Nature", type: "mc", diff: 4, q: "What do we call animals that sleep through the whole winter?", choices: ["They hibernate", "They migrate", "They evaporate"], answer: "They hibernate" },
  { cat: "Nature", type: "mc", diff: 4, q: "Which of these animals lays eggs?", choices: ["Chicken", "Dog", "Cat"], answer: "Chicken" },
  { cat: "Nature", type: "mc", diff: 5, q: "What gas do plants breathe in that people breathe out?", choices: ["Oxygen", "Carbon dioxide", "Helium"], answer: "Carbon dioxide" },
  { cat: "Nature", type: "open", diff: 2, q: "Can you name 3 birds?" },
  { cat: "Nature", type: "open", diff: 3, q: "Can you name 3 things that are alive?" },
  { cat: "Nature", type: "open", diff: 3, q: "Can you name 3 kinds of weather?" },

  // ---------- MORE SPACE ----------
  { cat: "Space", type: "mc", diff: 2, q: "What do we call a person who travels to space?", choices: ["Astronaut", "Pilot", "Sailor"], answer: "Astronaut" },
  { cat: "Space", type: "mc", diff: 3, q: "What do we call a group of stars that makes a picture in the sky?", choices: ["A constellation", "A galaxy", "A comet"], answer: "A constellation" },
  { cat: "Space", type: "mc", diff: 3, q: "What is the name of the galaxy we live in?", choices: ["Milky Way", "Andromeda", "Solar System"], answer: "Milky Way" },
  { cat: "Space", type: "mc", diff: 4, q: "Which planet is the biggest in our solar system?", choices: ["Jupiter", "Earth", "Mars"], answer: "Jupiter" },
  { cat: "Space", type: "mc", diff: 4, q: "What do we call a rock from space that falls to Earth?", choices: ["A meteorite", "A satellite", "A planet"], answer: "A meteorite" },
  { cat: "Space", type: "tf", diff: 3, q: "The moon is bigger than the sun.", answer: "False" },
  { cat: "Space", type: "tf", diff: 2, q: "There is no air to breathe in space.", answer: "True" },
  { cat: "Space", type: "open", diff: 4, q: "What is the name of the vehicle astronauts fly to space?" },

  // ---------- MORE COLORS & SHAPES ----------
  { cat: "Colors", type: "mc", diff: 1, q: "What color do you get if you mix black and white?", choices: ["Gray", "Green", "Pink"], answer: "Gray" },
  { cat: "Colors", type: "mc", diff: 1, q: "What color is a banana?", choices: ["Yellow", "Purple", "Blue"], answer: "Yellow" },
  { cat: "Colors", type: "mc", diff: 1, q: "What color is grass?", choices: ["Green", "Red", "Orange"], answer: "Green" },
  { cat: "Colors", type: "mc", diff: 2, q: "How many sides does a rectangle have?", choices: ["3", "4", "5"], answer: "4" },
  { cat: "Colors", type: "mc", diff: 2, q: "How many points does a star usually have?", choices: ["4", "5", "6"], answer: "5" },
  { cat: "Colors", type: "mc", diff: 2, q: "What shape is a stop sign?", choices: ["Circle", "Octagon", "Triangle"], answer: "Octagon" },
  { cat: "Colors", type: "mc", diff: 3, q: "How many sides does a hexagon have?", choices: ["5", "6", "7"], answer: "6" },
  { cat: "Colors", type: "mc", diff: 3, q: "What color is between yellow and blue on a rainbow?", choices: ["Green", "Red", "Purple"], answer: "Green" },
  { cat: "Colors", type: "mc", diff: 3, q: "How many colors are in a rainbow?", choices: ["5", "7", "9"], answer: "7" },
  { cat: "Colors", type: "open", diff: 1, q: "Can you name 3 shapes?" },
  { cat: "Colors", type: "open", diff: 2, q: "Can you name something that is the color red?" },

  // ---------- MORE WORLD / GEOGRAPHY ----------
  { cat: "World", type: "mc", diff: 2, q: "What do we call the frozen continent where penguins live?", choices: ["Antarctica", "Australia", "Asia"], answer: "Antarctica" },
  { cat: "World", type: "mc", diff: 2, q: "What is the name of the city where the White House is?", choices: ["Washington, D.C.", "New York City", "Los Angeles"], answer: "Washington, D.C." },
  { cat: "World", type: "mc", diff: 3, q: "What do we call the imaginary line around the middle of the Earth?", choices: ["The equator", "The horizon", "The border"], answer: "The equator" },
  { cat: "World", type: "mc", diff: 3, q: "What is the largest ocean on Earth?", choices: ["Pacific Ocean", "Atlantic Ocean", "Arctic Ocean"], answer: "Pacific Ocean" },
  { cat: "World", type: "mc", diff: 3, q: "Which country is known for the Eiffel Tower?", choices: ["France", "Italy", "Spain"], answer: "France" },
  { cat: "World", type: "mc", diff: 4, q: "Which country is known for the Great Wall?", choices: ["China", "Japan", "India"], answer: "China" },
  { cat: "World", type: "mc", diff: 4, q: "Which country is shaped like a boot?", choices: ["Italy", "Greece", "Spain"], answer: "Italy" },
  { cat: "World", type: "mc", diff: 4, q: "What do we call a large group of islands?", choices: ["An archipelago", "A peninsula", "A canyon"], answer: "An archipelago" },
  { cat: "World", type: "mc", diff: 5, q: "What is the smallest continent?", choices: ["Australia", "Europe", "Africa"], answer: "Australia" },
  { cat: "World", type: "open", diff: 3, q: "Can you name 3 cities?" },
  { cat: "World", type: "open", diff: 4, q: "Can you name 3 oceans?" },

  // ---------- MORE BODY & HEALTH ----------
  { cat: "Body", type: "mc", diff: 1, q: "What do we use to taste food?", choices: ["Tongue", "Elbow", "Ear"], answer: "Tongue" },
  { cat: "Body", type: "mc", diff: 1, q: "What do we use to feel if something is soft or hard?", choices: ["Skin", "Eyes", "Nose"], answer: "Skin" },
  { cat: "Body", type: "mc", diff: 2, q: "What should you do before eating to stay healthy?", choices: ["Wash your hands", "Jump around", "Close your eyes"], answer: "Wash your hands" },
  { cat: "Body", type: "mc", diff: 2, q: "How many teeth do most adults have?", choices: ["20", "32", "40"], answer: "32" },
  { cat: "Body", type: "mc", diff: 3, q: "What part of your body helps you think?", choices: ["Brain", "Stomach", "Foot"], answer: "Brain" },
  { cat: "Body", type: "mc", diff: 3, q: "What do we call the hard parts inside your body that hold you up?", choices: ["Bones", "Muscles", "Skin"], answer: "Bones" },
  { cat: "Body", type: "tf", diff: 1, q: "You should brush your teeth every day.", answer: "True" },
  { cat: "Body", type: "open", diff: 3, q: "Can you name 3 bones or body parts?" },

  // ---------- LETTERS & READING ----------
  { cat: "Letters", type: "mc", diff: 1, q: "What letter comes after A?", choices: ["B", "C", "Z"], answer: "B" },
  { cat: "Letters", type: "mc", diff: 1, q: "What letter comes before C?", choices: ["A", "B", "D"], answer: "B" },
  { cat: "Letters", type: "mc", diff: 1, q: "What is the first letter of the alphabet?", choices: ["A", "Z", "M"], answer: "A" },
  { cat: "Letters", type: "mc", diff: 1, q: "What is the last letter of the alphabet?", choices: ["Y", "Z", "X"], answer: "Z" },
  { cat: "Letters", type: "mc", diff: 2, q: "What letter does 'apple' start with?", choices: ["A", "B", "E"], answer: "A" },
  { cat: "Letters", type: "mc", diff: 2, q: "What letter does 'dog' start with?", choices: ["D", "G", "O"], answer: "D" },
  { cat: "Letters", type: "mc", diff: 2, q: "How many letters are in the word 'cat'?", choices: ["2", "3", "4"], answer: "3" },
  { cat: "Letters", type: "mc", diff: 3, q: "How many letters are in the whole alphabet?", choices: ["24", "26", "28"], answer: "26" },
  { cat: "Letters", type: "mc", diff: 3, q: "Which of these is a vowel?", choices: ["B", "E", "T"], answer: "E" },
  { cat: "Letters", type: "mc", diff: 4, q: "How many vowels are there (a, e, i, o, u)?", choices: ["4", "5", "6"], answer: "5" },
  { cat: "Letters", type: "open", diff: 1, q: "Can you say the alphabet from A to E?" },
  { cat: "Letters", type: "open", diff: 2, q: "Can you spell your first name?" },
  { cat: "Letters", type: "open", diff: 3, q: "Can you think of a word that starts with the letter B?" },

  // ---------- TIME & CALENDAR ----------
  { cat: "Time", type: "mc", diff: 1, q: "What comes after Monday?", choices: ["Sunday", "Tuesday", "Friday"], answer: "Tuesday" },
  { cat: "Time", type: "mc", diff: 1, q: "What day comes right before Saturday?", choices: ["Friday", "Sunday", "Monday"], answer: "Friday" },
  { cat: "Time", type: "mc", diff: 2, q: "How many days are in a weekend?", choices: ["1", "2", "3"], answer: "2" },
  { cat: "Time", type: "mc", diff: 2, q: "What month comes right after January?", choices: ["February", "March", "December"], answer: "February" },
  { cat: "Time", type: "mc", diff: 2, q: "What month is Halloween in?", choices: ["October", "July", "March"], answer: "October" },
  { cat: "Time", type: "mc", diff: 3, q: "What month do we celebrate the New Year?", choices: ["January", "June", "September"], answer: "January" },
  { cat: "Time", type: "mc", diff: 3, q: "How many hours are in a day?", choices: ["12", "24", "36"], answer: "24" },
  { cat: "Time", type: "mc", diff: 4, q: "What is the first month of the year?", choices: ["January", "December", "March"], answer: "January" },
  { cat: "Time", type: "mc", diff: 4, q: "What is the last month of the year?", choices: ["November", "December", "October"], answer: "December" },
  { cat: "Time", type: "open", diff: 2, q: "Can you name the days of the week?" },
  { cat: "Time", type: "open", diff: 4, q: "Can you name the months of the year?" },

  // ---------- MUSIC ----------
  { cat: "Music", type: "mc", diff: 1, q: "What do you do with your feet to a song you like?", choices: ["Dance", "Sleep", "Read"], answer: "Dance" },
  { cat: "Music", type: "mc", diff: 2, q: "What instrument do you blow into to make music?", choices: ["Trumpet", "Drum", "Piano"], answer: "Trumpet" },
  { cat: "Music", type: "mc", diff: 2, q: "What instrument do you hit with sticks?", choices: ["Drum", "Flute", "Violin"], answer: "Drum" },
  { cat: "Music", type: "mc", diff: 3, q: "What instrument has strings you pluck or strum?", choices: ["Guitar", "Trumpet", "Drum"], answer: "Guitar" },
  { cat: "Music", type: "mc", diff: 3, q: "What do we call it when a group of people sing together?", choices: ["A choir", "A team", "A band"], answer: "A choir" },
  { cat: "Music", type: "open", diff: 1, q: "Can you sing the first line of a song you love?" },
  { cat: "Music", type: "open", diff: 2, q: "Can you name 3 instruments?" },

  // ---------- FOOD ----------
  { cat: "Food", type: "mc", diff: 1, q: "What do bees make that you can eat?", choices: ["Honey", "Jelly", "Butter"], answer: "Honey" },
  { cat: "Food", type: "mc", diff: 1, q: "What do you call a red, round fruit that keeps the doctor away?", choices: ["An apple", "A pea", "A carrot"], answer: "An apple" },
  { cat: "Food", type: "mc", diff: 1, q: "What color is a ripe banana usually?", choices: ["Yellow", "Green", "Red"], answer: "Yellow" },
  { cat: "Food", type: "mc", diff: 2, q: "What vegetable do rabbits love to eat?", choices: ["Carrots", "Broccoli", "Corn"], answer: "Carrots" },
  { cat: "Food", type: "mc", diff: 2, q: "What do we make from milk that's often orange or white and used on sandwiches?", choices: ["Cheese", "Bread", "Rice"], answer: "Cheese" },
  { cat: "Food", type: "mc", diff: 2, q: "What frozen treat do you eat in the summer that melts fast?", choices: ["Ice cream", "Soup", "Toast"], answer: "Ice cream" },
  { cat: "Food", type: "mc", diff: 3, q: "What do we call food that comes from animals like cows, chickens, and pigs?", choices: ["Meat", "Vegetables", "Grains"], answer: "Meat" },
  { cat: "Food", type: "mc", diff: 3, q: "Where does milk come from?", choices: ["Cows", "Chickens", "Pigs"], answer: "Cows" },
  { cat: "Food", type: "open", diff: 1, q: "Can you name 3 vegetables?" },
  { cat: "Food", type: "open", diff: 2, q: "Can you name your favorite food?" },
  { cat: "Food", type: "open", diff: 2, q: "Can you name 3 foods that are healthy for you?" },

  // ---------- COMMUNITY HELPERS ----------
  { cat: "Fun", type: "mc", diff: 2, q: "Who do you call for help if there is a fire?", choices: ["Firefighters", "Bakers", "Artists"], answer: "Firefighters" },
  { cat: "Fun", type: "mc", diff: 2, q: "Who helps you when you are sick?", choices: ["A doctor", "A pilot", "A farmer"], answer: "A doctor" },
  { cat: "Fun", type: "mc", diff: 2, q: "Who delivers mail and packages to your house?", choices: ["A mail carrier", "A dentist", "A chef"], answer: "A mail carrier" },
  { cat: "Fun", type: "mc", diff: 3, q: "Who helps keep our streets and neighborhoods safe?", choices: ["Police officers", "Bakers", "Painters"], answer: "Police officers" },
  { cat: "Fun", type: "mc", diff: 3, q: "Who grows the fruits and vegetables we eat?", choices: ["Farmers", "Firefighters", "Pilots"], answer: "Farmers" },
  { cat: "Fun", type: "mc", diff: 3, q: "Who takes care of your teeth?", choices: ["A dentist", "A vet", "A librarian"], answer: "A dentist" },
  { cat: "Fun", type: "mc", diff: 3, q: "Who takes care of sick animals?", choices: ["A veterinarian", "A dentist", "A pilot"], answer: "A veterinarian" },
  { cat: "Fun", type: "open", diff: 2, q: "Can you name 3 helpers in our community?" },

  // ---------- MORE FUN / GENERAL ----------
  { cat: "Fun", type: "mc", diff: 1, q: "What do you wear on your feet?", choices: ["Shoes", "Hats", "Gloves"], answer: "Shoes" },
  { cat: "Fun", type: "mc", diff: 1, q: "What do you sleep in at night?", choices: ["A bed", "A car", "A pool"], answer: "A bed" },
  { cat: "Fun", type: "tf", diff: 1, q: "You should say 'please' and 'thank you' when you ask for something.", answer: "True" },
  { cat: "Fun", type: "tf", diff: 2, q: "It's a good idea to share your toys with friends.", answer: "True" },
  { cat: "Fun", type: "mc", diff: 2, q: "What do you call the place where you borrow books?", choices: ["A library", "A hospital", "A garage"], answer: "A library" },
  { cat: "Fun", type: "mc", diff: 2, q: "What do you use an umbrella for?", choices: ["Staying dry in the rain", "Cutting paper", "Cooking food"], answer: "Staying dry in the rain" },
  { cat: "Fun", type: "mc", diff: 3, q: "What do we call the vehicle that takes sick people to the hospital fast?", choices: ["An ambulance", "A school bus", "A taxi"], answer: "An ambulance" },
  { cat: "Fun", type: "mc", diff: 3, q: "What do we call a place where you go to see animals?", choices: ["A zoo", "A library", "A bakery"], answer: "A zoo" },
  { cat: "Fun", type: "mc", diff: 3, q: "What do you call the vehicle that flies in the sky and carries lots of people?", choices: ["An airplane", "A submarine", "A train"], answer: "An airplane" },
  { cat: "Fun", type: "mc", diff: 4, q: "What do we call a vehicle that travels underwater?", choices: ["A submarine", "A helicopter", "A tractor"], answer: "A submarine" },
  { cat: "Fun", type: "mc", diff: 4, q: "What do you call a big vehicle that travels on train tracks?", choices: ["A train", "A boat", "A scooter"], answer: "A train" },
  { cat: "Fun", type: "open", diff: 1, q: "Can you name 3 vehicles?" },
  { cat: "Fun", type: "open", diff: 2, q: "Can you name 3 things you might see at a playground?" },
  { cat: "Fun", type: "open", diff: 3, q: "Can you name 3 things that are found in a kitchen?" },
];
