// Auto-generated by calc_nutrition.py — do not edit by hand
// Re-run after updating recipes.js or ingredient_matches.json

window.NUTRITION_DATA = {
  "pancakes": {
    "servings": 2,
    "per_serving": {
      "calories": 1052.7,
      "protein": 27.4,
      "carbs": 181.0,
      "fat": 22.4,
      "fiber": 6.7,
      "sugar": 30.3,
      "sodium": 388.4
    },
    "total": {
      "calories": 2105.5,
      "protein": 54.7,
      "carbs": 361.9,
      "fat": 44.8,
      "fiber": 13.4,
      "sugar": 60.7,
      "sodium": 776.8
    },
    "mapped_ingredients": 6,
    "skipped_ingredients": [
      "baking powder"
    ],
    "coverage_note": "6/7 ingredients mapped"
  },
  "waffles": {
    "servings": 4,
    "per_serving": {
      "calories": 837.7,
      "protein": 19.9,
      "carbs": 120.7,
      "fat": 29.6,
      "fiber": 4.5,
      "sugar": 20.1,
      "sodium": 384.9
    },
    "total": {
      "calories": 3351.0,
      "protein": 79.4,
      "carbs": 482.8,
      "fat": 118.2,
      "fiber": 18.0,
      "sugar": 80.4,
      "sodium": 1539.4
    },
    "mapped_ingredients": 6,
    "skipped_ingredients": [
      "baking powder",
      "vanilla extract"
    ],
    "coverage_note": "6/8 ingredients mapped"
  },
  "omelette": {
    "servings": 4,
    "per_serving": {
      "calories": 191.7,
      "protein": 7.9,
      "carbs": 5.9,
      "fat": 15.7,
      "fiber": 0.1,
      "sugar": 1.9,
      "sodium": 103.6
    },
    "total": {
      "calories": 766.7,
      "protein": 31.5,
      "carbs": 23.7,
      "fat": 62.8,
      "fiber": 0.4,
      "sugar": 7.8,
      "sodium": 414.5
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "red pepper (0g \u2014 unit: 'to taste')",
      "salt (0g \u2014 unit: 'to taste')",
      "onion powder (0g \u2014 unit: 'to taste')",
      "garlic powder (0g \u2014 unit: 'to taste')",
      "cheddar cheese (0g \u2014 unit: 'preferred')",
      "hot sauce (0g \u2014 unit: 'optional')",
      "fresh cracked pepper"
    ],
    "coverage_note": "3/10 ingredients mapped"
  },
  "french-toast": {
    "servings": 4,
    "per_serving": {
      "calories": 119.8,
      "protein": 4.6,
      "carbs": 9.4,
      "fat": 7.1,
      "fiber": 1.0,
      "sugar": 5.7,
      "sodium": 111.6
    },
    "total": {
      "calories": 479.3,
      "protein": 18.4,
      "carbs": 37.7,
      "fat": 28.4,
      "fiber": 4.1,
      "sugar": 22.7,
      "sodium": 446.6
    },
    "mapped_ingredients": 5,
    "skipped_ingredients": [
      "thick-cut bread (brioche or challah)",
      "vanilla extract"
    ],
    "coverage_note": "5/7 ingredients mapped"
  },
  "yogurt-parfait": {
    "servings": 4,
    "per_serving": {
      "calories": 162.8,
      "protein": 7.5,
      "carbs": 19.2,
      "fat": 6.4,
      "fiber": 1.6,
      "sugar": 6.0,
      "sodium": 24.3
    },
    "total": {
      "calories": 651.2,
      "protein": 30.2,
      "carbs": 76.9,
      "fat": 25.4,
      "fiber": 6.4,
      "sugar": 24.2,
      "sodium": 97.2
    },
    "mapped_ingredients": 5,
    "skipped_ingredients": [],
    "coverage_note": "5/5 ingredients mapped"
  },
  "buttered-noodles": {
    "servings": 4,
    "per_serving": {
      "calories": 265.2,
      "protein": 8.9,
      "carbs": 45.3,
      "fat": 5.0,
      "fiber": 1.9,
      "sugar": 1.6,
      "sodium": 95.4
    },
    "total": {
      "calories": 1060.9,
      "protein": 35.7,
      "carbs": 181.3,
      "fat": 20.0,
      "fiber": 7.7,
      "sugar": 6.4,
      "sodium": 381.4
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "salt (0g \u2014 unit: 'for water')"
    ],
    "coverage_note": "3/4 ingredients mapped"
  },
  "bean-tacos": {
    "servings": 4,
    "per_serving": {
      "calories": 306.7,
      "protein": 33.8,
      "carbs": 13.3,
      "fat": 12.7,
      "fiber": 1.3,
      "sugar": 5.4,
      "sodium": 890.0
    },
    "total": {
      "calories": 1226.8,
      "protein": 135.4,
      "carbs": 53.4,
      "fat": 50.8,
      "fiber": 5.0,
      "sugar": 21.4,
      "sodium": 3560.2
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "taco seasoning",
      "small flour tortillas (0g \u2014 unit: '')",
      "guacamole"
    ],
    "coverage_note": "3/6 ingredients mapped"
  },
  "scrambled-soldiers": {
    "servings": 4,
    "per_serving": {
      "calories": 137.5,
      "protein": 5.4,
      "carbs": 1.7,
      "fat": 12.2,
      "fiber": 0.0,
      "sugar": 1.2,
      "sodium": 123.4
    },
    "total": {
      "calories": 549.9,
      "protein": 21.5,
      "carbs": 6.7,
      "fat": 48.6,
      "fiber": 0.2,
      "sugar": 4.7,
      "sodium": 493.6
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "bread (0g \u2014 unit: 'slices')"
    ],
    "coverage_note": "3/4 ingredients mapped"
  },
  "breakfast-quesadilla": {
    "servings": 4,
    "per_serving": {
      "calories": 112.1,
      "protein": 6.6,
      "carbs": 0.6,
      "fat": 9.2,
      "fiber": 0.0,
      "sugar": 0.5,
      "sodium": 149.1
    },
    "total": {
      "calories": 448.2,
      "protein": 26.3,
      "carbs": 2.4,
      "fat": 36.8,
      "fiber": 0.0,
      "sugar": 1.9,
      "sodium": 596.5
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "tortilla (0g \u2014 unit: '')"
    ],
    "coverage_note": "3/4 ingredients mapped"
  },
  "spaghetti-carbonara": {
    "servings": 4,
    "per_serving": {
      "calories": 474.1,
      "protein": 14.7,
      "carbs": 84.0,
      "fat": 9.3,
      "fiber": 7.1,
      "sugar": 0.6,
      "sodium": 1565.9
    },
    "total": {
      "calories": 1896.5,
      "protein": 58.9,
      "carbs": 336.2,
      "fat": 37.2,
      "fiber": 28.6,
      "sugar": 2.5,
      "sodium": 6263.5
    },
    "mapped_ingredients": 2,
    "skipped_ingredients": [
      "guanciale or pancetta",
      "pecorino romano",
      "fresh cracked pepper"
    ],
    "coverage_note": "2/5 ingredients mapped"
  },
  "chicken-stir-fry": {
    "servings": 4,
    "per_serving": {
      "calories": 85.0,
      "protein": 9.2,
      "carbs": 12.3,
      "fat": 0.8,
      "fiber": 3.2,
      "sugar": 2.1,
      "sodium": 40.3
    },
    "total": {
      "calories": 339.9,
      "protein": 36.8,
      "carbs": 49.3,
      "fat": 3.4,
      "fiber": 12.8,
      "sugar": 8.4,
      "sodium": 161.2
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "chicken breast (0g \u2014 unit: 'sliced')",
      "garlic (0g \u2014 unit: 'cloves')"
    ],
    "coverage_note": "3/5 ingredients mapped"
  },
  "sheet-pan-salmon": {
    "servings": 4,
    "per_serving": {
      "calories": 69.7,
      "protein": 1.9,
      "carbs": 7.4,
      "fat": 3.9,
      "fiber": 0.0,
      "sugar": 6.2,
      "sodium": 0.4
    },
    "total": {
      "calories": 278.7,
      "protein": 7.8,
      "carbs": 29.7,
      "fat": 15.5,
      "fiber": 0.1,
      "sugar": 24.6,
      "sodium": 1.5
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "salmon fillets (0g \u2014 unit: '')",
      "asparagus (0g \u2014 unit: 'bunch')"
    ],
    "coverage_note": "3/5 ingredients mapped"
  },
  "rainbow-bento": {
    "servings": 4,
    "per_serving": {
      "calories": 0.0,
      "protein": 0.0,
      "carbs": 0.0,
      "fat": 0.0,
      "fiber": 0.0,
      "sugar": 0.0,
      "sodium": 0.0
    },
    "total": {
      "calories": 0,
      "protein": 0,
      "carbs": 0,
      "fat": 0,
      "fiber": 0,
      "sugar": 0,
      "sodium": 0
    },
    "mapped_ingredients": 0,
    "skipped_ingredients": [
      "mozz string cheese",
      "strawberries (0g \u2014 unit: 'sliced')",
      "grapes",
      "pretzels"
    ],
    "coverage_note": "0/4 ingredients mapped"
  },
  "snack-pack-lunch": {
    "servings": 4,
    "per_serving": {
      "calories": 0.0,
      "protein": 0.0,
      "carbs": 0.0,
      "fat": 0.0,
      "fiber": 0.0,
      "sugar": 0.0,
      "sodium": 0.0
    },
    "total": {
      "calories": 0,
      "protein": 0,
      "carbs": 0,
      "fat": 0,
      "fiber": 0,
      "sugar": 0,
      "sodium": 0
    },
    "mapped_ingredients": 0,
    "skipped_ingredients": [
      "popcorn",
      "cheese puffs",
      "greek yogurt (0g \u2014 unit: 'pot')",
      "pretzels"
    ],
    "coverage_note": "0/4 ingredients mapped"
  },
  "cold-pasta-salad": {
    "servings": 4,
    "per_serving": {
      "calories": 122.2,
      "protein": 4.6,
      "carbs": 19.4,
      "fat": 3.2,
      "fiber": 2.8,
      "sugar": 0.5,
      "sodium": 71.2
    },
    "total": {
      "calories": 488.8,
      "protein": 18.2,
      "carbs": 77.7,
      "fat": 12.8,
      "fiber": 11.0,
      "sugar": 2.1,
      "sodium": 285.0
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "cucumber sticks"
    ],
    "coverage_note": "3/4 ingredients mapped"
  },
  "lemon-cream-pasta": {
    "servings": 4,
    "per_serving": {
      "calories": 785.6,
      "protein": 27.0,
      "carbs": 99.2,
      "fat": 31.8,
      "fiber": 6.6,
      "sugar": 4.7,
      "sodium": 580.8
    },
    "total": {
      "calories": 3142.3,
      "protein": 108.2,
      "carbs": 396.9,
      "fat": 127.3,
      "fiber": 26.4,
      "sugar": 18.7,
      "sodium": 2323.3
    },
    "mapped_ingredients": 7,
    "skipped_ingredients": [
      "garlic (0g \u2014 unit: 'cloves (optional)')",
      "salt (0g \u2014 unit: 'to taste')"
    ],
    "coverage_note": "7/9 ingredients mapped"
  },
  "crispy-cast-iron-cod": {
    "servings": 4,
    "per_serving": {
      "calories": 207.2,
      "protein": 2.2,
      "carbs": 14.4,
      "fat": 16.2,
      "fiber": 0.9,
      "sugar": 0.7,
      "sodium": 100.2
    },
    "total": {
      "calories": 828.7,
      "protein": 8.6,
      "carbs": 57.6,
      "fat": 64.9,
      "fiber": 3.7,
      "sugar": 2.8,
      "sodium": 400.9
    },
    "mapped_ingredients": 7,
    "skipped_ingredients": [
      "cod fillets (0g \u2014 unit: '(approx 6oz each)')",
      "garlic (0g \u2014 unit: 'cloves, minced')",
      "salt & black pepper"
    ],
    "coverage_note": "7/10 ingredients mapped"
  },
  "wwf-quinoa": {
    "servings": 4,
    "per_serving": {
      "calories": 567.9,
      "protein": 37.0,
      "carbs": 58.9,
      "fat": 22.4,
      "fiber": 4.8,
      "sugar": 2.7,
      "sodium": 301.3
    },
    "total": {
      "calories": 2271.8,
      "protein": 148.0,
      "carbs": 235.6,
      "fat": 89.5,
      "fiber": 19.2,
      "sugar": 11.0,
      "sodium": 1205.0
    },
    "mapped_ingredients": 9,
    "skipped_ingredients": [
      "artichoke hearts",
      "salt (0g \u2014 unit: 'to taste')"
    ],
    "coverage_note": "9/11 ingredients mapped"
  },
  "no-cilantro-street-corn-quinoa": {
    "servings": 4,
    "per_serving": {
      "calories": 465.8,
      "protein": 19.3,
      "carbs": 72.9,
      "fat": 14.0,
      "fiber": 8.1,
      "sugar": 9.1,
      "sodium": 306.7
    },
    "total": {
      "calories": 1863.0,
      "protein": 77.1,
      "carbs": 291.5,
      "fat": 55.9,
      "fiber": 32.5,
      "sugar": 36.5,
      "sodium": 1226.7
    },
    "mapped_ingredients": 9,
    "skipped_ingredients": [
      "black beans (0g \u2014 unit: 'can (rinsed)')",
      "red bell pepper (0g \u2014 unit: 'diced')",
      "scallions (0g \u2014 unit: 'sliced')",
      "salt & pepper"
    ],
    "coverage_note": "9/13 ingredients mapped"
  },
  "smashed-parmesan-sprouts": {
    "servings": 4,
    "per_serving": {
      "calories": 251.8,
      "protein": 13.3,
      "carbs": 16.0,
      "fat": 16.5,
      "fiber": 5.5,
      "sugar": 0.1,
      "sodium": 571.1
    },
    "total": {
      "calories": 1007.0,
      "protein": 53.0,
      "carbs": 63.9,
      "fat": 66.0,
      "fiber": 22.2,
      "sugar": 0.2,
      "sodium": 2284.6
    },
    "mapped_ingredients": 4,
    "skipped_ingredients": [
      "salt & black pepper"
    ],
    "coverage_note": "4/5 ingredients mapped"
  },
  "cast-iron-brussels-sprouts": {
    "servings": 4,
    "per_serving": {
      "calories": 66.7,
      "protein": 4.5,
      "carbs": 14.0,
      "fat": 0.6,
      "fiber": 5.4,
      "sugar": 3.1,
      "sodium": 29.3
    },
    "total": {
      "calories": 266.9,
      "protein": 18.1,
      "carbs": 56.0,
      "fat": 2.6,
      "fiber": 21.7,
      "sugar": 12.3,
      "sodium": 117.4
    },
    "mapped_ingredients": 2,
    "skipped_ingredients": [
      "bacon or pancetta (0g \u2014 unit: 'slices, chopped')",
      "balsamic glaze",
      "lemon juice",
      "salt & black pepper"
    ],
    "coverage_note": "2/6 ingredients mapped"
  },
  "cacio-e-pepe": {
    "servings": 4,
    "per_serving": {
      "calories": 404.0,
      "protein": 9.9,
      "carbs": 85.7,
      "fat": 3.4,
      "fiber": 8.1,
      "sugar": 0.0,
      "sodium": 1496.5
    },
    "total": {
      "calories": 1616.2,
      "protein": 39.7,
      "carbs": 342.7,
      "fat": 13.4,
      "fiber": 32.4,
      "sugar": 0.1,
      "sodium": 5986.0
    },
    "mapped_ingredients": 2,
    "skipped_ingredients": [
      "pecorino romano",
      "salt (0g \u2014 unit: 'for pasta water')"
    ],
    "coverage_note": "2/4 ingredients mapped"
  },
  "pasta-amatriciana": {
    "servings": 4,
    "per_serving": {
      "calories": 396.6,
      "protein": 9.6,
      "carbs": 83.6,
      "fat": 3.3,
      "fiber": 7.3,
      "sugar": 0.1,
      "sodium": 1495.9
    },
    "total": {
      "calories": 1586.5,
      "protein": 38.4,
      "carbs": 334.5,
      "fat": 13.4,
      "fiber": 29.3,
      "sugar": 0.3,
      "sodium": 5983.7
    },
    "mapped_ingredients": 2,
    "skipped_ingredients": [
      "guanciale or pancetta",
      "peeled plum tomatoes (0g \u2014 unit: 'can (14oz), hand-crushed')",
      "pecorino romano",
      "white wine",
      "salt & pepper"
    ],
    "coverage_note": "2/7 ingredients mapped"
  },
  "pasta-gricia": {
    "servings": 4,
    "per_serving": {
      "calories": 394.6,
      "protein": 9.5,
      "carbs": 83.3,
      "fat": 3.2,
      "fiber": 7.1,
      "sugar": 0.0,
      "sodium": 1495.7
    },
    "total": {
      "calories": 1578.5,
      "protein": 38.1,
      "carbs": 333.1,
      "fat": 12.9,
      "fiber": 28.6,
      "sugar": 0,
      "sodium": 5983.0
    },
    "mapped_ingredients": 1,
    "skipped_ingredients": [
      "guanciale",
      "pecorino romano",
      "fresh cracked black pepper",
      "salt (0g \u2014 unit: 'for pasta water')"
    ],
    "coverage_note": "1/5 ingredients mapped"
  },
  "kid-lunch-classic": {
    "servings": 4,
    "per_serving": {
      "calories": 9.8,
      "protein": 0.2,
      "carbs": 2.4,
      "fat": 0.1,
      "fiber": 0.0,
      "sugar": 0.0,
      "sodium": 0.0
    },
    "total": {
      "calories": 39.2,
      "protein": 0.8,
      "carbs": 9.6,
      "fat": 0.3,
      "fiber": 0,
      "sugar": 0,
      "sodium": 0.0
    },
    "mapped_ingredients": 1,
    "skipped_ingredients": [
      "greek yogurt cup",
      "string cheese",
      "Z Bar",
      "applesauce pouch"
    ],
    "coverage_note": "1/5 ingredients mapped"
  },
  "kid-lunch-protein": {
    "servings": 4,
    "per_serving": {
      "calories": 17.2,
      "protein": 0.2,
      "carbs": 4.4,
      "fat": 0.1,
      "fiber": 0.0,
      "sugar": 0.0,
      "sodium": 0.0
    },
    "total": {
      "calories": 68.9,
      "protein": 0.8,
      "carbs": 17.5,
      "fat": 0.4,
      "fiber": 0,
      "sugar": 0,
      "sodium": 0.0
    },
    "mapped_ingredients": 1,
    "skipped_ingredients": [
      "greek yogurt cup",
      "turkey deli meat (0g \u2014 unit: 'slices (rolled up)')",
      "Z Bar",
      "applesauce pouch"
    ],
    "coverage_note": "1/5 ingredients mapped"
  },
  "kid-lunch-crunch": {
    "servings": 4,
    "per_serving": {
      "calories": 9.8,
      "protein": 0.2,
      "carbs": 2.4,
      "fat": 0.1,
      "fiber": 0.0,
      "sugar": 0.0,
      "sodium": 0.0
    },
    "total": {
      "calories": 39.2,
      "protein": 0.8,
      "carbs": 9.6,
      "fat": 0.3,
      "fiber": 0,
      "sugar": 0,
      "sodium": 0.0
    },
    "mapped_ingredients": 1,
    "skipped_ingredients": [
      "greek yogurt cup",
      "string cheese",
      "Z Bar",
      "applesauce pouch",
      "pretzels or crackers"
    ],
    "coverage_note": "1/6 ingredients mapped"
  },
  "kid-lunch-dairy-swap": {
    "servings": 4,
    "per_serving": {
      "calories": 9.8,
      "protein": 0.2,
      "carbs": 2.4,
      "fat": 0.1,
      "fiber": 0.0,
      "sugar": 0.0,
      "sodium": 0.0
    },
    "total": {
      "calories": 39.2,
      "protein": 0.8,
      "carbs": 9.6,
      "fat": 0.3,
      "fiber": 0,
      "sugar": 0,
      "sodium": 0.0
    },
    "mapped_ingredients": 1,
    "skipped_ingredients": [
      "cottage cheese cup",
      "string cheese",
      "Z Bar",
      "applesauce pouch"
    ],
    "coverage_note": "1/5 ingredients mapped"
  },
  "kid-lunch-sandwich": {
    "servings": 4,
    "per_serving": {
      "calories": 31.9,
      "protein": 1.1,
      "carbs": 3.2,
      "fat": 1.9,
      "fiber": 0.2,
      "sugar": 0.0,
      "sodium": 8.3
    },
    "total": {
      "calories": 127.6,
      "protein": 4.4,
      "carbs": 13.0,
      "fat": 7.7,
      "fiber": 0.9,
      "sugar": 0,
      "sodium": 33.1
    },
    "mapped_ingredients": 2,
    "skipped_ingredients": [
      "bread (0g \u2014 unit: 'slice')",
      "string cheese",
      "applesauce pouch"
    ],
    "coverage_note": "2/5 ingredients mapped"
  },
  "moms-rolled-biscuits": {
    "servings": 4,
    "per_serving": {
      "calories": 650.5,
      "protein": 14.2,
      "carbs": 102.6,
      "fat": 19.4,
      "fiber": 3.8,
      "sugar": 7.1,
      "sodium": 207.8
    },
    "total": {
      "calories": 2602.0,
      "protein": 57.0,
      "carbs": 410.2,
      "fat": 77.7,
      "fiber": 15.2,
      "sugar": 28.3,
      "sodium": 831.4
    },
    "mapped_ingredients": 4,
    "skipped_ingredients": [
      "baking powder",
      "lemon juice (optional)"
    ],
    "coverage_note": "4/6 ingredients mapped"
  },
  "cream-drop-biscuits": {
    "servings": 4,
    "per_serving": {
      "calories": 690.7,
      "protein": 14.0,
      "carbs": 94.8,
      "fat": 27.9,
      "fiber": 3.3,
      "sugar": 0.3,
      "sodium": 17.9
    },
    "total": {
      "calories": 2762.8,
      "protein": 55.9,
      "carbs": 379.2,
      "fat": 111.4,
      "fiber": 13.1,
      "sugar": 1.3,
      "sodium": 71.5
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "baking powder"
    ],
    "coverage_note": "3/4 ingredients mapped"
  },
  "golden-egg-biscuits": {
    "servings": 4,
    "per_serving": {
      "calories": 760.0,
      "protein": 16.9,
      "carbs": 110.6,
      "fat": 26.9,
      "fiber": 4.0,
      "sugar": 4.9,
      "sodium": 253.9
    },
    "total": {
      "calories": 3039.8,
      "protein": 67.6,
      "carbs": 442.3,
      "fat": 107.4,
      "fiber": 16.1,
      "sugar": 19.7,
      "sodium": 1015.5
    },
    "mapped_ingredients": 5,
    "skipped_ingredients": [
      "baking powder"
    ],
    "coverage_note": "5/6 ingredients mapped"
  },
  "iceberg-chopped-salad": {
    "servings": 4,
    "per_serving": {
      "calories": 81.9,
      "protein": 0.8,
      "carbs": 4.6,
      "fat": 7.7,
      "fiber": 0.1,
      "sugar": 0.5,
      "sodium": 0.2
    },
    "total": {
      "calories": 327.6,
      "protein": 3.0,
      "carbs": 18.3,
      "fat": 30.7,
      "fiber": 0.3,
      "sugar": 2.1,
      "sodium": 0.8
    },
    "mapped_ingredients": 2,
    "skipped_ingredients": [
      "\u2014 FOR THE SALAD \u2014",
      "iceberg lettuce (0g \u2014 unit: 'chopped')",
      "purple onion (0g \u2014 unit: 'thinly sliced')",
      "cucumber (0g \u2014 unit: 'sliced or diced')",
      "corn (0g \u2014 unit: 'fresh or cooked kernels')",
      "parmesan (0g \u2014 unit: 'freshly grated or shaved')",
      "salt, pepper & oregano",
      "\u2014 FOR THE DRESSING \u2014",
      "garlic (0g \u2014 unit: 'clove, minced')",
      "olive oil (0g \u2014 unit: 'good quality, to taste')",
      "white vinegar (0g \u2014 unit: 'splash')",
      "salt & pepper",
      "oregano (0g \u2014 unit: 'light sprinkle')",
      "\u2014 BALLARD SPECIAL CROUTONS \u2014",
      "rustic bread (0g \u2014 unit: 'cubed')",
      "olive oil (0g \u2014 unit: 'for skillet')",
      "salt (0g \u2014 unit: 'pinch')"
    ],
    "coverage_note": "2/19 ingredients mapped"
  },
  "cheeseburger-pasta": {
    "servings": 4,
    "per_serving": {
      "calories": 558.0,
      "protein": 35.4,
      "carbs": 75.4,
      "fat": 11.5,
      "fiber": 3.1,
      "sugar": 6.8,
      "sodium": 172.1
    },
    "total": {
      "calories": 2231.9,
      "protein": 141.5,
      "carbs": 301.5,
      "fat": 46.0,
      "fiber": 12.4,
      "sugar": 27.1,
      "sodium": 688.3
    },
    "mapped_ingredients": 5,
    "skipped_ingredients": [
      "shredded mild cheddar (0g \u2014 unit: 'cups')"
    ],
    "coverage_note": "5/6 ingredients mapped"
  },
  "chicken-parm-sliders": {
    "servings": 4,
    "per_serving": {
      "calories": 334.5,
      "protein": 23.6,
      "carbs": 24.4,
      "fat": 15.3,
      "fiber": 0.8,
      "sugar": 0.1,
      "sodium": 326.4
    },
    "total": {
      "calories": 1338.1,
      "protein": 94.4,
      "carbs": 97.7,
      "fat": 61.0,
      "fiber": 3.2,
      "sugar": 0.5,
      "sodium": 1305.5
    },
    "mapped_ingredients": 4,
    "skipped_ingredients": [
      "salt (0g \u2014 unit: 'to taste')",
      "breadcrumbs",
      "olive oil (0g \u2014 unit: 'for cooking')",
      "marinara sauce (0g \u2014 unit: 'cup')",
      "brioche or slider buns"
    ],
    "coverage_note": "4/9 ingredients mapped"
  },
  "simple-meatballs": {
    "servings": 4,
    "per_serving": {
      "calories": 214.5,
      "protein": 25.0,
      "carbs": 6.7,
      "fat": 9.1,
      "fiber": 0.1,
      "sugar": 1.2,
      "sodium": 106.1
    },
    "total": {
      "calories": 858.0,
      "protein": 100.0,
      "carbs": 26.6,
      "fat": 36.3,
      "fiber": 0.5,
      "sugar": 4.7,
      "sodium": 424.5
    },
    "mapped_ingredients": 5,
    "skipped_ingredients": [
      "breadcrumbs"
    ],
    "coverage_note": "5/6 ingredients mapped"
  },
  "mild-chicken-quesadillas": {
    "servings": 4,
    "per_serving": {
      "calories": 590.1,
      "protein": 49.5,
      "carbs": 36.2,
      "fat": 26.3,
      "fiber": 1.8,
      "sugar": 8.8,
      "sodium": 2156.9
    },
    "total": {
      "calories": 2360.4,
      "protein": 198.0,
      "carbs": 144.8,
      "fat": 105.3,
      "fiber": 7.0,
      "sugar": 35.3,
      "sodium": 8627.6
    },
    "mapped_ingredients": 3,
    "skipped_ingredients": [
      "butter or olive oil (0g \u2014 unit: 'for pan')"
    ],
    "coverage_note": "3/4 ingredients mapped"
  },
  "upgraded-buttered-pasta": {
    "servings": 4,
    "per_serving": {
      "calories": 342.9,
      "protein": 13.6,
      "carbs": 31.2,
      "fat": 18.8,
      "fiber": 3.9,
      "sugar": 0.8,
      "sodium": 618.6
    },
    "total": {
      "calories": 1371.5,
      "protein": 54.4,
      "carbs": 124.7,
      "fat": 75.0,
      "fiber": 15.7,
      "sugar": 3.0,
      "sodium": 2474.6
    },
    "mapped_ingredients": 4,
    "skipped_ingredients": [],
    "coverage_note": "4/4 ingredients mapped"
  },
  "akils-morning-oatmeal": {
    "servings": 4,
    "per_serving": {
      "calories": 173.8,
      "protein": 5.8,
      "carbs": 33.0,
      "fat": 2.0,
      "fiber": 0.6,
      "sugar": 6.0,
      "sodium": 55.8
    },
    "total": {
      "calories": 695.3,
      "protein": 23.4,
      "carbs": 132.0,
      "fat": 8.0,
      "fiber": 2.4,
      "sugar": 24.1,
      "sodium": 223.1
    },
    "mapped_ingredients": 5,
    "skipped_ingredients": [
      "agave syrup",
      "vanilla extract",
      "ground cinnamon (0g \u2014 unit: 'pinch')",
      "salt (0g \u2014 unit: 'pinch')",
      "fresh fruit, sliced (0g \u2014 unit: 'for serving')"
    ],
    "coverage_note": "5/10 ingredients mapped"
  },
  "lunch-box-noodle-bowl": {
    "servings": 8,
    "per_serving": {
      "calories": 400.2,
      "protein": 33.5,
      "carbs": 26.0,
      "fat": 21.1,
      "fiber": 10.9,
      "sugar": 4.0,
      "sodium": 151.4
    },
    "total": {
      "calories": 3201.6,
      "protein": 268.1,
      "carbs": 208.0,
      "fat": 168.8,
      "fiber": 87.0,
      "sugar": 31.8,
      "sodium": 1211.0
    },
    "mapped_ingredients": 7,
    "skipped_ingredients": [
      "noodles (sweet potato, soba, or udon)",
      "extra-virgin olive oil (0g \u2014 unit: '2 tsp')",
      "toasted sesame oil (noodles)",
      "rice bran oil (or neutral oil)",
      "firm tofu, cut into 8 slices",
      "soy sauce (tofu) (0g \u2014 unit: '2 tsp')",
      "oyster sauce or hoisin",
      "fresh lemon juice",
      "toasted sesame oil (tofu)",
      "Chinese broccoli (or similar greens) (0g \u2014 unit: 'bunches')",
      "nori sheets"
    ],
    "coverage_note": "7/18 ingredients mapped"
  }
};
