const chronosSeedDataRaw = [
    {
        "id": 1,
        "event_name": "Big Bang",
        "category": "Cosmology",
        "subcategory": "Universe Formation",
        "era": "Cosmological Era",
        "region": "Universe",
        "location": "Universe",
        "start_date": -13800000000,
        "end_date": -13800000000,
        "year_numeric": -13800000000,
        "description": "Origin of the universe from rapid expansion",
        "significance": "Beginning of space, time, matter",
        "level": 2
    },
    {
        "id": 2,
        "event_name": "Formation of Earth",
        "category": "Geological Formation",
        "subcategory": "Planet Formation",
        "era": "Geological Era",
        "region": "Solar System",
        "location": "Earth",
        "start_date": -4540000000,
        "end_date": -4540000000,
        "year_numeric": -4540000000,
        "description": "Earth forms from solar nebula",
        "significance": "Beginning of Earth's planetary history",
        "level": 2
    },
    {
        "id": 3,
        "event_name": "First Life on Earth",
        "category": "Evolutionary Biology",
        "subcategory": "Microbial Life",
        "era": "Geological Era",
        "region": "Earth",
        "location": "Earth",
        "start_date": -3500000000,
        "end_date": -3500000000,
        "year_numeric": -3500000000,
        "description": "Earliest microbial life emerges",
        "significance": "Start of biological evolution",
        "level": 2
    },
    {
        "id": 4,
        "event_name": "Rise of Homo sapiens",
        "category": "Early Humanity",
        "subcategory": "Human Evolution",
        "era": "Prehistoric Humanity",
        "region": "Africa",
        "location": "Africa",
        "start_date": -300000,
        "end_date": -300000,
        "year_numeric": -300000,
        "description": "Modern humans appear",
        "significance": "Beginning of modern humans",
        "level": 2
    },
    {
        "id": 5,
        "event_name": "Agricultural Revolution",
        "category": "Civilization",
        "subcategory": "Agriculture",
        "era": "Early Civilizations",
        "region": "Middle East",
        "location": "Fertile Crescent",
        "start_date": -10000,
        "end_date": -8000,
        "year_numeric": -10000,
        "description": "Development of farming societies",
        "significance": "Transition from hunter-gatherers",
        "level": 1
    },
    {
        "id": 6,
        "event_name": "Great Pyramid of Giza Constructed",
        "category": "Civilization",
        "subcategory": "Monument",
        "era": "Early Civilizations",
        "region": "Egypt",
        "location": "Giza",
        "start_date": -2580,
        "end_date": -2560,
        "year_numeric": -2580,
        "description": "Construction of Khufu's pyramid",
        "significance": "Symbol of Egyptian power",
        "level": 1
    },
    {
        "id": 7,
        "event_name": "Founding of Rome",
        "category": "Civilization",
        "subcategory": "City Founding",
        "era": "Classical Age",
        "region": "Italy",
        "location": "Rome",
        "start_date": -753,
        "end_date": -753,
        "year_numeric": -753,
        "description": "Legendary founding of Rome",
        "significance": "Start of Roman civilization",
        "level": 2
    },
    {
        "id": 8,
        "event_name": "Fall of Western Roman Empire",
        "category": "Political Transformation",
        "subcategory": "Empire Collapse",
        "era": "Post-Classical",
        "region": "Europe",
        "location": "Rome",
        "start_date": 476,
        "end_date": 476,
        "year_numeric": 476,
        "description": "Deposition of Romulus Augustulus",
        "significance": "End of Western Roman rule",
        "level": 1
    },
    {
        "id": 9,
        "event_name": "Columbus Reaches Americas",
        "category": "Exploration",
        "subcategory": "Age of Exploration",
        "era": "Early Modern",
        "region": "Atlantic",
        "location": "Americas",
        "start_date": 1492,
        "end_date": 1492,
        "year_numeric": 1492,
        "description": "Voyage of Columbus",
        "significance": "Beginning of sustained European contact",
        "level": 1
    },
    {
        "id": 10,
        "event_name": "American Declaration of Independence",
        "category": "Political Transformation",
        "subcategory": "Independence",
        "era": "Early Modern",
        "region": "United States",
        "location": "Philadelphia",
        "start_date": 1776,
        "end_date": 1776,
        "year_numeric": 1776,
        "description": "Colonies declare independence",
        "significance": "Birth of the United States",
        "level": 1
    },
    {
        "id": 11,
        "event_name": "Industrial Revolution Begins",
        "category": "Technological Innovation",
        "subcategory": "Industrialization",
        "era": "Industrial Era",
        "region": "Europe",
        "location": "Britain",
        "start_date": 1760,
        "end_date": 1840,
        "year_numeric": 1760,
        "description": "Mechanization of industry",
        "significance": "Transforms global economy",
        "level": 1
    },
    {
        "id": 12,
        "event_name": "World War I",
        "category": "War",
        "subcategory": "Global War",
        "era": "Industrial Era",
        "region": "Global",
        "location": "Multiple",
        "start_date": 1914,
        "end_date": 1918,
        "year_numeric": 1914,
        "description": "Major global conflict",
        "significance": "Collapse of empires",
        "level": 1
    },
    {
        "id": 13,
        "event_name": "World War II",
        "category": "War",
        "subcategory": "Global War",
        "era": "Industrial Era",
        "region": "Global",
        "location": "Multiple",
        "start_date": 1939,
        "end_date": 1945,
        "year_numeric": 1939,
        "description": "Largest war in history",
        "significance": "Reshaped global order",
        "level": 1
    },
    {
        "id": 14,
        "event_name": "Apollo 11 Moon Landing",
        "category": "Scientific Breakthrough",
        "subcategory": "Space Exploration",
        "era": "Contemporary",
        "region": "United States",
        "location": "Moon",
        "start_date": 1969,
        "end_date": 1969,
        "year_numeric": 1969,
        "description": "First humans land on the Moon",
        "significance": "Major milestone in space exploration",
        "level": 1
    },
    {
        "id": 15,
        "event_name": "Fall of the Berlin Wall",
        "category": "Political Transformation",
        "subcategory": "Cold War",
        "era": "Contemporary",
        "region": "Germany",
        "location": "Berlin",
        "start_date": 1989,
        "end_date": 1989,
        "year_numeric": 1989,
        "description": "Opening of East/West Berlin border",
        "significance": "Symbolic end of Cold War division",
        "level": 1
    },
    {
        "id": 16,
        "event_name": "September 11 Attacks",
        "category": "Terrorism",
        "subcategory": "Terrorist Attack",
        "era": "Contemporary",
        "region": "United States",
        "location": "New York",
        "start_date": 2001,
        "end_date": 2001,
        "year_numeric": 2001,
        "description": "Coordinated terrorist attacks",
        "significance": "Triggered global War on Terror",
        "level": 1
    },
    {
        "id": 17,
        "event_name": "Alexander the Great: Life & Conquests",
        "category": "Civilization",
        "subcategory": "Historical Figure",
        "era": "Classical Age",
        "region": "Ancient Greece",
        "location": "Pella, Macedonia",
        "start_date": -356,
        "end_date": -323,
        "year_numeric": -356,
        "description": "Birth of Alexander III of Macedon (-356) and his subsequent military campaigns (-334 to -323) against the Persian Empire.",
        "significance": "Conquered a vast empire stretching from Greece to India, spreading Hellenistic culture.",
        "level": 2
    },
    {
        "id": 18,
        "event_name": "Birth of Julius Caesar",
        "category": "Civilization",
        "subcategory": "Historical Figure",
        "era": "Classical Age",
        "region": "Roman Republic",
        "location": "Rome",
        "start_date": -100,
        "end_date": -100,
        "year_numeric": -100,
        "description": "Birth of Roman general and statesman Julius Caesar.",
        "significance": "His actions led to the fall of the Roman Republic and rise of the Roman Empire.",
        "level": 2
    },
    {
        "id": 19,
        "event_name": "Leonardo da Vinci: Life & The Mona Lisa",
        "category": "Cultural Milestone",
        "subcategory": "Historical Figure",
        "era": "Early Modern",
        "region": "Europe",
        "location": "Vinci, Italy",
        "start_date": 1452,
        "end_date": 1506,
        "year_numeric": 1452,
        "description": "Birth of the Renaissance polymath (-1452) and the painting of his masterwork, the Mona Lisa (-1503 to -1506).",
        "significance": "Symbolized the creativity and versatility of the Renaissance.",
        "level": 2
    },
    {
        "id": 20,
        "event_name": "Galileo Galilei: Life & Observations",
        "category": "Scientific Breakthrough",
        "subcategory": "Historical Figure",
        "era": "Early Modern",
        "region": "Europe",
        "location": "Pisa, Italy",
        "start_date": 1564,
        "end_date": 1610,
        "year_numeric": 1564,
        "description": "Life of the 'father of observational astronomy' (-1564) through the publication of his telescopic discoveries (-1610).",
        "significance": "Provided critical evidence for the heliocentric model of the solar system.",
        "level": 2
    },
    {
        "id": 21,
        "event_name": "Isaac Newton: Life & Principia",
        "category": "Scientific Breakthrough",
        "subcategory": "Historical Figure",
        "era": "Early Modern",
        "region": "Europe",
        "location": "England",
        "start_date": 1643,
        "end_date": 1687,
        "year_numeric": 1643,
        "description": "Life of the physicist (-1643) and the publication of Philosophiae Naturalis Principia Mathematica (-1687).",
        "significance": "Newton's laws of motion and gravity formed the foundation of classical physics.",
        "level": 1
    },
    {
        "id": 22,
        "event_name": "Birth of Johann Sebastian Bach",
        "category": "Cultural Milestone",
        "subcategory": "Music",
        "era": "Early Modern",
        "region": "Europe",
        "location": "Germany",
        "start_date": 1685,
        "end_date": 1685,
        "year_numeric": 1685,
        "description": "Birth of composer Johann Sebastian Bach.",
        "significance": "One of the most influential composers in Western classical music.",
        "level": 3
    },
    {
        "id": 23,
        "event_name": "Wolfgang Amadeus Mozart: Life & Operas",
        "category": "Cultural Milestone",
        "subcategory": "Music",
        "era": "Early Modern",
        "region": "Europe",
        "location": "Salzburg",
        "start_date": 1756,
        "end_date": 1791,
        "year_numeric": 1756,
        "description": "Life of the musical prodigy (-1756) through the composition of his final revolutionary operas (-1791).",
        "significance": "Revolutionized classical opera and global composition.",
        "level": 3
    },
    {
        "id": 24,
        "event_name": "Charles Darwin: Life & Evolution",
        "category": "Scientific Breakthrough",
        "subcategory": "Historical Figure",
        "era": "Industrial Era",
        "region": "Europe",
        "location": "England",
        "start_date": 1809,
        "end_date": 1859,
        "year_numeric": 1809,
        "description": "Life of the naturalist (-1809) culminating in the publication of On the Origin of Species (-1859).",
        "significance": "Developed the theory of evolution by natural selection.",
        "level": 1
    },
    {
        "id": 25,
        "event_name": "Albert Einstein: Life & Relativity",
        "category": "Scientific Breakthrough",
        "subcategory": "Historical Figure",
        "era": "Industrial Era",
        "region": "Europe",
        "location": "Germany",
        "start_date": 1879,
        "end_date": 1915,
        "year_numeric": 1879,
        "description": "Life of the theoretical physicist (-1879) and the publication of General Relativity (-1915).",
        "significance": "Changed scientific understanding of gravity, space, and time.",
        "level": 1
    },
    {
        "id": 26,
        "event_name": "Composition of the Homeric Epics",
        "category": "Cultural Milestone",
        "subcategory": "Epic Literature",
        "era": "Classical Age",
        "region": "Europe",
        "location": "Ancient Greece",
        "start_date": -800,
        "end_date": -750,
        "year_numeric": -800,
        "description": "The Iliad and the Odyssey emerged in archaic Greece and became foundational works of Western literature. They preserved myth, heroic ideals, and oral tradition in forms that shaped later literature, education, and identity across the Greek world.",
        "significance": "These epics became enduring foundations of Western literary culture and helped define the moral and imaginative framework of ancient Greece.",
        "level": 2
    },
    {
        "id": 27,
        "event_name": "Life and Teachings of Confucius",
        "category": "Cultural Milestone",
        "subcategory": "Philosophy",
        "era": "Classical Age",
        "region": "Asia",
        "location": "Qufu, State of Lu, China",
        "start_date": -551,
        "end_date": -479,
        "year_numeric": -551,
        "description": "Confucius taught an ethical and social philosophy centered on virtue, order, family obligation, education, and just governance. His ideas were later compiled and institutionalized, deeply influencing Chinese political culture and East Asian civilization.",
        "significance": "Confucian thought became one of the most influential moral and political systems in world history.",
        "level": 1
    },
    {
        "id": 28,
        "event_name": "Life of Socrates",
        "category": "Cultural Milestone",
        "subcategory": "Philosophy",
        "era": "Classical Age",
        "region": "Europe",
        "location": "Athens, Greece",
        "start_date": -470,
        "end_date": -399,
        "year_numeric": -470,
        "description": "Socrates transformed philosophy by emphasizing questioning, dialogue, and the examination of moral assumptions rather than mythic or purely natural explanation. Though he wrote nothing himself, his method and trial became defining moments in the history of thought.",
        "significance": "Socrates helped establish critical inquiry and ethical reasoning as central pillars of Western philosophy.",
        "level": 2
    },
    {
        "id": 29,
        "event_name": "Life of Plato",
        "category": "Cultural Milestone",
        "subcategory": "Philosophy",
        "era": "Classical Age",
        "region": "Europe",
        "location": "Athens, Greece",
        "start_date": -427,
        "end_date": -347,
        "year_numeric": -427,
        "description": "Plato founded the Academy in Athens and wrote dialogues exploring justice, knowledge, politics, metaphysics, and the ideal state. His works transmitted Socratic thought and became central texts in philosophy, theology, and political theory.",
        "significance": "Plato's writings shaped the intellectual foundations of Western philosophy, education, and political thought.",
        "level": 2
    },
    {
        "id": 30,
        "event_name": "Life of Aristotle",
        "category": "Scientific Breakthrough",
        "subcategory": "Philosophy and Natural Science",
        "era": "Classical Age",
        "region": "Europe",
        "location": "Stagira and Athens, Greece",
        "start_date": -384,
        "end_date": -322,
        "year_numeric": -384,
        "description": "Aristotle developed influential systems of logic, ethics, politics, biology, and metaphysics while studying and teaching in the Greek world. His works became authoritative across the Mediterranean and later Islamic and European scholarship.",
        "significance": "Aristotle organized vast domains of knowledge in ways that shaped science, logic, and philosophy for centuries.",
        "level": 2
    },
    {
        "id": 31,
        "event_name": "Life and Works of Archimedes",
        "category": "Scientific Breakthrough",
        "subcategory": "Mathematics and Engineering",
        "era": "Classical Age",
        "region": "Europe",
        "location": "Syracuse, Sicily",
        "start_date": -287,
        "end_date": -212,
        "year_numeric": -287,
        "description": "Archimedes made major advances in geometry, mechanics, hydrostatics, and engineering, including work on levers, buoyancy, and approximations of pi. His theoretical and practical insights influenced both ancient and later scientific traditions.",
        "significance": "Archimedes helped establish mathematics and physics as rigorous tools for understanding the physical world.",
        "level": 2
    },
    {
        "id": 32,
        "event_name": "Life and Ministry of Jesus of Nazareth",
        "category": "Cultural Milestone",
        "subcategory": "Religion",
        "era": "Classical Age",
        "region": "Middle East",
        "location": "Judea, Roman Empire",
        "start_date": 0,
        "end_date": 30,
        "year_numeric": 0,
        "description": "Jesus of Nazareth preached in Roman Judea, attracting followers whose accounts of his teachings, crucifixion, and reported resurrection formed the core of Christianity. The movement that grew from his life spread across the Roman world and beyond.",
        "significance": "The life of Jesus became the foundation of Christianity, one of the most influential religious traditions in world history.",
        "level": 1
    },
    {
        "id": 33,
        "event_name": "Life of Muhammad and the Rise of Islam",
        "category": "Political Transformation",
        "subcategory": "Religion and State Formation",
        "era": "Post-Classical",
        "region": "Middle East",
        "location": "Mecca and Medina, Arabia",
        "start_date": 570,
        "end_date": 632,
        "year_numeric": 570,
        "description": "Muhammad's prophetic mission in Arabia produced the Qur'an and unified diverse communities under a new religious and political order. After his death, Islam expanded rapidly across the Middle East, North Africa, and beyond.",
        "significance": "Muhammad's life launched Islam and reshaped the religious, political, and cultural history of Afro-Eurasia.",
        "level": 1
    },
    {
        "id": 34,
        "event_name": "Viking Age",
        "category": "Political Transformation",
        "subcategory": "Migration and Maritime Expansion",
        "era": "Post-Classical",
        "region": "Europe",
        "location": "Scandinavia, British Isles, North Atlantic, and Continental Europe",
        "start_date": 793,
        "end_date": 1066,
        "year_numeric": 793,
        "description": "The Viking Age began with Scandinavian raids and expanded into trade, settlement, and state-building across Europe and the North Atlantic. Vikings connected distant regions through maritime networks and helped transform medieval European politics and commerce.",
        "significance": "The Viking Age redrew political and trade connections across northern Europe and accelerated cross-cultural exchange.",
        "level": 2
    },
    {
        "id": 35,
        "event_name": "Charlemagne Crowned Emperor",
        "category": "Political Transformation",
        "subcategory": "Imperial Coronation",
        "era": "Post-Classical",
        "region": "Europe",
        "location": "Rome, Italy",
        "start_date": 800,
        "end_date": 800,
        "year_numeric": 800,
        "description": "On Christmas Day in 800, Pope Leo III crowned Charlemagne emperor, symbolically reviving imperial rule in Western Europe. The event strengthened ties between kingship and the Latin Church while shaping the political legacy of medieval Europe.",
        "significance": "Charlemagne's coronation helped define medieval European kingship, empire, and church-state relations.",
        "level": 2
    },
    {
        "id": 36,
        "event_name": "Invention of Gunpowder in China",
        "category": "Technological Innovation",
        "subcategory": "Military Technology",
        "era": "Post-Classical",
        "region": "Asia",
        "location": "China",
        "start_date": 850,
        "end_date": 850,
        "year_numeric": 850,
        "description": "Gunpowder was developed by Chinese alchemists during the Tang period and soon found military applications in bombs, rockets, and early firearms. Its later spread across Eurasia transformed warfare and state power.",
        "significance": "Gunpowder revolutionized military technology and permanently altered the global balance of power.",
        "level": 1
    },
    {
        "id": 37,
        "event_name": "The Crusades",
        "category": "War",
        "subcategory": "Religious Conflict",
        "era": "Post-Classical",
        "region": "Europe and Middle East",
        "location": "Eastern Mediterranean",
        "start_date": 1095,
        "end_date": 1291,
        "year_numeric": 1095,
        "description": "The Crusades were a series of armed campaigns launched primarily by Latin Christian powers into the eastern Mediterranean. They combined religious motives, political ambitions, and commercial interests, leaving lasting effects on Christian-Muslim relations and Mediterranean exchange.",
        "significance": "The Crusades reshaped religious conflict, trade, and political relations between Europe and the Middle East.",
        "level": 2
    },
    {
        "id": 38,
        "event_name": "Magna Carta Sealed",
        "category": "Political Transformation",
        "subcategory": "Constitutional Development",
        "era": "Post-Classical",
        "region": "Europe",
        "location": "Runnymede, England",
        "start_date": 1215,
        "end_date": 1215,
        "year_numeric": 1215,
        "description": "King John of England sealed Magna Carta under pressure from rebellious barons, accepting limits on royal authority and legal protections for subjects. Though initially narrow and contested, it became a landmark in constitutional history.",
        "significance": "Magna Carta became a foundational symbol of limited government and the rule of law.",
        "level": 1
    },
    {
        "id": 39,
        "event_name": "Life and Conquests of Genghis Khan",
        "category": "War",
        "subcategory": "Empire Expansion",
        "era": "Post-Classical",
        "region": "Asia",
        "location": "Mongolia and Eurasia",
        "start_date": 1162,
        "end_date": 1227,
        "year_numeric": 1162,
        "description": "Genghis Khan united the Mongol tribes and launched campaigns that created the largest contiguous land empire in history. Mongol expansion transformed Eurasian trade, warfare, communications, and state structures.",
        "significance": "Genghis Khan reordered Eurasia through conquest and opened vast new channels of exchange across continents.",
        "level": 2
    },
    {
        "id": 40,
        "event_name": "Black Death",
        "category": "Political Transformation",
        "subcategory": "Pandemic",
        "era": "Post-Classical",
        "region": "Europe, Asia, and North Africa",
        "location": "Afro-Eurasia",
        "start_date": 1347,
        "end_date": 1351,
        "year_numeric": 1347,
        "description": "The Black Death was a devastating pandemic of bubonic plague that spread across Afro-Eurasia, killing a massive share of the population in many regions. It destabilized economies, weakened traditional social orders, and altered labor relations and religious life.",
        "significance": "The Black Death transformed demography, labor systems, and social structures across much of the known world.",
        "level": 1
    },
    {
        "id": 41,
        "event_name": "Development of the Printing Press",
        "category": "Technological Innovation",
        "subcategory": "Printing",
        "era": "Early Modern",
        "region": "Europe",
        "location": "Mainz, Germany",
        "start_date": 1450,
        "end_date": 1455,
        "year_numeric": 1450,
        "description": "Johannes Gutenberg developed movable-type printing in Europe, making the large-scale reproduction of texts far faster and cheaper than manuscript copying. The new technology accelerated literacy, scholarship, administration, and the spread of religious and political ideas.",
        "significance": "The printing press transformed communication and became a decisive engine of modern knowledge, reform, and mass culture.",
        "level": 1
    },
    {
        "id": 43,
        "event_name": "Magellan-Elcano Circumnavigation",
        "category": "Scientific Breakthrough",
        "subcategory": "Global Exploration",
        "era": "Early Modern",
        "region": "Global",
        "location": "Atlantic, Pacific, and Indian Oceans",
        "start_date": 1519,
        "end_date": 1522,
        "year_numeric": 1519,
        "description": "The expedition begun by Ferdinand Magellan and completed under Juan Sebastian Elcano achieved the first circumnavigation of the Earth. The voyage demonstrated the practical global scale of the planet and intensified the integration of world trade routes.",
        "significance": "The first circumnavigation confirmed a truly global world system and marked a major turning point in navigation, commerce, and geographic knowledge.",
        "level": 2
    },
    {
        "id": 50,
        "event_name": "Permanent Neolithic Settlements (Jericho)",
        "category": "Civilization",
        "subcategory": "Settlement",
        "era": "Early Civilizations",
        "region": "Middle East",
        "location": "Jericho",
        "start_date": -9000,
        "end_date": -8000,
        "year_numeric": -9000,
        "description": "One of the earliest known permanent human settlements emerges in Jericho, featuring stone structures and early defensive walls.",
        "significance": "Marks the transition from nomadic life to permanent settlement, a foundational step toward civilization.",
        "level": 2
    },
    {
        "id": 51,
        "event_name": "Proto-Urban Society at Çatalhöyük",
        "category": "Civilization",
        "subcategory": "Proto-City",
        "era": "Early Civilizations",
        "region": "Anatolia",
        "location": "Çatalhöyük",
        "start_date": -7500,
        "end_date": -5700,
        "year_numeric": -7500,
        "description": "Çatalhöyük develops as a dense, organized settlement with shared walls, ritual spaces, and early social structure.",
        "significance": "Represents one of the earliest large-scale human communities with proto-urban organization.",
        "level": 2
    },
    {
        "id": 52,
        "event_name": "Development of Pottery and Food Storage",
        "category": "Technological Innovation",
        "subcategory": "Agricultural Technology",
        "era": "Early Civilizations",
        "region": "Global",
        "location": "Multiple",
        "start_date": -7000,
        "end_date": -5000,
        "year_numeric": -7000,
        "description": "Humans develop pottery for storing surplus food, enabling longer-term resource management and trade.",
        "significance": "Food storage allows surplus accumulation, which supports population growth and specialization.",
        "level": 2
    },
    {
        "id": 53,
        "event_name": "Early Social Stratification Emerges",
        "category": "Civilization",
        "subcategory": "Social Structure",
        "era": "Early Civilizations",
        "region": "Global",
        "location": "Multiple",
        "start_date": -7000,
        "end_date": -4000,
        "year_numeric": -7000,
        "description": "Human societies begin to differentiate into roles such as leaders, laborers, and religious figures.",
        "significance": "Introduces hierarchy and division of labor, essential for complex societal organization.",
        "level": 2
    },
    {
        "id": 54,
        "event_name": "Chalcolithic Period (Copper Age)",
        "category": "Technological Innovation",
        "subcategory": "Metallurgy",
        "era": "Early Civilizations",
        "region": "Middle East",
        "location": "Mesopotamia",
        "start_date": -5000,
        "end_date": -3300,
        "year_numeric": -5000,
        "description": "The use of copper tools begins, marking the transition from stone to metal technology.",
        "significance": "Metal tools increase efficiency in agriculture, construction, and warfare.",
        "level": 2
    },
    {
        "id": 55,
        "event_name": "Rise of Sumerian City-States",
        "category": "Civilization",
        "subcategory": "Urbanization",
        "era": "Early Civilizations",
        "region": "Middle East",
        "location": "Mesopotamia",
        "start_date": -4500,
        "end_date": -3000,
        "year_numeric": -4500,
        "description": "Sumerian cities such as Uruk and Ur develop into complex urban centers with governance, religion, and economic systems.",
        "significance": "Represents the emergence of the first true cities and organized civilization.",
        "level": 1
    },
    {
        "id": 56,
        "event_name": "Invention of Writing (Cuneiform)",
        "category": "Scientific Breakthrough",
        "subcategory": "Writing System",
        "era": "Early Civilizations",
        "region": "Middle East",
        "location": "Sumer",
        "start_date": -3200,
        "end_date": -3200,
        "year_numeric": -3200,
        "description": "Cuneiform writing is developed in Mesopotamia for record-keeping and administration.",
        "significance": "Marks the beginning of recorded history and complex communication systems.",
        "level": 1
    },
    {
        "id": 57,
        "event_name": "Development of Early Trade Networks",
        "category": "Economic Event",
        "subcategory": "Trade",
        "era": "Early Civilizations",
        "region": "Middle East and South Asia",
        "location": "Mesopotamia and Indus Valley",
        "start_date": -3000,
        "end_date": -2000,
        "year_numeric": -3000,
        "description": "Trade routes emerge connecting Mesopotamia with distant regions such as the Indus Valley, exchanging goods and ideas.",
        "significance": "Expands economic systems and cultural exchange beyond local regions.",
        "level": 2
    },
    {
        "id": 58,
        "event_name": "Formation of Early State Governments",
        "category": "Political Transformation",
        "subcategory": "State Formation",
        "era": "Early Civilizations",
        "region": "Global",
        "location": "Multiple",
        "start_date": -3000,
        "end_date": -2500,
        "year_numeric": -3000,
        "description": "Centralized governments emerge with systems of taxation, law, and organized religion.",
        "significance": "Establishes the framework for governance, law, and administrative control.",
        "level": 1
    },
    {
        "id": 59,
        "event_name": "Unification of Egypt under Narmer",
        "category": "Political Transformation",
        "subcategory": "State Unification",
        "era": "Early Civilizations",
        "region": "Africa",
        "location": "Egypt",
        "start_date": -3100,
        "end_date": -3100,
        "year_numeric": -3100,
        "description": "Upper and Lower Egypt are unified under a single ruler, traditionally identified as Narmer.",
        "significance": "Creates one of the first centralized nation-states in history.",
        "level": 1
    },
    {
        "id": 60,
        "event_name": "Early Dynastic Egypt",
        "category": "Civilization",
        "subcategory": "State Development",
        "era": "Early Civilizations",
        "region": "Africa",
        "location": "Egypt",
        "start_date": -3000,
        "end_date": -2600,
        "year_numeric": -3000,
        "description": "Egypt develops a stable political structure, religious system, and writing traditions, laying the groundwork for Old Kingdom state power.",
        "significance": "Establishes the cultural and political foundations of ancient Egyptian civilization.",
        "level": 2
    },
    {
        "id": 61,
        "event_name": "Construction of Ziggurats",
        "category": "Cultural Milestone",
        "subcategory": "Monumental Architecture",
        "era": "Early Civilizations",
        "region": "Middle East",
        "location": "Mesopotamia",
        "start_date": -3000,
        "end_date": -2500,
        "year_numeric": -3000,
        "description": "Large temple structures are built in Mesopotamian cities as religious, administrative, and symbolic centers of power.",
        "significance": "Represents the rise of organized religion and monumental construction in early urban civilization.",
        "level": 2
    },
    {
        "id": 62,
        "event_name": "Step Pyramid of Djoser",
        "category": "Cultural Milestone",
        "subcategory": "Monumental Architecture",
        "era": "Early Civilizations",
        "region": "Africa",
        "location": "Saqqara, Egypt",
        "start_date": -2670,
        "end_date": -2650,
        "year_numeric": -2670,
        "description": "The first large-scale stone pyramid is constructed for Pharaoh Djoser during Egypt's Old Kingdom, marking a breakthrough in architecture and royal monumentality.",
        "significance": "Marks a major leap in engineering and the beginning of pyramid construction.",
        "level": 2
    },
    {
        "id": 63,
        "event_name": "Abraham and the Foundations of Judaism",
        "category": "Cultural Milestone",
        "subcategory": "Religion",
        "era": "Early Civilizations",
        "region": "Middle East",
        "location": "Mesopotamia and Canaan",
        "start_date": -2000,
        "end_date": -1800,
        "year_numeric": -2000,
        "description": "Abraham, revered in Jewish tradition as the founding patriarch, is associated with the early 2nd millennium BCE and the covenantal beginnings of the Hebrew people.",
        "significance": "Judaism became a foundational religious tradition whose ideas shaped law, ethics, identity, and the later development of Christianity and Islam.",
        "level": 1
    },
    {
        "id": 64,
        "event_name": "Life of the Buddha and the Rise of Buddhism",
        "category": "Cultural Milestone",
        "subcategory": "Religion",
        "era": "Classical Age",
        "region": "Asia",
        "location": "Northeastern India",
        "start_date": -563,
        "end_date": -483,
        "year_numeric": -563,
        "description": "Siddhartha Gautama, later known as the Buddha, taught a path centered on suffering, compassion, and enlightenment, giving rise to one of the world's major religions.",
        "significance": "Buddhism shaped philosophy, ethics, art, and political culture across much of Asia and remains one of the most influential religious traditions in world history.",
        "level": 1
    },
    {
        "id": 65,
        "event_name": "COVID-19 Pandemic",
        "category": "Political Transformation",
        "subcategory": "Pandemic",
        "era": "Contemporary",
        "region": "Global",
        "location": "Global",
        "start_date": 2020,
        "end_date": 2023,
        "year_numeric": 2020,
        "description": "The global spread of COVID-19 disrupted health systems, education, travel, work, politics, and daily life on a worldwide scale.",
        "significance": "COVID-19 reshaped modern life across nearly every society and became one of the defining global events of the early 21st century.",
        "level": 1
    },
    {
        "id": 66,
        "event_name": "Bolshevik Revolution",
        "category": "Political Transformation",
        "subcategory": "Revolution",
        "era": "Industrial Era",
        "region": "Europe",
        "location": "Petrograd, Russia",
        "start_date": 1917,
        "end_date": 1917,
        "year_numeric": 1917,
        "description": "In the October Revolution of 1917, the Bolsheviks seized power in Russia and began building the Soviet state.",
        "significance": "The Bolshevik Revolution transformed global politics by creating the first communist state and shaping much of the 20th century.",
        "level": 2
    },
    {
        "id": 67,
        "event_name": "Early Vedic Tradition and the Foundations of Hinduism",
        "category": "Cultural Milestone",
        "subcategory": "Religion",
        "era": "Early Civilizations",
        "region": "Asia",
        "location": "Indian Subcontinent",
        "start_date": -1500,
        "end_date": -500,
        "year_numeric": -1500,
        "description": "The early Vedic tradition on the Indian subcontinent preserved sacred texts, rituals, and religious ideas that became the oldest written layer of what later developed into Hinduism.",
        "significance": "These traditions formed the deep religious and cultural roots of Hinduism, one of the world's oldest and most influential living religions.",
        "level": 2
    },
    {
        "id": 68,
        "event_name": "Ludwig van Beethoven",
        "category": "Cultural Milestone",
        "subcategory": "Music",
        "era": "Industrial Era",
        "region": "Europe",
        "location": "Bonn and Vienna",
        "start_date": 1770,
        "end_date": 1827,
        "year_numeric": 1770,
        "description": "Beethoven was a German composer whose work bridged the Classical and Romantic eras and became central to the history of Western music.",
        "significance": "Beethoven remains one of the most celebrated composers in history, though his impact is more cultural than universally civilizational in the Chronos framework.",
        "level": 3
    },
    {
        "id": 69,
        "event_name": "Nicolaus Copernicus and the Heliocentric Theory",
        "category": "Scientific Breakthrough",
        "subcategory": "Astronomy",
        "era": "Early Modern",
        "region": "Europe",
        "location": "Poland",
        "start_date": 1473,
        "end_date": 1543,
        "year_numeric": 1473,
        "description": "Copernicus proposed that Earth and the other planets revolve around the Sun, and his theory was published in 1543.",
        "significance": "Copernicus helped launch the Scientific Revolution by changing humanity's understanding of the cosmos and Earth's place within it.",
        "level": 2
    },
    {
        "id": 70,
        "event_name": "Statue of Zeus at Olympia",
        "category": "Cultural Milestone",
        "subcategory": "Monumental Sculpture",
        "era": "Classical Age",
        "region": "Europe",
        "location": "Olympia, Greece",
        "start_date": -435,
        "end_date": -435,
        "year_numeric": -435,
        "description": "A massive seated statue of the god Zeus was created at Olympia by the sculptor Phidias and became one of the most celebrated artistic achievements of the ancient Greek world.",
        "significance": "It stood as one of the greatest symbols of Greek religion, art, and monumental craftsmanship.",
        "level": 2
    },
    {
        "id": 71,
        "event_name": "Temple of Artemis at Ephesus",
        "category": "Cultural Milestone",
        "subcategory": "Monumental Architecture",
        "era": "Classical Age",
        "region": "Asia",
        "location": "Ephesus, Anatolia",
        "start_date": -550,
        "end_date": -356,
        "year_numeric": -550,
        "description": "The great Temple of Artemis at Ephesus was built in the 6th century BCE and later rebuilt after its destruction in 356 BCE, becoming one of the most admired sacred structures of the ancient world.",
        "significance": "It became one of antiquity's most famous temples and a lasting symbol of religion, wealth, and artistic grandeur.",
        "level": 2
    },
    {
        "id": 72,
        "event_name": "Mausoleum at Halicarnassus",
        "category": "Cultural Milestone",
        "subcategory": "Monumental Tomb",
        "era": "Classical Age",
        "region": "Asia",
        "location": "Halicarnassus, Caria",
        "start_date": -353,
        "end_date": -351,
        "year_numeric": -353,
        "description": "Built for Mausolus by Artemisia II, the Mausoleum at Halicarnassus was an enormous royal tomb whose fame was so great that its name became the root of the word 'mausoleum.'",
        "significance": "It became one of the best-known funerary monuments in history and a model of elite memorial architecture.",
        "level": 2
    },
    {
        "id": 73,
        "event_name": "Colossus of Rhodes",
        "category": "Cultural Milestone",
        "subcategory": "Monumental Sculpture",
        "era": "Classical Age",
        "region": "Europe",
        "location": "Rhodes, Greece",
        "start_date": -292,
        "end_date": -280,
        "year_numeric": -292,
        "description": "The Colossus of Rhodes was a giant bronze statue of the sun god Helios erected to celebrate Rhodes's survival after siege, and it stood as one of the most famous monuments of the ancient world.",
        "significance": "It symbolized civic pride, artistic ambition, and the power of monumental public sculpture in the Hellenistic age.",
        "level": 2
    },
    {
        "id": 74,
        "event_name": "Lighthouse of Alexandria",
        "category": "Technological Innovation",
        "subcategory": "Monumental Engineering",
        "era": "Classical Age",
        "region": "Africa",
        "location": "Alexandria, Egypt",
        "start_date": -280,
        "end_date": -270,
        "year_numeric": -280,
        "description": "The Pharos of Alexandria was built on the island of Pharos to guide ships into the harbor of Alexandria and became one of the tallest and most famous structures of the ancient world.",
        "significance": "It became the ancient world's most famous lighthouse and a landmark achievement in practical engineering and navigation.",
        "level": 2
    },
    {
        "id": 75,
        "event_name": "Hanging Gardens of Babylon",
        "category": "Cultural Milestone",
        "subcategory": "Legendary Monument",
        "era": "Early Civilizations",
        "region": "Middle East",
        "location": "Babylon, Mesopotamia",
        "start_date": -600,
        "end_date": -560,
        "year_numeric": -600,
        "description": "The Hanging Gardens of Babylon were described in ancient accounts as a magnificent terraced garden of great beauty, though historians still debate whether they existed exactly as later writers described.",
        "significance": "They remain one of the most famous and mysterious wonders of the ancient world, symbolizing the blend of history, myth, and royal splendor.",
        "level": 2
    },
    {
        "id": 76,
        "event_name": "Stonehenge",
        "category": "Cultural Milestone",
        "subcategory": "Monumental Architecture",
        "era": "Early Civilizations",
        "region": "Europe",
        "location": "Wiltshire, England",
        "start_date": -3100,
        "end_date": -1500,
        "year_numeric": -3100,
        "description": "Stonehenge was built in several stages over many centuries as a monumental stone circle and ritual site on Salisbury Plain.",
        "significance": "It remains one of the world's most recognizable prehistoric monuments and a major symbol of early ritual, engineering, and communal effort.",
        "level": 2
    },
    {
        "id": 77,
        "event_name": "Roman Colosseum",
        "category": "Cultural Milestone",
        "subcategory": "Monumental Architecture",
        "era": "Classical Age",
        "region": "Europe",
        "location": "Rome, Italy",
        "start_date": 72,
        "end_date": 80,
        "year_numeric": 72,
        "description": "The Colosseum was constructed in Rome under the Flavian emperors as a massive amphitheater for public spectacles, including gladiatorial contests and state ceremonies.",
        "significance": "It became one of the most enduring symbols of Roman engineering, imperial power, and mass public entertainment.",
        "level": 2
    },
    {
        "id": 78,
        "event_name": "Qin Shi Huang and the Unification of China",
        "category": "Political Transformation",
        "subcategory": "State Unification",
        "era": "Classical Age",
        "region": "Asia",
        "location": "China",
        "start_date": -259,
        "end_date": -210,
        "year_numeric": -259,
        "description": "Qin Shi Huang, the first emperor of a unified China, conquered rival states and established a centralized imperial system with standardized writing, weights, measures, and roads.",
        "significance": "He created the first unified Chinese empire and laid the foundation for the long imperial structure that shaped Chinese history for over two thousand years.",
        "level": 1
    },
    {
        "id": 79,
        "event_name": "Terracotta Army",
        "category": "Cultural Milestone",
        "subcategory": "Monumental Tomb Complex",
        "era": "Classical Age",
        "region": "Asia",
        "location": "Xi'an, China",
        "start_date": -246,
        "end_date": -210,
        "year_numeric": -246,
        "description": "The Terracotta Army was created as part of the vast mausoleum complex of Qin Shi Huang, with thousands of life-sized soldiers, horses, and chariots buried to guard the emperor in the afterlife.",
        "significance": "It stands as one of the greatest archaeological discoveries in history and a remarkable symbol of imperial power, military organization, and artistic achievement in ancient China.",
        "level": 2
    }
];

// Mapping generator
const chronosSeedDatabase = chronosSeedDataRaw.map(e => {
    const year = e.year_numeric || e.start_date;
    const endYear = e.end_date || year;

    // Explicit significance level from raw data, fallback to previous year-based logic for safety
    const level = e.level || (year < -10000 ? 2 : 1);

    // Confidence heuristic
    let confidence = "High";
    if (e.start_date !== e.end_date) confidence = "Moderate";
    if (year < -10000) confidence = "Estimation";
    if (year < -1000000) confidence = "Theoretical";

    return {
        id: `seed-${e.id}`,
        startYear: year,
        endYear: endYear,
        title: e.event_name,
        significance: level,
        confidence: confidence,
        snippet: e.significance || (e.description.split('.')[0] + '.'),
        description: e.description,
        category: e.category,
        subcategory: e.subcategory,
        era: e.era,
        region: e.region,
        location: e.location,
        gap: 400, // Balanced descent gap
        approx: e.start_date !== e.end_date || e.start_date < -1000,
        source: 'SEED'
    };
});

// ════════════════════════════════════════════════
// Civilization Arc Module: Relationship Layer
// ════════════════════════════════════════════════

const chronosSeedRelationships = [
    { "source": 50, "target": 51, "type": "enables" },
    { "source": 51, "target": 53, "type": "leads_to" },
    { "source": 52, "target": 53, "type": "enables" },
    { "source": 53, "target": 55, "type": "drives" },
    { "source": 54, "target": 55, "type": "accelerates" },
    { "source": 55, "target": 56, "type": "requires" },
    { "source": 55, "target": 57, "type": "expands" },
    { "source": 56, "target": 58, "type": "enables" },
    { "source": 58, "target": 59, "type": "culminates_in" },
    { "source": 59, "target": 60, "type": "leads_to" },
    { "source": 55, "target": 61, "type": "leads_to" },
    { "source": 60, "target": 62, "type": "enables" }
];

const chronosSeedMeta = {
    "module_name": "Civilization Arc",
    "module_slug": "civilization-arc",
    "start_anchor": "Agricultural Revolution",
    "end_anchor": "Great Pyramid of Giza Constructed",
    "theme": "The emergence of civilization from agriculture to centralized monumental states",
    "historical_logic": [
        "Agriculture enables settlement",
        "Settlement enables surplus",
        "Surplus enables hierarchy",
        "Hierarchy enables cities",
        "Cities require writing and administration",
        "Administration enables states",
        "States produce monumental architecture"
    ]
};
