// Vetted Wikidata Historical Consensus
const wikidataHistory = [
    {
        "id": "Q835034",
        "title": "Triassic-Jurassic mass extinction",
        "date": "201300000 BCE",
        "startYear": -201300000,
        "description": "mass extinction at the end of the Triassic",
        "snippet": "mass extinction at the end of the Triassic",
        "significance": 1,
        "gap": 150
    },
    {
        "id": "Q1404282",
        "title": "Kondoa Rock Art Sites",
        "date": "2999 BCE",
        "startYear": -2999,
        "description": "cave in Tanzania",
        "snippet": "cave in Tanzania",
        "significance": 1,
        "gap": 150
    },
    {
        "id": "Q866862",
        "title": "Battle of Aegospotami",
        "date": "404 BCE",
        "startYear": -404,
        "description": "Final major battle of the Peloponnesian War, 405 BCE",
        "snippet": "Final major battle of the Peloponnesian War, 405 BCE",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q1144693",
        "title": "Minoan eruption",
        "date": "1600 BCE",
        "startYear": -1600,
        "description": "major volcanic eruption around 1600 BCE",
        "snippet": "major volcanic eruption around 1600 BCE",
        "significance": 1,
        "gap": 150
    },
    {
        "id": "Q431205",
        "title": "Battle of Cunaxa",
        "date": "400 BCE",
        "startYear": -400,
        "description": "battle",
        "snippet": "battle",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q1370497",
        "title": "Ahasuerus",
        "date": "484 BCE",
        "startYear": -484,
        "description": "name of one or more kings of Persia in the Hebrew Bible (Esther, Ezra, Daniel), cognate to the Greek form Xerxes or Artaxerxes",
        "snippet": "name of one or more kings of Persia in the Hebrew Bible (Esther, Ezra, Daniel), cognate to the Greek form Xerxes or Arta...",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q747679",
        "title": "Battle of Artemisium",
        "date": "479 BCE",
        "startYear": -479,
        "description": "480 BCE naval battle",
        "snippet": "480 BCE naval battle",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q378957",
        "title": "Battle of Ticinus",
        "date": "217 BCE",
        "startYear": -217,
        "description": "battle of the Second Punic War between the Carthaginian forces of Hannibal and the Romans under Publius Cornelius Scipio in November 218 BCE",
        "snippet": "battle of the Second Punic War between the Carthaginian forces of Hannibal and the Romans under Publius Cornelius Scipio...",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q1065985",
        "title": "Ordovician–Silurian extinction event",
        "date": "443800000 BCE",
        "startYear": -443800000,
        "description": "mass extinction event at the end of the Ordovician period and the beginning of the Silurian period in the Paleozoic era, around 444 million years ago",
        "snippet": "mass extinction event at the end of the Ordovician period and the beginning of the Silurian period in the Paleozoic era,...",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q733364",
        "title": "Battle of Megiddo",
        "date": "1456 BCE",
        "startYear": -1456,
        "description": "ancient battle between the Egyptian Empire and Canaanite rebels",
        "snippet": "ancient battle between the Egyptian Empire and Canaanite rebels",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q837561",
        "title": "Great Oxygenation Event",
        "date": "2450000000 BCE",
        "startYear": -2450000000,
        "description": "Paleoproterozoic surge in atmospheric oxygen",
        "snippet": "Paleoproterozoic surge in atmospheric oxygen",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q461599",
        "title": "Battle of Leuctra",
        "date": "370 BCE",
        "startYear": -370,
        "description": "battle between Thebes and Sparta, 371 BCE",
        "snippet": "battle between Thebes and Sparta, 371 BCE",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q319124",
        "title": "Battle of Ipsus",
        "date": "300 BCE",
        "startYear": -300,
        "description": "battle",
        "snippet": "battle",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q391087",
        "title": "Battle of Cynoscephalae",
        "date": "196 BCE",
        "startYear": -196,
        "description": "battle of the Second Macedonian War",
        "snippet": "battle of the Second Macedonian War",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q917811",
        "title": "Battle of Magnesia",
        "date": "189 BCE",
        "startYear": -189,
        "description": "battle",
        "snippet": "battle",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q217043",
        "title": "Olduvai Gorge",
        "date": "1750000 BCE",
        "startYear": -1750000,
        "description": "archaeological site in Tanzania",
        "snippet": "archaeological site in Tanzania",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q32919",
        "title": "Cambrian explosion",
        "date": "543000000 BCE",
        "startYear": -543000000,
        "description": "Portion of the Cambrian Period during which life vastly diversified",
        "snippet": "Portion of the Cambrian Period during which life vastly diversified",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q35740",
        "title": "Hurrian",
        "date": "1500 BCE",
        "startYear": -1500,
        "description": "language",
        "snippet": "language",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q1247524",
        "title": "founding of Rome",
        "date": "752 BCE",
        "startYear": -752,
        "description": "mythical tale",
        "snippet": "mythical tale",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q200716",
        "title": "Battle of Chaeronea",
        "date": "337 BCE",
        "startYear": -337,
        "description": "338 BCE battle during the expansion of Macedonia under Philip II",
        "snippet": "338 BCE battle during the expansion of Macedonia under Philip II",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q192938",
        "title": "Battle of the Granicus",
        "date": "333 BCE",
        "startYear": -333,
        "description": "334 BC battle between Macedonians and Persians",
        "snippet": "334 BC battle between Macedonians and Persians",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q207250",
        "title": "Battle of Lake Trasimene",
        "date": "216 BCE",
        "startYear": -216,
        "description": "217 BCE battle of the Second Punic War",
        "snippet": "217 BCE battle of the Second Punic War",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q203729",
        "title": "Battle of Kadesh",
        "date": "1273 BCE",
        "startYear": -1273,
        "description": "battle between Egyptians and Hittites fought in 1274 BCE",
        "snippet": "battle between Egyptians and Hittites fought in 1274 BCE",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q141118",
        "title": "Permian-Triassic mass extinction",
        "date": "251900000 BCE",
        "startYear": -251900000,
        "description": "mass extinction event at the end of the Permian Period approximately 250 million years ago",
        "snippet": "mass extinction event at the end of the Permian Period approximately 250 million years ago",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q174361",
        "title": "Book of the Dead",
        "date": "1274 BCE",
        "startYear": -1274,
        "description": "ancient Egyptian funerary text",
        "snippet": "ancient Egyptian funerary text",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q204636",
        "title": "Battle of Plataea",
        "date": "478 BCE",
        "startYear": -478,
        "description": "479 BCE land battle during the second Persian invasion of Greece",
        "snippet": "479 BCE land battle during the second Persian invasion of Greece",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q178850",
        "title": "Battle of Salamis",
        "date": "479 BCE",
        "startYear": -479,
        "description": "480 BCE naval battle fought between an alliance of Greek city-states and the Persian Empire",
        "snippet": "480 BCE naval battle fought between an alliance of Greek city-states and the Persian Empire",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q179670",
        "title": "Battle of Gaugamela",
        "date": "330 BCE",
        "startYear": -330,
        "description": "decisive battle of Alexander the Great's invasion of the Persian Achaemenid Empire",
        "snippet": "decisive battle of Alexander the Great's invasion of the Persian Achaemenid Empire",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q201526",
        "title": "Battle of Issus",
        "date": "332 BCE",
        "startYear": -332,
        "description": "second great battle of Alexander's conquest of Asia",
        "snippet": "second great battle of Alexander's conquest of Asia",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q179591",
        "title": "Battle of Cannae",
        "date": "215 BCE",
        "startYear": -215,
        "description": "major battle of the Second Punic War (216 BCE)",
        "snippet": "major battle of the Second Punic War (216 BCE)",
        "significance": 3,
        "gap": 150
    },
    {
        "id": "Q55811",
        "title": "Cretaceous-Paleogene mass extinction",
        "date": "66000000 BCE",
        "startYear": -66000000,
        "description": "extinction event ending the Mesozoic Era",
        "snippet": "extinction event ending the Mesozoic Era",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q35668",
        "title": "Hittite",
        "date": "1650 BCE",
        "startYear": -1650,
        "description": "extinct Bronze Age Indo-European language",
        "snippet": "extinct Bronze Age Indo-European language",
        "significance": 2,
        "gap": 150
    },
    {
        "id": "Q323",
        "title": "Big Bang",
        "date": "13787000000 BCE",
        "startYear": -13787000000,
        "description": "hypothetical begin of the Universe through expansion out of an infinitely small and infinitely dense state",
        "snippet": "hypothetical begin of the Universe through expansion out of an infinitely small and infinitely dense state",
        "significance": 1,
        "gap": 150
    },
    {
        "id": "Q31900",
        "title": "Battle of Marathon",
        "date": "489 BCE",
        "startYear": -489,
        "description": "490 BCE battle in the Greco-Persian wars",
        "snippet": "490 BCE battle in the Greco-Persian wars",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q131969",
        "title": "Battle of Thermopylae",
        "date": "479 BCE",
        "startYear": -479,
        "description": "battle of 480 BCE during Persian invasion of Greece",
        "snippet": "battle of 480 BCE during Persian invasion of Greece",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q33745",
        "title": "Peloponnesian War",
        "date": "430 BCE",
        "startYear": -430,
        "description": "war fought between Athens and Sparta (431–404 BCE)",
        "snippet": "war fought between Athens and Sparta (431–404 BCE)",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q6286",
        "title": "First Punic War",
        "date": "263 BCE",
        "startYear": -263,
        "description": "First War between Rome and Carthage",
        "snippet": "First War between Rome and Carthage",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q6271",
        "title": "Second Punic War",
        "date": "217 BCE",
        "startYear": -217,
        "description": "second war between the Roman Republic and Carthage, fought between 218 and 201 BCE",
        "snippet": "second war between the Roman Republic and Carthage, fought between 218 and 201 BCE",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q200056",
        "title": "Battle of Zama",
        "date": "201 BCE",
        "startYear": -201,
        "description": "final battle of the Second Punic War",
        "snippet": "final battle of the Second Punic War",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q6334",
        "title": "Third Punic War",
        "date": "148 BCE",
        "startYear": -148,
        "description": "war between the Roman Republic and Carthage between 149 and 146 BCE",
        "snippet": "war between the Roman Republic and Carthage between 149 and 146 BCE",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q194378",
        "title": "Third Servile War",
        "date": "72 BCE",
        "startYear": -72,
        "description": "major slave rebellion against the Roman Republic (73-71 BCE)",
        "snippet": "major slave rebellion against the Roman Republic (73-71 BCE)",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q202161",
        "title": "Gallic War",
        "date": "57 BCE",
        "startYear": -57,
        "description": "war (58–50 BCE) between the Roman Republic and Gaul",
        "snippet": "war (58–50 BCE) between the Roman Republic and Gaul",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q87779",
        "title": "Battle of the Teutoburg Forest",
        "date": "0009",
        "startYear": 9,
        "description": "battle between a coalition of Germanic peoples and an Imperial Roman army, 9 BCE",
        "snippet": "battle between a coalition of Germanic peoples and an Imperial Roman army, 9 BCE",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q139808",
        "title": "Battle of the Maureaco Fields",
        "date": "0451",
        "startYear": 297,
        "description": "battle between Romans and Huns in 451",
        "snippet": "battle between Romans and Huns in 451",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q486124",
        "title": "Battle of Badr",
        "date": "0624",
        "startYear": 404,
        "description": "624 battle between the Muslims and the Quraysh near Badr (present-day Saudi Arabia)",
        "snippet": "624 battle between the Muslims and the Quraysh near Badr (present-day Saudi Arabia)",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q488278",
        "title": "Battle of Uhud",
        "date": "0625",
        "startYear": 405,
        "description": "early Islamic battle",
        "snippet": "early Islamic battle",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q826083",
        "title": "Battle of the Trench",
        "date": "0627",
        "startYear": 407,
        "description": "failed besieging of early Muslims by Arab and Jewish forces in 627 CE",
        "snippet": "failed besieging of early Muslims by Arab and Jewish forces in 627 CE",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q887684",
        "title": "Muslim conquest of Persia",
        "date": "0633",
        "startYear": 411,
        "description": "historical event",
        "snippet": "historical event",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q194226",
        "title": "Battle of Yarmouk",
        "date": "0636",
        "startYear": 414,
        "description": "battle of the Arab–Byzantine wars",
        "snippet": "battle of the Arab–Byzantine wars",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q626058",
        "title": "Battle of Karbala",
        "date": "0680",
        "startYear": 680,
        "description": "battle in October 680 between the army of Ubayd Allah ibn Ziyad and al-Husayn ibn Ali",
        "snippet": "battle in October 680 between the army of Ubayd Allah ibn Ziyad and al-Husayn ibn Ali",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q173077",
        "title": "Battle of Tours",
        "date": "0732",
        "startYear": 474,
        "description": "battle fought in 732 by Merovingian Franks against the Umayyad Caliphate",
        "snippet": "battle fought in 732 by Merovingian Franks against the Umayyad Caliphate",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q83224",
        "title": "Battle of Hastings",
        "date": "1066",
        "startYear": 1066,
        "description": "battle which occurred on 14 October 1066",
        "snippet": "battle which occurred on 14 October 1066",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q203225",
        "title": "Battle of Stamford Bridge",
        "date": "1066",
        "startYear": 1066,
        "description": "1066 battle in the East Riding of Yorkshire, England, UK",
        "snippet": "1066 battle in the East Riding of Yorkshire, England, UK",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q200032",
        "title": "Battle of Manzikert",
        "date": "1071",
        "startYear": 1071,
        "description": "battle between the Byzantine Empire and Seljuq Turks in 1071",
        "snippet": "battle between the Byzantine Empire and Seljuq Turks in 1071",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q233568",
        "title": "Battle of Hattin",
        "date": "1187",
        "startYear": 1187,
        "description": "Victory of Saladin against Crusader states, 1187",
        "snippet": "Victory of Saladin against Crusader states, 1187",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q369560",
        "title": "Siege of Baghdad",
        "date": "1258",
        "startYear": 1258,
        "description": "1258 Mongol conquest of the Abbasid Caliphate",
        "snippet": "1258 Mongol conquest of the Abbasid Caliphate",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q222520",
        "title": "Battle of Bannockburn",
        "date": "1314",
        "startYear": 1314,
        "description": "1314 battle during the First War of Scottish Independence",
        "snippet": "1314 battle during the First War of Scottish Independence",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q12551",
        "title": "Hundred Years' War",
        "date": "1337",
        "startYear": 1337,
        "description": "series of conflicts and wars between England and France between 1337 and 1453",
        "snippet": "series of conflicts and wars between England and France between 1337 and 1453",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q27759",
        "title": "Battle of Crécy",
        "date": "1346",
        "startYear": 1346,
        "description": "1346 battle of the Hundred Years' War",
        "snippet": "1346 battle of the Hundred Years' War",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q210354",
        "title": "Battle of Kulikovo",
        "date": "1380",
        "startYear": 1380,
        "description": "1380 battle between Russian principalities and Golden Horde",
        "snippet": "1380 battle between Russian principalities and Golden Horde",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q179288",
        "title": "Battle of Kosovo",
        "date": "1389",
        "startYear": 1389,
        "description": "battle on 28th June 1389",
        "snippet": "battle on 28th June 1389",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q209387",
        "title": "Battle of Ankara",
        "date": "1402",
        "startYear": 1402,
        "description": "battle near Ankara on 20 July 1402, between the Timurid Empire and the Ottoman Sultanate",
        "snippet": "battle near Ankara on 20 July 1402, between the Timurid Empire and the Ottoman Sultanate",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q33570",
        "title": "Battle of Grunwald",
        "date": "1410",
        "startYear": 1410,
        "description": "1410 battle between the Teutonic Knights and Poland–Lithuania",
        "snippet": "1410 battle between the Teutonic Knights and Poland–Lithuania",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q188495",
        "title": "Battle of Agincourt",
        "date": "1415",
        "startYear": 1415,
        "description": "1415 English victory in the Hundred Years' War",
        "snippet": "1415 English victory in the Hundred Years' War",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q160077",
        "title": "Fall of Constantinople",
        "date": "1453",
        "startYear": 1453,
        "description": "1453 capture of the Byzantine capital by the Ottoman Empire",
        "snippet": "1453 capture of the Byzantine capital by the Ottoman Empire",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q127751",
        "title": "Wars of the Roses",
        "date": "1455",
        "startYear": 1455,
        "description": "dynastic civil war in England from 1455 to 1487",
        "snippet": "dynastic civil war in England from 1455 to 1487",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q178510",
        "title": "Battle of Mohács",
        "date": "1526",
        "startYear": 1526,
        "description": "1526 major battle in 16th-century Central Europe",
        "snippet": "1526 major battle in 16th-century Central Europe",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q246863",
        "title": "Livonian War",
        "date": "1558",
        "startYear": 1558,
        "description": "war in the Baltic region (1558-1583)",
        "snippet": "war in the Baltic region (1558-1583)",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q58732",
        "title": "Siege of Malta",
        "date": "1565",
        "startYear": 1565,
        "description": "Ottoman Empire's invasion of Malta in 1565",
        "snippet": "Ottoman Empire's invasion of Malta in 1565",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q80330",
        "title": "English Civil War",
        "date": "1642",
        "startYear": 1642,
        "description": "series of armed conflicts and political machinations between Parliamentarians and Royalists",
        "snippet": "series of armed conflicts and political machinations between Parliamentarians and Royalists",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q74623",
        "title": "Great Turkish War",
        "date": "1683",
        "startYear": 1683,
        "description": "series of conflicts (1683–1699) between the Ottoman Empire and the Holy League (Habsburg Empire, Poland-Lithuania, Venice, Russia), ending with the latter's victory",
        "snippet": "series of conflicts (1683–1699) between the Ottoman Empire and the Holy League (Habsburg Empire, P",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q200855",
        "title": "Battle of Vienna",
        "date": "1683",
        "startYear": 1683,
        "description": "battle near Vienna on 12 September 1683, between the Christian European states and the Ottomans, won by Christians commanded by Polish king John III Sobieski",
        "snippet": "battle near Vienna on 12 September 1683, between the Christian European states and the Ottomans, won",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q152218",
        "title": "Nine Years' War",
        "date": "1688",
        "startYear": 1688,
        "description": "war principally fought in Central Europe from 1688 to 1697",
        "snippet": "war principally fought in Central Europe from 1688 to 1697",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q151616",
        "title": "Great Northern War",
        "date": "1700",
        "startYear": 1700,
        "description": "conflict between anti-Swedish coalition Led by Russia and Swedish empires in 1700–1721",
        "snippet": "conflict between anti-Swedish coalition Led by Russia and Swedish empires in 1700–1721",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q152486",
        "title": "Battle of Poltava",
        "date": "1709",
        "startYear": 1709,
        "description": "decisive battle in the Great Northern War between Tsardom Russia and the Swedish Empire in 1709",
        "snippet": "decisive battle in the Great Northern War between Tsardom Russia and the Swedish Empire in 1709",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q32929",
        "title": "War of the Austrian Succession",
        "date": "1740",
        "startYear": 1740,
        "description": "1740–1748 war",
        "snippet": "1740–1748 war",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q154697",
        "title": "French and Indian War",
        "date": "1754",
        "startYear": 1754,
        "description": "North American theatre of the worldwide Seven Years' War",
        "snippet": "North American theatre of the worldwide Seven Years' War",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q33143",
        "title": "Seven Years' War",
        "date": "1756",
        "startYear": 1756,
        "description": "global war among European powers (1756–1763)",
        "snippet": "global war among European powers (1756–1763)",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q203233",
        "title": "Battle of Plassey",
        "date": "1757",
        "startYear": 1757,
        "description": "1757 battle which established the British Raj in India",
        "snippet": "1757 battle which established the British Raj in India",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q382116",
        "title": "Caucasian War",
        "date": "1763",
        "startYear": 1763,
        "description": "1763–1864 invasion of the Caucasus by the Russian Empire",
        "snippet": "1763–1864 invasion of the Caucasus by the Russian Empire",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q207318",
        "title": "French Revolutionary Wars",
        "date": "1792",
        "startYear": 1792,
        "description": "1792–1802 series of conflicts between the French Republic and several European monarchies",
        "snippet": "1792–1802 series of conflicts between the French Republic and several European monarchies",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q249232",
        "title": "War of the Third Coalition",
        "date": "1805",
        "startYear": 1805,
        "description": "1805–1806 conflict during the Napoleonic Wars",
        "snippet": "1805–1806 conflict during the Napoleonic Wars",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q134114",
        "title": "Battle of Austerlitz",
        "date": "1805",
        "startYear": 1805,
        "description": "1805 battle during the War of the Third Coalition",
        "snippet": "1805 battle during the War of the Third Coalition",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q26013",
        "title": "War of 1812",
        "date": "1812",
        "startYear": 1812,
        "description": "conflict between the United States and the British Empire from 1812 to 1815",
        "snippet": "conflict between the United States and the British Empire from 1812 to 1815",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q179250",
        "title": "French invasion of Russia",
        "date": "1812",
        "startYear": 1812,
        "description": "1812 conflict during the Napoleonic Wars",
        "snippet": "1812 conflict during the Napoleonic Wars",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q184320",
        "title": "Battle of Borodino",
        "date": "1812",
        "startYear": 1812,
        "description": "1812 battle during the French invasion of Russia",
        "snippet": "1812 battle during the French invasion of Russia",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q151005",
        "title": "Battle of Leipzig",
        "date": "1813",
        "startYear": 1813,
        "description": "huge and heavy battle during the War of the Sixth Coalition against Napoleon (1813)",
        "snippet": "huge and heavy battle during the War of the Sixth Coalition against Napoleon (1813)",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q48314",
        "title": "Battle of Waterloo",
        "date": "1815",
        "startYear": 1815,
        "description": "1815 battle during the War of the Seventh Coalition",
        "snippet": "1815 battle during the War of the Seventh Coalition",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q235344",
        "title": "Battle of the Alamo",
        "date": "1836",
        "startYear": 1836,
        "description": "1836 major battle of the Texas Revolution",
        "snippet": "1836 major battle of the Texas Revolution",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q191282",
        "title": "First Opium War",
        "date": "1839",
        "startYear": 1839,
        "description": "war between Great Britain and China in the 19th century",
        "snippet": "war between Great Britain and China in the 19th century",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q6683",
        "title": "Mexican-American War",
        "date": "1846",
        "startYear": 1846,
        "description": "military conflict between the United States of America and Mexico from 1846 to 1848",
        "snippet": "military conflict between the United States of America and Mexico from 1846 to 1848",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q254106",
        "title": "Crimean War",
        "date": "1853",
        "startYear": 1853,
        "description": "military conflict fought between October 1853 – March 1856",
        "snippet": "military conflict fought between October 1853 – March 1856",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q418151",
        "title": "Second Opium War",
        "date": "1856",
        "startYear": 1856,
        "description": "1856–1860 war between British–French forces and China",
        "snippet": "1856–1860 war between British–French forces and China",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q129864",
        "title": "Indian Mutiny of 1857",
        "date": "1857",
        "startYear": 1857,
        "description": "1857–58 uprising against British Company rule",
        "snippet": "1857–58 uprising against British Company rule",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q33132",
        "title": "Battle of Gettysburg",
        "date": "1863",
        "startYear": 1863,
        "description": "1863 battle of the American Civil War",
        "snippet": "1863 battle of the American Civil War",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q58947",
        "title": "Paraguayan War",
        "date": "1864",
        "startYear": 1864,
        "description": "large-scale conflict in South America (1864–1870)",
        "snippet": "large-scale conflict in South America (1864–1870)",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q153650",
        "title": "Austro-Prussian War",
        "date": "1866",
        "startYear": 1866,
        "description": "1866 military conflict between the Kingdom of Prussia and the Austrian Empire",
        "snippet": "1866 military conflict between the Kingdom of Prussia and the Austrian Empire",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q46083",
        "title": "Franco-Prussian War",
        "date": "1870",
        "startYear": 1870,
        "description": "1870–1871 military conflict of the Second French Empire versus Prussia and its allies",
        "snippet": "1870–1871 military conflict of the Second French Empire versus Prussia and its allies",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q152004",
        "title": "War of the Pacific",
        "date": "1879",
        "startYear": 1879,
        "description": "war between Chile and a Bolivian–Peruvian alliance",
        "snippet": "war between Chile and a Bolivian–Peruvian alliance",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q178687",
        "title": "First Sino-Japanese War",
        "date": "1894",
        "startYear": 1894,
        "description": "1894–1895 war between the Qing dynasty and the Empire of Japan over influence in Joseon, fought chiefly in Joseon",
        "snippet": "1894–1895 war between the Qing dynasty and the Empire of Japan over influence in Joseon, fought ch",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q12583",
        "title": "Spanish–American War",
        "date": "1898",
        "startYear": 1898,
        "description": "1898 conflict between Spain and the United States",
        "snippet": "1898 conflict between Spain and the United States",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q215112",
        "title": "Second Boer War",
        "date": "1899",
        "startYear": 1899,
        "description": "war between two Boer Republics (South African Republic and Orange Free State) and the United Kingdom",
        "snippet": "war between two Boer Republics (South African Republic and Orange Free State) and the United Kingdom",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q214456",
        "title": "Philippine–American War",
        "date": "1899",
        "startYear": 1899,
        "description": "armed conflict between the First Philippine Republic and the United States",
        "snippet": "armed conflict between the First Philippine Republic and the United States",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q150229",
        "title": "Boxer Rebellion",
        "date": "1899",
        "startYear": 1899,
        "description": "anti-imperialist uprising which took place in China 1899-1901",
        "snippet": "anti-imperialist uprising which took place in China 1899-1901",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q159950",
        "title": "Russo-Japanese War",
        "date": "1904",
        "startYear": 1904,
        "description": "conflict between the Russian and Japanese empires from 1904 to 1905",
        "snippet": "conflict between the Russian and Japanese empires from 1904 to 1905",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q203824",
        "title": "Italo-Turkish War",
        "date": "1911",
        "startYear": 1911,
        "description": "1911–12 war between the Ottoman Empire and the Kingdom of Italy",
        "snippet": "1911–12 war between the Ottoman Empire and the Kingdom of Italy",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q177918",
        "title": "First Balkan War",
        "date": "1912",
        "startYear": 1912,
        "description": "war involving the Balkan League and the Ottoman Empire",
        "snippet": "war involving the Balkan League and the Ottoman Empire",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q184183",
        "title": "Second Balkan War",
        "date": "1913",
        "startYear": 1913,
        "description": "continuation of the First Balkan War in which Bulgaria fought Serbia, Greece, Romania and the Ottoman Empire",
        "snippet": "continuation of the First Balkan War in which Bulgaria fought Serbia, Greece, Romania and the Ottoma",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q190712",
        "title": "First Battle of the Marne",
        "date": "1914",
        "startYear": 1914,
        "description": "1914 First World War battle",
        "snippet": "1914 First World War battle",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q153858",
        "title": "Battle of Tannenberg",
        "date": "1914",
        "startYear": 1914,
        "description": "1914 battle between Russia and Germany",
        "snippet": "1914 battle between Russia and Germany",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q130847",
        "title": "Battle of Verdun",
        "date": "1916",
        "startYear": 1916,
        "description": "1916 battle on the Western Front during the First World War",
        "snippet": "1916 battle on the Western Front during the First World War",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q132568",
        "title": "Battle of the Somme",
        "date": "1916",
        "startYear": 1916,
        "description": "battle of the Western Front, World War I",
        "snippet": "battle of the Western Front, World War I",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q186284",
        "title": "Polish–Soviet War",
        "date": "1919",
        "startYear": 1919,
        "description": "conflict between Poland and Soviet Russia following the First World War (February 1919 - March 1921)",
        "snippet": "conflict between Poland and Soviet Russia following the First World War (February 1919 - March 1921)",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q87138",
        "title": "Greco-Turkish War",
        "date": "1919",
        "startYear": 1919,
        "description": "war lasting from 1919 to 1922 during the Turkish War of Independence",
        "snippet": "war lasting from 1919 to 1922 during the Turkish War of Independence",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q94916",
        "title": "Second Italo-Ethiopian War",
        "date": "1935",
        "startYear": 1935,
        "description": "1935-1936 war between Italy and Ethiopia",
        "snippet": "1935-1936 war between Italy and Ethiopia",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q170314",
        "title": "Second Sino-Japanese War",
        "date": "1937",
        "startYear": 1937,
        "description": "Japanese invasion of China (1937–1945)",
        "snippet": "Japanese invasion of China (1937–1945)",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q134949",
        "title": "Winter War",
        "date": "1939",
        "startYear": 1939,
        "description": "1939–1940 war between the Soviet Union and Finland",
        "snippet": "1939–1940 war between the Soviet Union and Finland",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q190882",
        "title": "Phoney War",
        "date": "1939",
        "startYear": 1939,
        "description": "eight-month period at the start of World War II, during which there was only one limited military land operation on the Western Front",
        "snippet": "eight-month period at the start of World War II, during which there was only one limited military la",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q151340",
        "title": "Battle of France",
        "date": "1940",
        "startYear": 1940,
        "description": "Nazi German invasion of France in 1940",
        "snippet": "Nazi German invasion of France in 1940",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q208529",
        "title": "Battle of Dunkirk",
        "date": "1940",
        "startYear": 1940,
        "description": "1940 battle in the Second World War between the Allies and Germany",
        "snippet": "1940 battle in the Second World War between the Allies and Germany",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q189266",
        "title": "Eastern Front",
        "date": "1941",
        "startYear": 1941,
        "description": "1941–1945 World War II theater",
        "snippet": "1941–1945 World War II theater",
        "significance": 1,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q52418",
        "title": "Attack on Pearl Harbor",
        "date": "1941",
        "startYear": 1941,
        "description": "1941 Japanese surprise attack on the U.S",
        "snippet": "1941 Japanese surprise attack on the U.S",
        "significance": 1,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q151290",
        "title": "Battle of Moscow",
        "date": "1941",
        "startYear": 1941,
        "description": "1941 World War II campaign in Russia",
        "snippet": "1941 World War II campaign in Russia",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q38789",
        "title": "Battle of Stalingrad",
        "date": "1942",
        "startYear": 1942,
        "description": "1942 major battle of World War II",
        "snippet": "1942 major battle of World War II",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q130861",
        "title": "Battle of Kursk",
        "date": "1943",
        "startYear": 1943,
        "description": "World War II battle that took place in 1943",
        "snippet": "World War II battle that took place in 1943",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q154940",
        "title": "Lapland War",
        "date": "1944",
        "startYear": 1944,
        "description": "1944–1945 war between Finland and Germany",
        "snippet": "1944–1945 war between Finland and Germany",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q16470",
        "title": "Normandy landings",
        "date": "1944",
        "startYear": 1944,
        "description": "1944 landing operations of the Allied invasion of Normandy",
        "snippet": "1944 landing operations of the Allied invasion of Normandy",
        "significance": 1,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q154182",
        "title": "Battle of Berlin",
        "date": "1945",
        "startYear": 1945,
        "description": "1945 last major offensive of the European theatre of World War Il",
        "snippet": "1945 last major offensive of the European theatre of World War Il",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q180182",
        "title": "Battle of Iwo Jima",
        "date": "1945",
        "startYear": 1945,
        "description": "1945 major battle in which US Forces captured the island of Iwo Jima from Japan during World War II",
        "snippet": "1945 major battle in which US Forces captured the island of Iwo Jima from Japan during World War ",
        "significance": 1,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q192660",
        "title": "Battle of Okinawa",
        "date": "1945",
        "startYear": 1945,
        "description": "1945 major battle of the Pacific War",
        "snippet": "1945 major battle of the Pacific War",
        "significance": 1,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q748780",
        "title": "First Indochina War",
        "date": "1946",
        "startYear": 1946,
        "description": "1946–1954 French colonial war in Vietnam",
        "snippet": "1946–1954 French colonial war in Vietnam",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q49097",
        "title": "1948 Palestine war",
        "date": "1947",
        "startYear": 1947,
        "description": "first war of the Arab–Israeli conflict",
        "snippet": "first war of the Arab–Israeli conflict",
        "significance": 1,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q1413732",
        "title": "Kashmir conflict",
        "date": "1947",
        "startYear": 1947,
        "description": "Territoral dispute in South Asia",
        "snippet": "Territoral dispute in South Asia",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q8663",
        "title": "Korean War",
        "date": "1950",
        "startYear": 1950,
        "description": "war between North and South Korea, 1950–1953",
        "snippet": "war between North and South Korea, 1950–1953",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q604897",
        "title": "Battle of Dien Bien Phu",
        "date": "1954",
        "startYear": 1954,
        "description": "1954 battle of the First Indochina War",
        "snippet": "1954 battle of the First Indochina War",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q49101",
        "title": "Suez Crisis",
        "date": "1956",
        "startYear": 1956,
        "description": "1956 invasion of Egypt by Israel, the United Kingdom, and France",
        "snippet": "1956 invasion of Egypt by Israel, the United Kingdom, and France",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q208694",
        "title": "Sino-Indian War",
        "date": "1962",
        "startYear": 1962,
        "description": "1962 war between India and China",
        "snippet": "1962 war between India and China",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q233583",
        "title": "Indo-Pakistani War of 1965",
        "date": "1965",
        "startYear": 1965,
        "description": "1965 war over Kashmir",
        "snippet": "1965 war over Kashmir",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q49077",
        "title": "Six-Day War",
        "date": "1967",
        "startYear": 1967,
        "description": "1967 war between Israel and Egypt, Jordan, and Syria",
        "snippet": "1967 war between Israel and Egypt, Jordan, and Syria",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q371394",
        "title": "Bangladesh Liberation War",
        "date": "1971",
        "startYear": 1971,
        "description": "conflict that led to the independence of the majority-Bengali country",
        "snippet": "conflict that led to the independence of the majority-Bengali country",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q1922071",
        "title": "Indo-Pakistani War of 1971",
        "date": "1971",
        "startYear": 1971,
        "description": "1971 war between India and Pakistan along Bengladesh Liberation War",
        "snippet": "1971 war between India and Pakistan along Bengladesh Liberation War",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q49100",
        "title": "Yom Kippur War",
        "date": "1973",
        "startYear": 1973,
        "description": "October 1973 war between Egypt and Syria at one side and Israel on the other side",
        "snippet": "October 1973 war between Egypt and Syria at one side and Israel on the other side",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q83085",
        "title": "Soviet-Afghan War",
        "date": "1979",
        "startYear": 1979,
        "description": "1979–1989 war between the Soviet Union and Afghan insurgents",
        "snippet": "1979–1989 war between the Soviet Union and Afghan insurgents",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q623171",
        "title": "Sino-Vietnamese War",
        "date": "1979",
        "startYear": 1979,
        "description": "war between the People's Republic of China and Socialist Republic of Vietnam in 1979",
        "snippet": "war between the People's Republic of China and Socialist Republic of Vietnam in 1979",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q82664",
        "title": "Iran–Iraq War",
        "date": "1980",
        "startYear": 1980,
        "description": "1980-1988 war between Iran and Iraq",
        "snippet": "1980-1988 war between Iran and Iraq",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q48249",
        "title": "Falklands War",
        "date": "1982",
        "startYear": 1982,
        "description": "undeclared war between Argentina and the United Kingdom in 1982",
        "snippet": "undeclared war between Argentina and the United Kingdom in 1982",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q49103",
        "title": "1982 Lebanon War",
        "date": "1982",
        "startYear": 1982,
        "description": "Israeli invasion of Lebanon",
        "snippet": "Israeli invasion of Lebanon",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q381375",
        "title": "First Nagorno-Karabakh War",
        "date": "1988",
        "startYear": 1988,
        "description": "armed conflict that took place in the late 1980s to May 1994",
        "snippet": "armed conflict that took place in the late 1980s to May 1994",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q37643",
        "title": "Gulf War",
        "date": "1990",
        "startYear": 1990,
        "description": "1990–1991 conflict between Iraq and a 42-country coalition",
        "snippet": "1990–1991 conflict between Iraq and a 42-country coalition",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q734004",
        "title": "Black January",
        "date": "1990",
        "startYear": 1990,
        "description": "1990 massacre in Baku",
        "snippet": "1990 massacre in Baku",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q68969",
        "title": "Croatian War of Independence",
        "date": "1991",
        "startYear": 1991,
        "description": "war of independence fought from 1991 to 1995",
        "snippet": "war of independence fought from 1991 to 1995",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q56039",
        "title": "German reunification",
        "date": "1991",
        "startYear": 1991,
        "description": "process in 1990 in which the German Democratic Republic became part of the Federal Republic of Germany",
        "snippet": "process in 1990 in which the German Democratic Republic became part of the Federal Republic of Germa",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q29269",
        "title": "First Chechen War",
        "date": "1994",
        "startYear": 1994,
        "description": "war fought from 1994 to 1996 in Chechnya",
        "snippet": "war fought from 1994 to 1996 in Chechnya",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q190029",
        "title": "Kosovo War",
        "date": "1998",
        "startYear": 1998,
        "description": "late 1990s armed conflict in Kosovo",
        "snippet": "late 1990s armed conflict in Kosovo",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q120843",
        "title": "Second Chechen War",
        "date": "1999",
        "startYear": 1999,
        "description": "war in Chechnya",
        "snippet": "war in Chechnya",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q404517",
        "title": "Kargil War",
        "date": "1999",
        "startYear": 1999,
        "description": "1999 conflict between India and Pakistan",
        "snippet": "1999 conflict between India and Pakistan",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q182865",
        "title": "War in Afghanistan (2001–2021)",
        "date": "2001",
        "startYear": 2001,
        "description": "armed conflict between NATO countries and Afghanistan since 2001",
        "snippet": "armed conflict between NATO countries and Afghanistan since 2001",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q185729",
        "title": "war on terror",
        "date": "2001",
        "startYear": 2001,
        "description": "Military campaign started after September 11 attacks",
        "snippet": "Military campaign started after September 11 attacks",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q545449",
        "title": "Iraq War",
        "date": "2003",
        "startYear": 2003,
        "description": "2003–2011 war after an American-led invasion",
        "snippet": "2003–2011 war after an American-led invasion",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q190758",
        "title": "War in Darfur",
        "date": "2003",
        "startYear": 2003,
        "description": "major armed conflict in the Darfur region of Sudan that began in February 2003",
        "snippet": "major armed conflict in the Darfur region of Sudan that began in February 2003",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q49104",
        "title": "2006 Lebanon War",
        "date": "2006",
        "startYear": 2006,
        "description": "armed conflict primarily between Israel and Hezbollah",
        "snippet": "armed conflict primarily between Israel and Hezbollah",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q620735",
        "title": "Russo-Georgian War",
        "date": "2008",
        "startYear": 2008,
        "description": "2008 Russian invasion of Georgia",
        "snippet": "2008 Russian invasion of Georgia",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q170682",
        "title": "Gaza War (2008–2009)",
        "date": "2008",
        "startYear": 2008,
        "description": "December 2008–January 2009 armed conflict in the Gaza Strip",
        "snippet": "December 2008–January 2009 armed conflict in the Gaza Strip",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q15860072",
        "title": "Russo-Ukrainian war",
        "date": "2014",
        "startYear": 2014,
        "description": "armed conflict between Russia and Ukraine since 2014",
        "snippet": "armed conflict between Russia and Ukraine since 2014",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q99659280",
        "title": "Second Nagorno-Karabakh War",
        "date": "2020",
        "startYear": 2020,
        "description": "armed conflict in South Caucasus",
        "snippet": "armed conflict in South Caucasus",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q110999040",
        "title": "full-scale Russo-Ukrainian war",
        "date": "2022",
        "startYear": 2022,
        "description": "full-scale invasion of Ukraine by Russia starting on 24 February 2022, part of Russo-Ukrainian War",
        "snippet": "full-scale invasion of Ukraine by Russia starting on 24 February 2022, part of Russo-Ukrainian War",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q122962941",
        "title": "Gaza war",
        "date": "2023",
        "startYear": 2023,
        "description": "armed conflict around the Gaza Strip that started on 7 October 2023",
        "snippet": "armed conflict around the Gaza Strip that started on 7 October 2023",
        "significance": 2,
        "gap": 150,
        "source": "WIKIDATA"
    },
    {
        "id": "Q134900605",
        "title": "Twelve-Day War",
        "date": "2025",
        "startYear": 2025,
        "description": "2025 armed conflict in the Middle East",
        "snippet": "2025 armed conflict in the Middle East",
        "significance": 3,
        "gap": 150,
        "source": "WIKIDATA"
    }
];
