const wikidataMasterList = [
  {
    id: "Q323",
    title: "Big Bang",
    date: "13787000000 BCE",
    startYear: -13787000000,
    description: "hypothetical begin of the Universe through expansion out of an infinitely small and infinitely dense state",
    snippet: "hypothetical begin of the Universe through expansion out of an infinitely small and infinitely dense",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q333",
    title: "astronomy",
    date: "8000 BCE",
    startYear: -8000,
    description: "natural science studying celestial objects and phenomena in the cosmos",
    snippet: "natural science studying celestial objects and phenomena in the cosmos",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q203729",
    title: "Battle of Kadesh",
    date: "1273 BCE",
    startYear: -1273,
    description: "battle between Egyptians and Hittites fought in 1274 BCE",
    snippet: "battle between Egyptians and Hittites fought in 1274 BCE",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q42458",
    title: "Anaximander",
    date: "609 BCE",
    startYear: -609,
    description: "pre-Socratic Greek philosopher",
    snippet: "pre-Socratic Greek philosopher",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q10261",
    title: "Pythagoras",
    date: "582 BCE",
    startYear: -582,
    description: "Greek philosopher and mathematician (c. 570 – c. 495 BC)",
    snippet: "Greek philosopher and mathematician (c. 570 – c. 495 BC)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41155",
    title: "Heraclitus",
    date: "534 BCE",
    startYear: -534,
    description: "Greek philosopher (late 6th/early 5th-century BC)",
    snippet: "Greek philosopher (late 6th/early 5th-century BC)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q83041",
    title: "Anaxagoras",
    date: "499 BCE",
    startYear: -499,
    description: "5th-century BC Greek philosopher",
    snippet: "5th-century BC Greek philosopher",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q31900",
    title: "Battle of Marathon",
    date: "489 BCE",
    startYear: -489,
    description: "490 BCE battle in the Greco-Persian wars",
    snippet: "490 BCE battle in the Greco-Persian wars",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q131969",
    title: "Battle of Thermopylae",
    date: "479 BCE",
    startYear: -479,
    description: "battle of 480 BCE during Persian invasion of Greece",
    snippet: "battle of 480 BCE during Persian invasion of Greece",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q204636",
    title: "Battle of Plataea",
    date: "478 BCE",
    startYear: -478,
    description: "479 BCE land battle during the second Persian invasion of Greece",
    snippet: "479 BCE land battle during the second Persian invasion of Greece",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41980",
    title: "Democritus",
    date: "460 BCE",
    startYear: -460,
    description: "Greek philosopher (c. 460–c. 370 BC)",
    snippet: "Greek philosopher (c. 460–c. 370 BC)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q33745",
    title: "Peloponnesian War",
    date: "430 BCE",
    startYear: -430,
    description: "war fought between Athens and Sparta (431–404 BCE)",
    snippet: "war fought between Athens and Sparta (431–404 BCE)",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8747",
    title: "Euclid",
    date: "333 BCE",
    startYear: -333,
    description: "ancient Greek mathematician (fl. 300 BC)",
    snippet: "ancient Greek mathematician (fl. 300 BC)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q201526",
    title: "Battle of Issus",
    date: "332 BCE",
    startYear: -332,
    description: "second great battle of Alexander's conquest of Asia",
    snippet: "second great battle of Alexander's conquest of Asia",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q179670",
    title: "Battle of Gaugamela",
    date: "330 BCE",
    startYear: -330,
    description: "decisive battle of Alexander the Great's invasion of the Persian Achaemenid Empire",
    snippet: "decisive battle of Alexander the Great's invasion of the Persian Achaemenid Empire",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8739",
    title: "Archimedes",
    date: "286 BCE",
    startYear: -286,
    description: "Greek mathematician and physicist (c. 287 – c. 212 BC)",
    snippet: "Greek mathematician and physicist (c. 287 – c. 212 BC)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q43182",
    title: "Eratosthenes",
    date: "275 BCE",
    startYear: -275,
    description: "Greek mathematician, geographer, poet, astronomer, librarian and music theorist",
    snippet: "Greek mathematician, geographer, poet, astronomer, librarian and music theorist",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q6286",
    title: "First Punic War",
    date: "263 BCE",
    startYear: -263,
    description: "First War between Rome and Carthage",
    snippet: "First War between Rome and Carthage",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q6271",
    title: "Second Punic War",
    date: "217 BCE",
    startYear: -217,
    description: "second war between the Roman Republic and Carthage, fought between 218 and 201 BCE",
    snippet: "second war between the Roman Republic and Carthage, fought between 218 and 201 BCE",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q179591",
    title: "Battle of Cannae",
    date: "215 BCE",
    startYear: -215,
    description: "major battle of the Second Punic War (216 BCE)",
    snippet: "major battle of the Second Punic War (216 BCE)",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q200056",
    title: "Battle of Zama",
    date: "201 BCE",
    startYear: -201,
    description: "final battle of the Second Punic War",
    snippet: "final battle of the Second Punic War",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q6334",
    title: "Third Punic War",
    date: "148 BCE",
    startYear: -148,
    description: "war between the Roman Republic and Carthage between 149 and 146 BCE",
    snippet: "war between the Roman Republic and Carthage between 149 and 146 BCE",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9372",
    title: "Sima Qian",
    date: "144 BCE",
    startYear: -144,
    description: "2nd-century BCE Chinese historian and writer",
    snippet: "2nd-century BCE Chinese historian and writer",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q194378",
    title: "Third Servile War",
    date: "72 BCE",
    startYear: -72,
    description: "major slave rebellion against the Roman Republic (73-71 BCE)",
    snippet: "major slave rebellion against the Roman Republic (73-71 BCE)",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q202161",
    title: "Gallic War",
    date: "57 BCE",
    startYear: -57,
    description: "war (58–50 BCE) between the Roman Republic and Gaul",
    snippet: "war (58–50 BCE) between the Roman Republic and Gaul",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q87779",
    title: "Battle of the Teutoburg Forest",
    date: "0009",
    startYear: 0009,
    description: "battle between a coalition of Germanic peoples and an Imperial Roman army, 9 BCE",
    snippet: "battle between a coalition of Germanic peoples and an Imperial Roman army, 9 BCE",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q185117",
    title: "Justin Martyr",
    date: "0100",
    startYear: 0100,
    description: "2nd century CE Christian apologist and martyr",
    snippet: "2nd century CE Christian apologist and martyr",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q34943",
    title: "Ptolemy",
    date: "0100",
    startYear: 0100,
    description: "2nd-century Roman mathematician, astronomer, geographer",
    snippet: "2nd-century Roman mathematician, astronomer, geographer",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q11903",
    title: "Hypatia",
    date: "0360",
    startYear: 0360,
    description: "Greek Neoplatonist philosopher",
    snippet: "Greek Neoplatonist philosopher",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q139808",
    title: "Battle of the Maureaco Fields",
    date: "0451",
    startYear: 0451,
    description: "battle between Romans and Huns in 451",
    snippet: "battle between Romans and Huns in 451",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q202943",
    title: "Brahmagupta",
    date: "0598",
    startYear: 0598,
    description: "Indian mathematician and astronomer (c. 598 – c. 668 CE)",
    snippet: "Indian mathematician and astronomer (c. 598 – c. 668 CE)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q486124",
    title: "Battle of Badr",
    date: "0624",
    startYear: 0624,
    description: "624 battle between the Muslims and the Quraysh near Badr (present-day Saudi Arabia)",
    snippet: "624 battle between the Muslims and the Quraysh near Badr (present-day Saudi Arabia)",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q488278",
    title: "Battle of Uhud",
    date: "0625",
    startYear: 0625,
    description: "early Islamic battle",
    snippet: "early Islamic battle",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q826083",
    title: "Battle of the Trench",
    date: "0627",
    startYear: 0627,
    description: "failed besieging of early Muslims by Arab and Jewish forces in 627 CE",
    snippet: "failed besieging of early Muslims by Arab and Jewish forces in 627 CE",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q887684",
    title: "Muslim conquest of Persia",
    date: "0633",
    startYear: 0633,
    description: "historical event",
    snippet: "historical event",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q194226",
    title: "Battle of Yarmouk",
    date: "0636",
    startYear: 0636,
    description: "battle of the Arab–Byzantine wars",
    snippet: "battle of the Arab–Byzantine wars",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q626058",
    title: "Battle of Karbala",
    date: "0680",
    startYear: 0680,
    description: "battle in October 680 between the army of Ubayd Allah ibn Ziyad and al-Husayn ibn Ali",
    snippet: "battle in October 680 between the army of Ubayd Allah ibn Ziyad and al-Husayn ibn Ali",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q173077",
    title: "Battle of Tours",
    date: "0732",
    startYear: 0732,
    description: "battle fought in 732 by Merovingian Franks against the Umayyad Caliphate",
    snippet: "battle fought in 732 by Merovingian Franks against the Umayyad Caliphate",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9038",
    title: "Muḥammad ibn Musa al-Khwarizmi",
    date: "0780",
    startYear: 0780,
    description: "9th-century Persian mathematician and astronomer",
    snippet: "9th-century Persian mathematician and astronomer",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q11104",
    title: "Ibn al-Haytham",
    date: "0965",
    startYear: 0965,
    description: "Persian physicist, mathematician and astronomer (c. 965 – c. 1040)",
    snippet: "Persian physicist, mathematician and astronomer (c. 965 – c. 1040)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q11826",
    title: "Al-Biruni",
    date: "0973",
    startYear: 0973,
    description: "11th-century Persian scholar and polymath (973–1048)",
    snippet: "11th-century Persian scholar and polymath (973–1048)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8011",
    title: "Avicenna",
    date: "0980",
    startYear: 0980,
    description: "Persian polymath, physician and philosopher (c. 980–1037)",
    snippet: "Persian polymath, physician and philosopher (c. 980–1037)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q35900",
    title: "Omar Khayyám",
    date: "1048",
    startYear: 1048,
    description: "Persian mathematician and poet (1048–1131)",
    snippet: "Persian mathematician and poet (1048–1131)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q83224",
    title: "Battle of Hastings",
    date: "1066",
    startYear: 1066,
    description: "battle which occurred on 14 October 1066",
    snippet: "battle which occurred on 14 October 1066",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q203225",
    title: "Battle of Stamford Bridge",
    date: "1066",
    startYear: 1066,
    description: "1066 battle in the East Riding of Yorkshire, England, UK",
    snippet: "1066 battle in the East Riding of Yorkshire, England, UK",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q200032",
    title: "Battle of Manzikert",
    date: "1071",
    startYear: 1071,
    description: "battle between the Byzantine Empire and Seljuq Turks in 1071",
    snippet: "battle between the Byzantine Empire and Seljuq Turks in 1071",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q39837",
    title: "Averroes",
    date: "1126",
    startYear: 1126,
    description: "Arab Andalusian Muslim writer and philosopher (1126–1198)",
    snippet: "Arab Andalusian Muslim writer and philosopher (1126–1198)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q127398",
    title: "Moshe ben Maimon",
    date: "1138",
    startYear: 1138,
    description: "Medieval Jewish philosopher from Spain (1135–1204)",
    snippet: "Medieval Jewish philosopher from Spain (1135–1204)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8763",
    title: "Fibonacci",
    date: "1170",
    startYear: 1170,
    description: "Italian mathematician (c.1170–c.1240/50)",
    snippet: "Italian mathematician (c.1170–c.1240/50)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q233568",
    title: "Battle of Hattin",
    date: "1187",
    startYear: 1187,
    description: "Victory of Saladin against Crusader states, 1187",
    snippet: "Victory of Saladin against Crusader states, 1187",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q369560",
    title: "Siege of Baghdad",
    date: "1258",
    startYear: 1258,
    description: "1258 Mongol conquest of the Abbasid Caliphate",
    snippet: "1258 Mongol conquest of the Abbasid Caliphate",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q222520",
    title: "Battle of Bannockburn",
    date: "1314",
    startYear: 1314,
    description: "1314 battle during the First War of Scottish Independence",
    snippet: "1314 battle during the First War of Scottish Independence",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q12551",
    title: "Hundred Years' War",
    date: "1337",
    startYear: 1337,
    description: "series of conflicts and wars between England and France between 1337 and 1453",
    snippet: "series of conflicts and wars between England and France between 1337 and 1453",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q27759",
    title: "Battle of Crécy",
    date: "1346",
    startYear: 1346,
    description: "1346 battle of the Hundred Years' War",
    snippet: "1346 battle of the Hundred Years' War",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q210354",
    title: "Battle of Kulikovo",
    date: "1380",
    startYear: 1380,
    description: "1380 battle between Russian principalities and Golden Horde",
    snippet: "1380 battle between Russian principalities and Golden Horde",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q179288",
    title: "Battle of Kosovo",
    date: "1389",
    startYear: 1389,
    description: "battle on 28th June 1389",
    snippet: "battle on 28th June 1389",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q4692",
    title: "Renaissance",
    date: "1400",
    startYear: 1400,
    description: "cultural movement that spanned the period roughly from the 14th to the 17th century",
    snippet: "cultural movement that spanned the period roughly from the 14th to the 17th century",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8958",
    title: "Johannes Gutenberg",
    date: "1400",
    startYear: 1400,
    description: "German inventor and craftsman (1400-1468)",
    snippet: "German inventor and craftsman (1400-1468)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q209387",
    title: "Battle of Ankara",
    date: "1402",
    startYear: 1402,
    description: "battle near Ankara on 20 July 1402, between the Timurid Empire and the Ottoman Sultanate",
    snippet: "battle near Ankara on 20 July 1402, between the Timurid Empire and the Ottoman Sultanate",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q33570",
    title: "Battle of Grunwald",
    date: "1410",
    startYear: 1410,
    description: "1410 battle between the Teutonic Knights and Poland–Lithuania",
    snippet: "1410 battle between the Teutonic Knights and Poland–Lithuania",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q188495",
    title: "Battle of Agincourt",
    date: "1415",
    startYear: 1415,
    description: "1415 English victory in the Hundred Years' War",
    snippet: "1415 English victory in the Hundred Years' War",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7322",
    title: "Christopher Columbus",
    date: "1451",
    startYear: 1451,
    description: "Italian navigator, explorer, and colonist (1451–1506)",
    snippet: "Italian navigator, explorer, and colonist (1451–1506)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q762",
    title: "Leonardo da Vinci",
    date: "1452",
    startYear: 1452,
    description: "Italian Renaissance polymath (1452−1519)",
    snippet: "Italian Renaissance polymath (1452−1519)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q160077",
    title: "Fall of Constantinople",
    date: "1453",
    startYear: 1453,
    description: "1453 capture of the Byzantine capital by the Ottoman Empire",
    snippet: "1453 capture of the Byzantine capital by the Ottoman Empire",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q127751",
    title: "Wars of the Roses",
    date: "1455",
    startYear: 1455,
    description: "dynastic civil war in England from 1455 to 1487",
    snippet: "dynastic civil war in England from 1455 to 1487",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q5580",
    title: "Albrecht Dürer",
    date: "1471",
    startYear: 1471,
    description: "German painter, printmaker, mathematician, and theorist (1471–1528)",
    snippet: "German painter, printmaker, mathematician, and theorist (1471–1528)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q619",
    title: "Nicolaus Copernicus",
    date: "1473",
    startYear: 1473,
    description: "Polish mathematician and astronomer (1473–1543)",
    snippet: "Polish mathematician and astronomer (1473–1543)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7321",
    title: "Jacques Cartier",
    date: "1492",
    startYear: 1492,
    description: "Breton maritime explorer of North America (1491–1557)",
    snippet: "Breton maritime explorer of North America (1491–1557)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q83428",
    title: "Paracelsus",
    date: "1493",
    startYear: 1493,
    description: "Swiss physician, philosopher, theologian, and alchemist (c. 1493–1541)",
    snippet: "Swiss physician, philosopher, theologian, and alchemist (c. 1493–1541)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q39978",
    title: "Nostradamus",
    date: "1503",
    startYear: 1503,
    description: "French seer and astrologer (1503–1566)",
    snippet: "French seer and astrologer (1503–1566)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q178510",
    title: "Battle of Mohács",
    date: "1526",
    startYear: 1526,
    description: "1526 major battle in 16th-century Central Europe",
    snippet: "1526 major battle in 16th-century Central Europe",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q36620",
    title: "Tycho Brahe",
    date: "1546",
    startYear: 1546,
    description: "Danish astronomer and alchemist, 1546–1601",
    snippet: "Danish astronomer and alchemist, 1546–1601",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q36330",
    title: "Giordano Bruno",
    date: "1548",
    startYear: 1548,
    description: "Italian Dominican friar, philosopher and mathematician (1548–1600)",
    snippet: "Italian Dominican friar, philosopher and mathematician (1548–1600)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q246863",
    title: "Livonian War",
    date: "1558",
    startYear: 1558,
    description: "war in the Baltic region (1558-1583)",
    snippet: "war in the Baltic region (1558-1583)",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q37388",
    title: "Francis Bacon",
    date: "1561",
    startYear: 1561,
    description: "English philosopher and statesman (1561–1626)",
    snippet: "English philosopher and statesman (1561–1626)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q307",
    title: "Galileo Galilei",
    date: "1564",
    startYear: 1564,
    description: "Italian polymath (1564–1642)",
    snippet: "Italian polymath (1564–1642)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q58732",
    title: "Siege of Malta",
    date: "1565",
    startYear: 1565,
    description: "Ottoman Empire's invasion of Malta in 1565",
    snippet: "Ottoman Empire's invasion of Malta in 1565",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8963",
    title: "Johannes Kepler",
    date: "1572",
    startYear: 1572,
    description: "German mathematician and astronomer (1571–1630)",
    snippet: "German mathematician and astronomer (1571–1630)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q37621",
    title: "Thomas Hobbes",
    date: "1588",
    startYear: 1588,
    description: "English philosopher (1588–1679)",
    snippet: "English philosopher (1588–1679)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9191",
    title: "René Descartes",
    date: "1596",
    startYear: 1596,
    description: "French philosopher, mathematician, and scientist (1596–1650)",
    snippet: "French philosopher, mathematician, and scientist (1596–1650)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q75655",
    title: "Pierre de Fermat",
    date: "1607",
    startYear: 1607,
    description: "French mathematician and lawyer",
    snippet: "French mathematician and lawyer",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q1290",
    title: "Blaise Pascal",
    date: "1623",
    startYear: 1623,
    description: "French mathematician, physicist, inventor, writer, and Christian philosopher (1623–1662)",
    snippet: "French mathematician, physicist, inventor, writer, and Christian philosopher (1623–1662)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q43393",
    title: "Robert Boyle",
    date: "1627",
    startYear: 1627,
    description: "Anglo-Irish natural philosopher, chemist, physicist, and inventor",
    snippet: "Anglo-Irish natural philosopher, chemist, physicist, and inventor",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q39599",
    title: "Christiaan Huygens",
    date: "1629",
    startYear: 1629,
    description: "Dutch mathematician, physicist and astronomer (1629–1695)",
    snippet: "Dutch mathematician, physicist and astronomer (1629–1695)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9353",
    title: "John Locke",
    date: "1632",
    startYear: 1632,
    description: "English philosopher and physician (1632–1704)",
    snippet: "English philosopher and physician (1632–1704)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q43522",
    title: "Antonie van Leeuwenhoek",
    date: "1632",
    startYear: 1632,
    description: "Dutch scientist known as \",
    snippet: "Dutch scientist known as \",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q46830",
    title: "Robert Hooke",
    date: "1635",
    startYear: 1635,
    description: "English natural philosopher, architect and polymath (1635 — 1703)",
    snippet: "English natural philosopher, architect and polymath (1635 — 1703)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q80330",
    title: "English Civil War",
    date: "1642",
    startYear: 1642,
    description: "series of armed conflicts and political machinations between Parliamentarians and Royalists",
    snippet: "series of armed conflicts and political machinations between Parliamentarians and Royalists",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q935",
    title: "Isaac Newton",
    date: "1643",
    startYear: 1643,
    description: "English mathematician and physicist (1642–1727)",
    snippet: "English mathematician and physicist (1642–1727)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9047",
    title: "Gottfried Wilhelm Leibniz",
    date: "1646",
    startYear: 1646,
    description: "German mathematician and philosopher (1646–1716)",
    snippet: "German mathematician and philosopher (1646–1716)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q133100",
    title: "Innocent XIII",
    date: "1655",
    startYear: 1655,
    description: "pope of the Catholic Church from 1721 to 1724",
    snippet: "pope of the Catholic Church from 1721 to 1724",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q74623",
    title: "Great Turkish War",
    date: "1683",
    startYear: 1683,
    description: "series of conflicts (1683–1699) between the Ottoman Empire and the Holy League (Habsburg Empire, Poland-Lithuania, Venice, Russia), ending with the latter's victory",
    snippet: "series of conflicts (1683–1699) between the Ottoman Empire and the Holy League (Habsburg Empire, P",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q200855",
    title: "Battle of Vienna",
    date: "1683",
    startYear: 1683,
    description: "battle near Vienna on 12 September 1683, between the Christian European states and the Ottomans, won by Christians commanded by Polish king John III Sobieski",
    snippet: "battle near Vienna on 12 September 1683, between the Christian European states and the Ottomans, won",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q152218",
    title: "Nine Years' War",
    date: "1688",
    startYear: 1688,
    description: "war principally fought in Central Europe from 1688 to 1697",
    snippet: "war principally fought in Central Europe from 1688 to 1697",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q151616",
    title: "Great Northern War",
    date: "1700",
    startYear: 1700,
    description: "conflict between anti-Swedish coalition Led by Russia and Swedish empires in 1700–1721",
    snippet: "conflict between anti-Swedish coalition Led by Russia and Swedish empires in 1700–1721",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7604",
    title: "Leonhard Euler",
    date: "1707",
    startYear: 1707,
    description: "Swiss mathematician, physicist, and engineer (1707–1783)",
    snippet: "Swiss mathematician, physicist, and engineer (1707–1783)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q152486",
    title: "Battle of Poltava",
    date: "1709",
    startYear: 1709,
    description: "decisive battle in the Great Northern War between Tsardom Russia and the Swedish Empire in 1709",
    snippet: "decisive battle in the Great Northern War between Tsardom Russia and the Swedish Empire in 1709",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q58720",
    title: "Mikhail Lomonosov",
    date: "1711",
    startYear: 1711,
    description: "Russian polymath (1711-1765)",
    snippet: "Russian polymath (1711-1765)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q153232",
    title: "Jean Le Rond d'Alembert",
    date: "1717",
    startYear: 1717,
    description: "French mathematician, mechanician, physicist, philosopher and music theorist (1717–1783)",
    snippet: "French mathematician, mechanician, physicist, philosopher and music theorist (1717–1783)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9312",
    title: "Immanuel Kant",
    date: "1724",
    startYear: 1724,
    description: "German philosopher (1724–1804)",
    snippet: "German philosopher (1724–1804)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9041",
    title: "James Watt",
    date: "1736",
    startYear: 1736,
    description: "British engineer (1736–1819)",
    snippet: "British engineer (1736–1819)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q80222",
    title: "Joseph-Louis Lagrange",
    date: "1736",
    startYear: 1736,
    description: "Mathematician and astronomer (1736–1813)",
    snippet: "Mathematician and astronomer (1736–1813)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q14277",
    title: "William Herschel",
    date: "1738",
    startYear: 1738,
    description: "German-born British astronomer and composer (1738–1822)",
    snippet: "German-born British astronomer and composer (1738–1822)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q32929",
    title: "War of the Austrian Succession",
    date: "1740",
    startYear: 1740,
    description: "1740–1748 war",
    snippet: "1740–1748 war",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q11812",
    title: "Thomas Jefferson",
    date: "1743",
    startYear: 1743,
    description: "president of the United States from 1801 to 1809 (1743–1826)",
    snippet: "president of the United States from 1801 to 1809 (1743–1826)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q39607",
    title: "Antoine Lavoisier",
    date: "1743",
    startYear: 1743,
    description: "French nobleman and chemist (1743–1794)",
    snippet: "French nobleman and chemist (1743–1794)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q680",
    title: "Alessandro Volta",
    date: "1745",
    startYear: 1745,
    description: "Italian physicist, chemist, and pioneer of electricity and power (1745-1827)",
    snippet: "Italian physicist, chemist, and pioneer of electricity and power (1745-1827)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q5879",
    title: "Johann Wolfgang von Goethe",
    date: "1749",
    startYear: 1749,
    description: "German writer, artist, natural scientist and politician (1749–1832)",
    snippet: "German writer, artist, natural scientist and politician (1749–1832)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q44481",
    title: "Pierre-Simon Laplace",
    date: "1749",
    startYear: 1749,
    description: "French mathematician and astronomer (1749–1827)",
    snippet: "French mathematician and astronomer (1749–1827)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q154697",
    title: "French and Indian War",
    date: "1754",
    startYear: 1754,
    description: "North American theatre of the worldwide Seven Years' War",
    snippet: "North American theatre of the worldwide Seven Years' War",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q33143",
    title: "Seven Years' War",
    date: "1756",
    startYear: 1756,
    description: "global war among European powers (1756–1763)",
    snippet: "global war among European powers (1756–1763)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q203233",
    title: "Battle of Plassey",
    date: "1757",
    startYear: 1757,
    description: "1757 battle which established the British Raj in India",
    snippet: "1757 battle which established the British Raj in India",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q382116",
    title: "Caucasian War",
    date: "1763",
    startYear: 1763,
    description: "1763–1864 invasion of the Caucasus by the Russian Empire",
    snippet: "1763–1864 invasion of the Caucasus by the Russian Empire",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41284",
    title: "John Dalton",
    date: "1766",
    startYear: 1766,
    description: "British chemist and mathematician (1766–1844)",
    snippet: "British chemist and mathematician (1766–1844)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q13526",
    title: "Thomas Robert Malthus",
    date: "1766",
    startYear: 1766,
    description: "British political economist (1766–1834)",
    snippet: "British political economist (1766–1834)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8772",
    title: "Joseph Fourier",
    date: "1768",
    startYear: 1768,
    description: "French mathematician and physicist (1768 – 1830)",
    snippet: "French mathematician and physicist (1768 – 1830)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q6694",
    title: "Alexander von Humboldt",
    date: "1769",
    startYear: 1769,
    description: "Prussian geographer, naturalist and explorer (1769–1859)",
    snippet: "Prussian geographer, naturalist and explorer (1769–1859)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q675",
    title: "André-Marie Ampère",
    date: "1775",
    startYear: 1775,
    description: "French physicist and mathematician (1775–1836)",
    snippet: "French physicist and mathematician (1775–1836)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q6722",
    title: "Carl Friedrich Gauss",
    date: "1777",
    startYear: 1777,
    description: "German mathematician and physicist (1777–1855)",
    snippet: "German mathematician and physicist (1777–1855)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q131761",
    title: "Humphry Davy",
    date: "1778",
    startYear: 1778,
    description: "British chemist",
    snippet: "British chemist",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q6534",
    title: "French Revolution",
    date: "1789",
    startYear: 1789,
    description: "revolution in France from 1789 to 1799",
    snippet: "revolution in France from 1789 to 1799",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q1585",
    title: "Georg Simon Ohm",
    date: "1789",
    startYear: 1789,
    description: "German physicist and mathematician",
    snippet: "German physicist and mathematician",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8750",
    title: "Michael Faraday",
    date: "1791",
    startYear: 1791,
    description: "British scientist (1791–1867)",
    snippet: "British scientist (1791–1867)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q46633",
    title: "Charles Babbage",
    date: "1791",
    startYear: 1791,
    description: "English mathematician, philosopher, and engineer (1791–1871)",
    snippet: "English mathematician, philosopher, and engineer (1791–1871)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q207318",
    title: "French Revolutionary Wars",
    date: "1792",
    startYear: 1792,
    description: "1792–1802 series of conflicts between the French Republic and several European monarchies",
    snippet: "1792–1802 series of conflicts between the French Republic and several European monarchies",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q151403",
    title: "Thomas Carlyle",
    date: "1795",
    startYear: 1795,
    description: "Scottish essayist, historian and philosopher (1795–1881)",
    snippet: "Scottish essayist, historian and philosopher (1795–1881)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q12718",
    title: "Auguste Comte",
    date: "1798",
    startYear: 1798,
    description: "French philosopher, mathematician and sociologist (1798–1857)",
    snippet: "French philosopher, mathematician and sociologist (1798–1857)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q249232",
    title: "War of the Third Coalition",
    date: "1805",
    startYear: 1805,
    description: "1805–1806 conflict during the Napoleonic Wars",
    snippet: "1805–1806 conflict during the Napoleonic Wars",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q134114",
    title: "Battle of Austerlitz",
    date: "1805",
    startYear: 1805,
    description: "1805 battle during the War of the Third Coalition",
    snippet: "1805 battle during the War of the Third Coalition",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q26013",
    title: "War of 1812",
    date: "1812",
    startYear: 1812,
    description: "conflict between the United States and the British Empire from 1812 to 1815",
    snippet: "conflict between the United States and the British Empire from 1812 to 1815",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q179250",
    title: "French invasion of Russia",
    date: "1812",
    startYear: 1812,
    description: "1812 conflict during the Napoleonic Wars",
    snippet: "1812 conflict during the Napoleonic Wars",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q184320",
    title: "Battle of Borodino",
    date: "1812",
    startYear: 1812,
    description: "1812 battle during the French invasion of Russia",
    snippet: "1812 battle during the French invasion of Russia",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q151005",
    title: "Battle of Leipzig",
    date: "1813",
    startYear: 1813,
    description: "huge and heavy battle during the War of the Sixth Coalition against Napoleon (1813)",
    snippet: "huge and heavy battle during the War of the Sixth Coalition against Napoleon (1813)",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q48314",
    title: "Battle of Waterloo",
    date: "1815",
    startYear: 1815,
    description: "1815 battle during the War of the Seventh Coalition",
    snippet: "1815 battle during the War of the Seventh Coalition",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7259",
    title: "Ada Lovelace",
    date: "1815",
    startYear: 1815,
    description: "English mathematician (1815–1852)",
    snippet: "English mathematician (1815–1852)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8962",
    title: "James Prescott Joule",
    date: "1818",
    startYear: 1818,
    description: "English physicist and brewer (1818–1889)",
    snippet: "English physicist and brewer (1818–1889)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q37970",
    title: "Gregor Mendel",
    date: "1822",
    startYear: 1822,
    description: "Moravian scientist and Augustinian friar (1822–1884)",
    snippet: "Moravian scientist and Augustinian friar (1822–1884)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q160627",
    title: "Alfred Russel Wallace",
    date: "1823",
    startYear: 1823,
    description: "British naturalist, explorer, geographer, anthropologist and biologist (1823-1913)",
    snippet: "British naturalist, explorer, geographer, anthropologist and biologist (1823-1913)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q42299",
    title: "Bernhard Riemann",
    date: "1826",
    startYear: 1826,
    description: "German mathematician (1826–1866)",
    snippet: "German mathematician (1826–1866)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9095",
    title: "James Clerk Maxwell",
    date: "1831",
    startYear: 1831,
    description: "Scottish physicist (1831–1879)",
    snippet: "Scottish physicist (1831–1879)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q38082",
    title: "Lewis Carroll",
    date: "1832",
    startYear: 1832,
    description: "British author and scholar (1832–1898)",
    snippet: "British author and scholar (1832–1898)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q23810",
    title: "Alfred Nobel",
    date: "1833",
    startYear: 1833,
    description: "Swedish chemist and inventor (1833–1896)",
    snippet: "Swedish chemist and inventor (1833–1896)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9106",
    title: "Dmitri Mendeleev",
    date: "1834",
    startYear: 1834,
    description: "Russian chemist (1834–1907)",
    snippet: "Russian chemist (1834–1907)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q235344",
    title: "Battle of the Alamo",
    date: "1836",
    startYear: 1836,
    description: "1836 major battle of the Texas Revolution",
    snippet: "1836 major battle of the Texas Revolution",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q191282",
    title: "First Opium War",
    date: "1839",
    startYear: 1839,
    description: "war between Great Britain and China in the 19th century",
    snippet: "war between Great Britain and China in the 19th century",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q37193",
    title: "Robert Koch",
    date: "1843",
    startYear: 1843,
    description: "German physician, bacteriologist (1843–1910)",
    snippet: "German physician, bacteriologist (1843–1910)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q40224",
    title: "Carl Benz",
    date: "1844",
    startYear: 1844,
    description: "German automotive and engine designer and manufacturer (1844–1929)",
    snippet: "German automotive and engine designer and manufacturer (1844–1929)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q35149",
    title: "Wilhelm Röntgen",
    date: "1845",
    startYear: 1845,
    description: "German physicist (1845–1923)",
    snippet: "German physicist (1845–1923)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q76420",
    title: "Georg Cantor",
    date: "1845",
    startYear: 1845,
    description: "German mathematician, inventor of set theory (1845–1918)",
    snippet: "German mathematician, inventor of set theory (1845–1918)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q6683",
    title: "Mexican-American War",
    date: "1846",
    startYear: 1846,
    description: "military conflict between the United States of America and Mexico from 1846 to 1848",
    snippet: "military conflict between the United States of America and Mexico from 1846 to 1848",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8743",
    title: "Thomas Edison",
    date: "1847",
    startYear: 1847,
    description: "American inventor and businessman (1847–1931)",
    snippet: "American inventor and businessman (1847–1931)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q34286",
    title: "Alexander Graham Bell",
    date: "1847",
    startYear: 1847,
    description: "Canadian-American scientist inventor of telephone (1847–1922)",
    snippet: "Canadian-American scientist inventor of telephone (1847–1922)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41269",
    title: "Henri Becquerel",
    date: "1852",
    startYear: 1852,
    description: "French physicist (1852–1908)",
    snippet: "French physicist (1852–1908)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q127234",
    title: "Albert A. Michelson",
    date: "1852",
    startYear: 1852,
    description: "American physicist (1852–1931)",
    snippet: "American physicist (1852–1931)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q254106",
    title: "Crimean War",
    date: "1853",
    startYear: 1853,
    description: "military conflict fought between October 1853 – March 1856",
    snippet: "military conflict fought between October 1853 – March 1856",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41688",
    title: "Hendrik Lorentz",
    date: "1853",
    startYear: 1853,
    description: "Dutch physicist (1853–1928)",
    snippet: "Dutch physicist (1853–1928)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q81082",
    title: "Henri Poincaré",
    date: "1854",
    startYear: 1854,
    description: "French mathematician, physicist and engineer (1854–1912)",
    snippet: "French mathematician, physicist and engineer (1854–1912)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q418151",
    title: "Second Opium War",
    date: "1856",
    startYear: 1856,
    description: "1856–1860 war between British–French forces and China",
    snippet: "1856–1860 war between British–French forces and China",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9036",
    title: "Nikola Tesla",
    date: "1856",
    startYear: 1856,
    description: "Serbian-American engineer and inventor (1856–1943)",
    snippet: "Serbian-American engineer and inventor (1856–1943)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q47285",
    title: "J. J. Thomson",
    date: "1856",
    startYear: 1856,
    description: "British physicist (1856-1940)",
    snippet: "British physicist (1856-1940)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q129864",
    title: "Indian Mutiny of 1857",
    date: "1857",
    startYear: 1857,
    description: "1857–58 uprising against British Company rule",
    snippet: "1857–58 uprising against British Company rule",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41257",
    title: "Heinrich Hertz",
    date: "1857",
    startYear: 1857,
    description: "German physicist (1857–1894)",
    snippet: "German physicist (1857–1894)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41239",
    title: "Konstantin Tsiolkovsky",
    date: "1857",
    startYear: 1857,
    description: "Russian and Soviet rocket scientist and pioneer of the astronautic theory (1857-1935)",
    snippet: "Russian and Soviet rocket scientist and pioneer of the astronautic theory (1857-1935)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9021",
    title: "Max Planck",
    date: "1858",
    startYear: 1858,
    description: "German theoretical physicist (1858–1947)",
    snippet: "German theoretical physicist (1858–1947)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q11758",
    title: "L. L. Zamenhof",
    date: "1859",
    startYear: 1859,
    description: "Polish-Jewish physician and inventor of Esperanto (1859-1917)",
    snippet: "Polish-Jewish physician and inventor of Esperanto (1859-1917)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q37463",
    title: "Pierre Curie",
    date: "1859",
    startYear: 1859,
    description: "French physicist (1859–1906)",
    snippet: "French physicist (1859–1906)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q80956",
    title: "Svante August Arrhenius",
    date: "1859",
    startYear: 1859,
    description: "Swedish astronomer, chemist and physicist (1859–1927)",
    snippet: "Swedish astronomer, chemist and physicist (1859–1927)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41585",
    title: "David Hilbert",
    date: "1862",
    startYear: 1862,
    description: "German mathematician (1862–1943)",
    snippet: "German mathematician (1862–1943)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q133747",
    title: "William Henry Bragg",
    date: "1862",
    startYear: 1862,
    description: "British scientist (1862–1942)",
    snippet: "British scientist (1862–1942)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q33132",
    title: "Battle of Gettysburg",
    date: "1863",
    startYear: 1863,
    description: "1863 battle of the American Civil War",
    snippet: "1863 battle of the American Civil War",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8768",
    title: "Henry Ford",
    date: "1863",
    startYear: 1863,
    description: "American business magnate (1863–1947)",
    snippet: "American business magnate (1863–1947)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q58947",
    title: "Paraguayan War",
    date: "1864",
    startYear: 1864,
    description: "large-scale conflict in South America (1864–1870)",
    snippet: "large-scale conflict in South America (1864–1870)",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q79000",
    title: "Pieter Zeeman",
    date: "1865",
    startYear: 1865,
    description: "Dutch physicist (1865–1943)",
    snippet: "Dutch physicist (1865–1943)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q153650",
    title: "Austro-Prussian War",
    date: "1866",
    startYear: 1866,
    description: "1866 military conflict between the Kingdom of Prussia and the Austrian Empire",
    snippet: "1866 military conflict between the Kingdom of Prussia and the Austrian Empire",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7186",
    title: "Marie Curie",
    date: "1867",
    startYear: 1867,
    description: "Polish-French physicist and chemist (1867–1934)",
    snippet: "Polish-French physicist and chemist (1867–1934)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q130975",
    title: "Robert A. Millikan",
    date: "1868",
    startYear: 1868,
    description: "American physicist (1868–1953)",
    snippet: "American physicist (1868–1953)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q1001",
    title: "Mahatma Gandhi",
    date: "1869",
    startYear: 1869,
    description: "Indian independence activist (1869–1948)",
    snippet: "Indian independence activist (1869–1948)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q46083",
    title: "Franco-Prussian War",
    date: "1870",
    startYear: 1870,
    description: "1870–1871 military conflict of the Second French Empire versus Prussia and its allies",
    snippet: "1870–1871 military conflict of the Second French Empire versus Prussia and its allies",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9123",
    title: "Ernest Rutherford",
    date: "1871",
    startYear: 1871,
    description: "New Zealand physicist (1871–1937)",
    snippet: "New Zealand physicist (1871–1937)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q33760",
    title: "Bertrand Russell",
    date: "1872",
    startYear: 1872,
    description: "British philosopher and logician (1872–1970)",
    snippet: "British philosopher and logician (1872–1970)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q36488",
    title: "Guglielmo Marconi",
    date: "1874",
    startYear: 1874,
    description: "Italian inventor and radio pioneer (1874-1937)",
    snippet: "Italian inventor and radio pioneer (1874-1937)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q152004",
    title: "War of the Pacific",
    date: "1879",
    startYear: 1879,
    description: "war between Chile and a Bolivian–Peruvian alliance",
    snippet: "war between Chile and a Bolivian–Peruvian alliance",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q937",
    title: "Albert Einstein",
    date: "1879",
    startYear: 1879,
    description: "German-born theoretical physicist (1879–1955)",
    snippet: "German-born theoretical physicist (1879–1955)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q37064",
    title: "Alexander Fleming",
    date: "1881",
    startYear: 1881,
    description: "Scottish biologist, pharmacologist, botanist, and Nobel laureate (1881–1955)",
    snippet: "Scottish biologist, pharmacologist, botanist, and Nobel laureate (1881–1955)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q58978",
    title: "Max Born",
    date: "1882",
    startYear: 1882,
    description: "German-Jewish physicist and mathematician (1882-1970)",
    snippet: "German-Jewish physicist and mathematician (1882-1970)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q103986",
    title: "Gerhard Dammann",
    date: "1883",
    startYear: 1883,
    description: "German actor (1883–1946)",
    snippet: "German actor (1883–1946)",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9317",
    title: "John Maynard Keynes",
    date: "1883",
    startYear: 1883,
    description: "British economist (1883–1946)",
    snippet: "British economist (1883–1946)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7085",
    title: "Niels Bohr",
    date: "1885",
    startYear: 1885,
    description: "Danish physicist (1885–1962)",
    snippet: "Danish physicist (1885–1962)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9130",
    title: "Erwin Schrödinger",
    date: "1887",
    startYear: 1887,
    description: "Austrian physicist (1887–1961)",
    snippet: "Austrian physicist (1887–1961)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q83163",
    title: "Srinivasa Ramanujan",
    date: "1887",
    startYear: 1887,
    description: "Indian mathematician (1887–1920)",
    snippet: "Indian mathematician (1887–1920)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q60429",
    title: "Chandrasekhara Venkata Raman",
    date: "1888",
    startYear: 1888,
    description: "Indian physicist (1888–1970)",
    snippet: "Indian physicist (1888–1970)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q9391",
    title: "Ludwig Wittgenstein",
    date: "1889",
    startYear: 1889,
    description: "Austrian philosopher and logician (1889–1951)",
    snippet: "Austrian philosopher and logician (1889–1951)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q48301",
    title: "Martin Heidegger",
    date: "1889",
    startYear: 1889,
    description: "German philosopher (1889–1976)",
    snippet: "German philosopher (1889–1976)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q43027",
    title: "Edwin Hubble",
    date: "1889",
    startYear: 1889,
    description: "American astronomer (1889–1953)",
    snippet: "American astronomer (1889–1953)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q178687",
    title: "First Sino-Japanese War",
    date: "1894",
    startYear: 1894,
    description: "1894–1895 war between the Qing dynasty and the Empire of Japan over influence in Joseon, fought chiefly in Joseon",
    snippet: "1894–1895 war between the Qing dynasty and the Empire of Japan over influence in Joseon, fought ch",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7504",
    title: "Irène Joliot-Curie",
    date: "1897",
    startYear: 1897,
    description: "French scientist (1897–1956)",
    snippet: "French scientist (1897–1956)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q12583",
    title: "Spanish–American War",
    date: "1898",
    startYear: 1898,
    description: "1898 conflict between Spain and the United States",
    snippet: "1898 conflict between Spain and the United States",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8003",
    title: "Sergei Eisenstein",
    date: "1898",
    startYear: 1898,
    description: "Soviet filmmaker (1898–1948)",
    snippet: "Soviet filmmaker (1898–1948)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q215112",
    title: "Second Boer War",
    date: "1899",
    startYear: 1899,
    description: "war between two Boer Republics (South African Republic and Orange Free State) and the United Kingdom",
    snippet: "war between two Boer Republics (South African Republic and Orange Free State) and the United Kingdom",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q214456",
    title: "Philippine–American War",
    date: "1899",
    startYear: 1899,
    description: "armed conflict between the First Philippine Republic and the United States",
    snippet: "armed conflict between the First Philippine Republic and the United States",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q150229",
    title: "Boxer Rebellion",
    date: "1899",
    startYear: 1899,
    description: "anti-imperialist uprising which took place in China 1899-1901",
    snippet: "anti-imperialist uprising which took place in China 1899-1901",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q2908",
    title: "Antoine de Saint-Exupéry",
    date: "1900",
    startYear: 1900,
    description: "French writer and aviator (1900–1944)",
    snippet: "French writer and aviator (1900–1944)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8704",
    title: "Walt Disney",
    date: "1901",
    startYear: 1901,
    description: "American animator, producer, director, screenwriter, voice actor and entrepreneur, founder of The Walt Disney Company (1901–1966)",
    snippet: "American animator, producer, director, screenwriter, voice actor and entrepreneur, founder of The Wa",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8753",
    title: "Enrico Fermi",
    date: "1901",
    startYear: 1901,
    description: "Italian–American physicist (1901–1954)",
    snippet: "Italian–American physicist (1901–1954)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q48983",
    title: "Linus Pauling",
    date: "1901",
    startYear: 1901,
    description: "American scientist (1901–1994)",
    snippet: "American scientist (1901–1994)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q81244",
    title: "Karl Popper",
    date: "1902",
    startYear: 1902,
    description: "Austrian-British philosopher of science and social and política e falsificationism and for criticism of Plato, Hegel and Marx as totalitarian opponents of open society (1902-1994)",
    snippet: "Austrian-British philosopher of science and social and política e falsificationism and for criticis",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q47480",
    title: "Paul Dirac",
    date: "1902",
    startYear: 1902,
    description: "British theoretical physicist (1902–1984)",
    snippet: "British theoretical physicist (1902–1984)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q17455",
    title: "John von Neumann",
    date: "1903",
    startYear: 1903,
    description: "Hungarian and American mathematician and physicist (1903–1957)",
    snippet: "Hungarian and American mathematician and physicist (1903–1957)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q159950",
    title: "Russo-Japanese War",
    date: "1904",
    startYear: 1904,
    description: "conflict between the Russian and Japanese empires from 1904 to 1905",
    snippet: "conflict between the Russian and Japanese empires from 1904 to 1905",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q132537",
    title: "Robert Oppenheimer",
    date: "1904",
    startYear: 1904,
    description: "American theoretical physicist, known as \",
    snippet: "American theoretical physicist, known as \",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41390",
    title: "Kurt Gödel",
    date: "1906",
    startYear: 1906,
    description: "Austrian-American logician, mathematician, and philosopher of mathematics (1906-1978)",
    snippet: "Austrian-American logician, mathematician, and philosopher of mathematics (1906-1978)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q57100",
    title: "Maria Goeppert Mayer",
    date: "1906",
    startYear: 1906,
    description: "German-born American theoretical physicist (1906-1972)",
    snippet: "German-born American theoretical physicist (1906-1972)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q185007",
    title: "Rita Levi-Montalcini",
    date: "1909",
    startYear: 1909,
    description: "Italian neurologist (1909–2012)",
    snippet: "Italian neurologist (1909–2012)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7487",
    title: "Dorothy Hodgkin",
    date: "1910",
    startYear: 1910,
    description: "British chemist",
    snippet: "British chemist",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q203824",
    title: "Italo-Turkish War",
    date: "1911",
    startYear: 1911,
    description: "1911–12 war between the Ottoman Empire and the Kingdom of Italy",
    snippet: "1911–12 war between the Ottoman Empire and the Kingdom of Italy",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q177918",
    title: "First Balkan War",
    date: "1912",
    startYear: 1912,
    description: "war involving the Balkan League and the Ottoman Empire",
    snippet: "war involving the Balkan League and the Ottoman Empire",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q57384",
    title: "Wernher von Braun",
    date: "1912",
    startYear: 1912,
    description: "German and later American aerospace engineer and space architect (1912–1977)",
    snippet: "German and later American aerospace engineer and space architect (1912–1977)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q184183",
    title: "Second Balkan War",
    date: "1913",
    startYear: 1913,
    description: "continuation of the First Balkan War in which Bulgaria fought Serbia, Greece, Romania and the Ottoman Empire",
    snippet: "continuation of the First Balkan War in which Bulgaria fought Serbia, Greece, Romania and the Ottoma",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q190712",
    title: "First Battle of the Marne",
    date: "1914",
    startYear: 1914,
    description: "1914 First World War battle",
    snippet: "1914 First World War battle",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q153858",
    title: "Battle of Tannenberg",
    date: "1914",
    startYear: 1914,
    description: "1914 battle between Russia and Germany",
    snippet: "1914 battle between Russia and Germany",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q130847",
    title: "Battle of Verdun",
    date: "1916",
    startYear: 1916,
    description: "1916 battle on the Western Front during the First World War",
    snippet: "1916 battle on the Western Front during the First World War",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q132568",
    title: "Battle of the Somme",
    date: "1916",
    startYear: 1916,
    description: "battle of the Western Front, World War I",
    snippet: "battle of the Western Front, World War I",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q47087",
    title: "Arthur C. Clarke",
    date: "1917",
    startYear: 1917,
    description: "British science fiction writer, inventor, and futurist (1917–2008)",
    snippet: "British science fiction writer, inventor, and futurist (1917–2008)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q39246",
    title: "Richard Feynman",
    date: "1918",
    startYear: 1918,
    description: "American theoretical physicist (1918–1988)",
    snippet: "American theoretical physicist (1918–1988)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q186284",
    title: "Polish–Soviet War",
    date: "1919",
    startYear: 1919,
    description: "conflict between Poland and Soviet Russia following the First World War (February 1919 - March 1921)",
    snippet: "conflict between Poland and Soviet Russia following the First World War (February 1919 - March 1921)",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q87138",
    title: "Greco-Turkish War",
    date: "1919",
    startYear: 1919,
    description: "war lasting from 1919 to 1922 during the Turkish War of Independence",
    snippet: "war lasting from 1919 to 1922 during the Turkish War of Independence",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7474",
    title: "Rosalind Franklin",
    date: "1920",
    startYear: 1920,
    description: "British chemist, biophysicist, and X-ray crystallographer (1920–1958)",
    snippet: "British chemist, biophysicist, and X-ray crystallographer (1920–1958)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q997",
    title: "Andrei Sakharov",
    date: "1921",
    startYear: 1921,
    description: "Soviet nuclear physicist and human rights activist (1921–1989)",
    snippet: "Soviet nuclear physicist and human rights activist (1921–1989)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q83333",
    title: "James Watson",
    date: "1928",
    startYear: 1928,
    description: "American molecular biologist, geneticist, zoologist and Nobel Laureate (1928–2025)",
    snippet: "American molecular biologist, geneticist, zoologist and Nobel Laureate (1928–2025)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q128736",
    title: "John Forbes Nash",
    date: "1928",
    startYear: 1928,
    description: "American mathematician and economist (1928–2015)",
    snippet: "American mathematician and economist (1928–2015)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q410",
    title: "Carl Sagan",
    date: "1934",
    startYear: 1934,
    description: "American astrophysicist, cosmologist and author (1934–1996)",
    snippet: "American astrophysicist, cosmologist and author (1934–1996)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q94916",
    title: "Second Italo-Ethiopian War",
    date: "1935",
    startYear: 1935,
    description: "1935-1936 war between Italy and Ethiopia",
    snippet: "1935-1936 war between Italy and Ethiopia",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q170314",
    title: "Second Sino-Japanese War",
    date: "1937",
    startYear: 1937,
    description: "Japanese invasion of China (1937–1945)",
    snippet: "Japanese invasion of China (1937–1945)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q134949",
    title: "Winter War",
    date: "1939",
    startYear: 1939,
    description: "1939–1940 war between the Soviet Union and Finland",
    snippet: "1939–1940 war between the Soviet Union and Finland",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q190882",
    title: "Phoney War",
    date: "1939",
    startYear: 1939,
    description: "eight-month period at the start of World War II, during which there was only one limited military land operation on the Western Front",
    snippet: "eight-month period at the start of World War II, during which there was only one limited military la",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q183492",
    title: "Margaret Atwood",
    date: "1939",
    startYear: 1939,
    description: "Canadian poet, novelist, literary critic, essayist, teacher, environmental activist, pépiniériste and inventor (born 1939)",
    snippet: "Canadian poet, novelist, literary critic, essayist, teacher, environmental activist, pépiniériste ",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q151340",
    title: "Battle of France",
    date: "1940",
    startYear: 1940,
    description: "Nazi German invasion of France in 1940",
    snippet: "Nazi German invasion of France in 1940",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q208529",
    title: "Battle of Dunkirk",
    date: "1940",
    startYear: 1940,
    description: "1940 battle in the Second World War between the Allies and Germany",
    snippet: "1940 battle in the Second World War between the Allies and Germany",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q189266",
    title: "Eastern Front",
    date: "1941",
    startYear: 1941,
    description: "1941–1945 World War II theater",
    snippet: "1941–1945 World War II theater",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q52418",
    title: "Attack on Pearl Harbor",
    date: "1941",
    startYear: 1941,
    description: "1941 Japanese surprise attack on the U.S",
    snippet: "1941 Japanese surprise attack on the U.S",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q151290",
    title: "Battle of Moscow",
    date: "1941",
    startYear: 1941,
    description: "1941 World War II campaign in Russia",
    snippet: "1941 World War II campaign in Russia",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q38789",
    title: "Battle of Stalingrad",
    date: "1942",
    startYear: 1942,
    description: "1942 major battle of World War II",
    snippet: "1942 major battle of World War II",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q130861",
    title: "Battle of Kursk",
    date: "1943",
    startYear: 1943,
    description: "World War II battle that took place in 1943",
    snippet: "World War II battle that took place in 1943",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q41314",
    title: "Bobby Fischer",
    date: "1943",
    startYear: 1943,
    description: "American chess player (1943–2008)",
    snippet: "American chess player (1943–2008)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q154940",
    title: "Lapland War",
    date: "1944",
    startYear: 1944,
    description: "1944–1945 war between Finland and Germany",
    snippet: "1944–1945 war between Finland and Germany",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q16470",
    title: "Normandy landings",
    date: "1944",
    startYear: 1944,
    description: "1944 landing operations of the Allied invasion of Normandy",
    snippet: "1944 landing operations of the Allied invasion of Normandy",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q154182",
    title: "Battle of Berlin",
    date: "1945",
    startYear: 1945,
    description: "1945 last major offensive of the European theatre of World War Il",
    snippet: "1945 last major offensive of the European theatre of World War Il",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q180182",
    title: "Battle of Iwo Jima",
    date: "1945",
    startYear: 1945,
    description: "1945 major battle in which US Forces captured the island of Iwo Jima from Japan during World War II",
    snippet: "1945 major battle in which US Forces captured the island of Iwo Jima from Japan during World War ",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q192660",
    title: "Battle of Okinawa",
    date: "1945",
    startYear: 1945,
    description: "1945 major battle of the Pacific War",
    snippet: "1945 major battle of the Pacific War",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q748780",
    title: "First Indochina War",
    date: "1946",
    startYear: 1946,
    description: "1946–1954 French colonial war in Vietnam",
    snippet: "1946–1954 French colonial war in Vietnam",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q49097",
    title: "1948 Palestine war",
    date: "1947",
    startYear: 1947,
    description: "first war of the Arab–Israeli conflict",
    snippet: "first war of the Arab–Israeli conflict",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q1413732",
    title: "Kashmir conflict",
    date: "1947",
    startYear: 1947,
    description: "Territoral dispute in South Asia",
    snippet: "Territoral dispute in South Asia",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q8663",
    title: "Korean War",
    date: "1950",
    startYear: 1950,
    description: "war between North and South Korea, 1950–1953",
    snippet: "war between North and South Korea, 1950–1953",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q483382",
    title: "Steve Wozniak",
    date: "1950",
    startYear: 1950,
    description: "American computer pioneer, inventor, computer engineer and programmer; co-founder of Apple Inc.",
    snippet: "American computer pioneer, inventor, computer engineer and programmer; co-founder of Apple Inc.",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q7439",
    title: "Richard Stallman",
    date: "1953",
    startYear: 1953,
    description: "American software freedom activist, short story writer and computer programmer, founder of the GNU project",
    snippet: "American software freedom activist, short story writer and computer programmer, founder of the GNU p",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q604897",
    title: "Battle of Dien Bien Phu",
    date: "1954",
    startYear: 1954,
    description: "1954 battle of the First Indochina War",
    snippet: "1954 battle of the First Indochina War",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q567",
    title: "Angela Merkel",
    date: "1954",
    startYear: 1954,
    description: "chancellor of Germany from 2005 to 2021",
    snippet: "chancellor of Germany from 2005 to 2021",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q42574",
    title: "James Cameron",
    date: "1954",
    startYear: 1954,
    description: "Canadian and New-Zealander filmmaker (born 1954)",
    snippet: "Canadian and New-Zealander filmmaker (born 1954)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q19837",
    title: "Steve Jobs",
    date: "1955",
    startYear: 1955,
    description: "American entrepreneur; co-founder of Apple Inc. (1955–2011)",
    snippet: "American entrepreneur; co-founder of Apple Inc. (1955–2011)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q6109517",
    title: "Leo XIV",
    date: "1955",
    startYear: 1955,
    description: "267th Pope of the Catholic Church (2025–)",
    snippet: "267th Pope of the Catholic Church (2025–)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q80",
    title: "Tim Berners-Lee",
    date: "1955",
    startYear: 1955,
    description: "English computer scientist (born 1955)",
    snippet: "English computer scientist (born 1955)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q49101",
    title: "Suez Crisis",
    date: "1956",
    startYear: 1956,
    description: "1956 invasion of Egypt by Israel, the United Kingdom, and France",
    snippet: "1956 invasion of Egypt by Israel, the United Kingdom, and France",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q208694",
    title: "Sino-Indian War",
    date: "1962",
    startYear: 1962,
    description: "1962 war between India and China",
    snippet: "1962 war between India and China",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q193484",
    title: "assassination of John F. Kennedy",
    date: "1963",
    startYear: 1963,
    description: "1963 murder in Dallas, Texas, U.S",
    snippet: "1963 murder in Dallas, Texas, U.S",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q233583",
    title: "Indo-Pakistani War of 1965",
    date: "1965",
    startYear: 1965,
    description: "1965 war over Kashmir",
    snippet: "1965 war over Kashmir",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q49077",
    title: "Six-Day War",
    date: "1967",
    startYear: 1967,
    description: "1967 war between Israel and Egypt, Jordan, and Syria",
    snippet: "1967 war between Israel and Egypt, Jordan, and Syria",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q34253",
    title: "Linus Torvalds",
    date: "1969",
    startYear: 1969,
    description: "Finnish software engineer (born 1969)",
    snippet: "Finnish software engineer (born 1969)",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q371394",
    title: "Bangladesh Liberation War",
    date: "1971",
    startYear: 1971,
    description: "conflict that led to the independence of the majority-Bengali country",
    snippet: "conflict that led to the independence of the majority-Bengali country",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q1922071",
    title: "Indo-Pakistani War of 1971",
    date: "1971",
    startYear: 1971,
    description: "1971 war between India and Pakistan along Bengladesh Liberation War",
    snippet: "1971 war between India and Pakistan along Bengladesh Liberation War",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q317521",
    title: "Elon Musk",
    date: "1971",
    startYear: 1971,
    description: "businessman and entrepreneur (born 1971)",
    snippet: "businessman and entrepreneur (born 1971)",
    significance: 1,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q49100",
    title: "Yom Kippur War",
    date: "1973",
    startYear: 1973,
    description: "October 1973 war between Egypt and Syria at one side and Israel on the other side",
    snippet: "October 1973 war between Egypt and Syria at one side and Israel on the other side",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q83085",
    title: "Soviet-Afghan War",
    date: "1979",
    startYear: 1979,
    description: "1979–1989 war between the Soviet Union and Afghan insurgents",
    snippet: "1979–1989 war between the Soviet Union and Afghan insurgents",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q623171",
    title: "Sino-Vietnamese War",
    date: "1979",
    startYear: 1979,
    description: "war between the People's Republic of China and Socialist Republic of Vietnam in 1979",
    snippet: "war between the People's Republic of China and Socialist Republic of Vietnam in 1979",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q82664",
    title: "Iran–Iraq War",
    date: "1980",
    startYear: 1980,
    description: "1980-1988 war between Iran and Iraq",
    snippet: "1980-1988 war between Iran and Iraq",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q48249",
    title: "Falklands War",
    date: "1982",
    startYear: 1982,
    description: "undeclared war between Argentina and the United Kingdom in 1982",
    snippet: "undeclared war between Argentina and the United Kingdom in 1982",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q49103",
    title: "1982 Lebanon War",
    date: "1982",
    startYear: 1982,
    description: "Israeli invasion of Lebanon",
    snippet: "Israeli invasion of Lebanon",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q381375",
    title: "First Nagorno-Karabakh War",
    date: "1988",
    startYear: 1988,
    description: "armed conflict that took place in the late 1980s to May 1994",
    snippet: "armed conflict that took place in the late 1980s to May 1994",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q37643",
    title: "Gulf War",
    date: "1990",
    startYear: 1990,
    description: "1990–1991 conflict between Iraq and a 42-country coalition",
    snippet: "1990–1991 conflict between Iraq and a 42-country coalition",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q734004",
    title: "Black January",
    date: "1990",
    startYear: 1990,
    description: "1990 massacre in Baku",
    snippet: "1990 massacre in Baku",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q68969",
    title: "Croatian War of Independence",
    date: "1991",
    startYear: 1991,
    description: "war of independence fought from 1991 to 1995",
    snippet: "war of independence fought from 1991 to 1995",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q56039",
    title: "German reunification",
    date: "1991",
    startYear: 1991,
    description: "process in 1990 in which the German Democratic Republic became part of the Federal Republic of Germany",
    snippet: "process in 1990 in which the German Democratic Republic became part of the Federal Republic of Germa",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q29269",
    title: "First Chechen War",
    date: "1994",
    startYear: 1994,
    description: "war fought from 1994 to 1996 in Chechnya",
    snippet: "war fought from 1994 to 1996 in Chechnya",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q190029",
    title: "Kosovo War",
    date: "1998",
    startYear: 1998,
    description: "late 1990s armed conflict in Kosovo",
    snippet: "late 1990s armed conflict in Kosovo",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q120843",
    title: "Second Chechen War",
    date: "1999",
    startYear: 1999,
    description: "war in Chechnya",
    snippet: "war in Chechnya",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q404517",
    title: "Kargil War",
    date: "1999",
    startYear: 1999,
    description: "1999 conflict between India and Pakistan",
    snippet: "1999 conflict between India and Pakistan",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q182865",
    title: "War in Afghanistan (2001–2021)",
    date: "2001",
    startYear: 2001,
    description: "armed conflict between NATO countries and Afghanistan since 2001",
    snippet: "armed conflict between NATO countries and Afghanistan since 2001",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q185729",
    title: "war on terror",
    date: "2001",
    startYear: 2001,
    description: "Military campaign started after September 11 attacks",
    snippet: "Military campaign started after September 11 attacks",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q545449",
    title: "Iraq War",
    date: "2003",
    startYear: 2003,
    description: "2003–2011 war after an American-led invasion",
    snippet: "2003–2011 war after an American-led invasion",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q190758",
    title: "War in Darfur",
    date: "2003",
    startYear: 2003,
    description: "major armed conflict in the Darfur region of Sudan that began in February 2003",
    snippet: "major armed conflict in the Darfur region of Sudan that began in February 2003",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q49104",
    title: "2006 Lebanon War",
    date: "2006",
    startYear: 2006,
    description: "armed conflict primarily between Israel and Hezbollah",
    snippet: "armed conflict primarily between Israel and Hezbollah",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q620735",
    title: "Russo-Georgian War",
    date: "2008",
    startYear: 2008,
    description: "2008 Russian invasion of Georgia",
    snippet: "2008 Russian invasion of Georgia",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q170682",
    title: "Gaza War (2008–2009)",
    date: "2008",
    startYear: 2008,
    description: "December 2008–January 2009 armed conflict in the Gaza Strip",
    snippet: "December 2008–January 2009 armed conflict in the Gaza Strip",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q15860072",
    title: "Russo-Ukrainian war",
    date: "2014",
    startYear: 2014,
    description: "armed conflict between Russia and Ukraine since 2014",
    snippet: "armed conflict between Russia and Ukraine since 2014",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q99659280",
    title: "Second Nagorno-Karabakh War",
    date: "2020",
    startYear: 2020,
    description: "armed conflict in South Caucasus",
    snippet: "armed conflict in South Caucasus",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q110999040",
    title: "full-scale Russo-Ukrainian war",
    date: "2022",
    startYear: 2022,
    description: "full-scale invasion of Ukraine by Russia starting on 24 February 2022, part of Russo-Ukrainian War",
    snippet: "full-scale invasion of Ukraine by Russia starting on 24 February 2022, part of Russo-Ukrainian War",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q122962941",
    title: "Gaza war",
    date: "2023",
    startYear: 2023,
    description: "armed conflict around the Gaza Strip that started on 7 October 2023",
    snippet: "armed conflict around the Gaza Strip that started on 7 October 2023",
    significance: 2,
    gap: 150,
    source: "WIKIDATA"
  },
  {
    id: "Q134900605",
    title: "Twelve-Day War",
    date: "2025",
    startYear: 2025,
    description: "2025 armed conflict in the Middle East",
    snippet: "2025 armed conflict in the Middle East",
    significance: 3,
    gap: 150,
    source: "WIKIDATA"
  },
];
