// Rules of the Game — kid-friendly questions on the actual Laws of the Game
// (IFAB). Same shape as quiz-trivia.js: { cat:"rules", diff (1-3), q, choices[],
// answer (index), fact }. Facts explain the WHY so kids learn the reasoning,
// not just the answer.

window.WC_QUIZ_RULES = [
  // ---------------------------------------------------- CARDS, FOULS & MISCONDUCT
  {
    cat: "rules", diff: 1,
    q: "What color card does the referee show to send a player OFF the field for good?",
    choices: ["Red", "Yellow", "Green", "Blue"],
    answer: 0,
    fact: "A red card means the player is sent off AND can't be replaced — so the team plays the rest of the match a player short.",
  },
  {
    cat: "rules", diff: 1,
    q: "A yellow card is mainly a...",
    choices: ["Warning (caution)", "Goal", "Substitution", "Time-out"],
    answer: 0,
    fact: "Yellow is a caution — a warning. Get two yellows in one game and they add up to a red, so you're sent off.",
  },
  {
    cat: "rules", diff: 1,
    q: "How many yellow cards in ONE match add up to a red card?",
    choices: ["1", "2", "3", "4"],
    answer: 1,
    fact: "Two yellow cards = one red card. The referee shows the second yellow, then the red, and the player leaves.",
  },
  {
    cat: "rules", diff: 1,
    q: "Touching the ball on purpose with your hand or arm (if you're not the keeper) is called a...",
    choices: ["Handball", "Header", "Tackle", "Throw-in"],
    answer: 0,
    fact: "A deliberate handball is a foul. It gives the other team a free kick — or a penalty if it happens inside the box.",
  },
  {
    cat: "rules", diff: 2,
    q: "Arguing angrily with the referee (called 'dissent') can earn a player what?",
    choices: ["A yellow card", "A goal", "A corner", "Nothing"],
    answer: 0,
    fact: "Showing disrespect to the referee is a cautionable offense — it's a yellow card. Respect the ref!",
  },
  {
    cat: "rules", diff: 2,
    q: "Wasting time or delaying the restart of play can earn what?",
    choices: ["A yellow card", "A red card", "A penalty", "Extra time"],
    answer: 0,
    fact: "Time-wasting is unsporting, so it's a yellow card. The ref also adds the lost time back as stoppage time.",
  },
  {
    cat: "rules", diff: 3,
    q: "Violent conduct — like striking an opponent — earns what?",
    choices: ["A straight red card", "A yellow card", "A warning", "A corner"],
    answer: 0,
    fact: "Violent conduct is one of the most serious offenses, so it's a straight red — no warning needed.",
  },
  {
    cat: "rules", diff: 3,
    q: "Spitting at someone or biting an opponent earns what?",
    choices: ["A red card", "A yellow card", "A free kick only", "A throw-in"],
    answer: 0,
    fact: "Spitting and biting are sent-off offenses — an automatic red card.",
  },
  {
    cat: "rules", diff: 3,
    q: "Stopping a clear, obvious goal-scoring chance by handball usually earns what?",
    choices: ["A red card", "A yellow card", "A throw-in", "A corner"],
    answer: 0,
    fact: "It's called 'denying an obvious goal-scoring opportunity' (DOGSO). The handball is a red card because it robbed a near-certain goal.",
  },
  {
    cat: "rules", diff: 3,
    q: "A really bad, dangerous tackle (serious foul play) earns what?",
    choices: ["A red card", "A throw-in", "A goal kick", "A yellow card"],
    answer: 0,
    fact: "Serious foul play — a tackle that endangers an opponent's safety — is a straight red card.",
  },

  // ---------------------------------------------------- FREE KICKS: DIRECT vs INDIRECT
  {
    cat: "rules", diff: 2,
    q: "From a DIRECT free kick, can you score by shooting straight into the goal?",
    choices: ["Yes", "No, never", "Only from the penalty spot", "Only with your head"],
    answer: 0,
    fact: "Yes! A direct free kick (given for fouls like tripping, pushing or handball) can go straight in without touching anyone else.",
  },
  {
    cat: "rules", diff: 2,
    q: "An INDIRECT free kick must do WHAT before a goal can count?",
    choices: [
      "Touch another player first",
      "Bounce twice",
      "Be taken with the left foot",
      "Go over the crossbar",
    ],
    answer: 0,
    fact: "An indirect free kick has to touch a second player before it counts. The referee signals it by holding one arm straight up.",
  },
  {
    cat: "rules", diff: 3,
    q: "How does the referee SIGNAL that a free kick is indirect?",
    choices: [
      "Raises one arm straight up",
      "Blows the whistle twice",
      "Points at the goal",
      "Crosses both arms",
    ],
    answer: 0,
    fact: "The ref keeps one arm raised straight up until the kick is taken and the ball touches another player (or goes out).",
  },
  {
    cat: "rules", diff: 2,
    q: "Direct free kicks are given for 'penal' fouls. Which of these is one?",
    choices: ["Tripping an opponent", "Being offside", "Dangerous high kick", "Wasting time"],
    answer: 0,
    fact: "Kicking, tripping, pushing, holding, and handball are 'penal' fouls — they give a DIRECT free kick (or a penalty in the box).",
  },
  {
    cat: "rules", diff: 2,
    q: "A foul by a defender INSIDE their own penalty area usually gives the other team...",
    choices: ["A penalty kick", "A corner", "A throw-in", "A yellow card only"],
    answer: 0,
    fact: "A penal foul inside the box becomes a penalty kick — one shot from the spot with only the goalkeeper to beat.",
  },
  {
    cat: "rules", diff: 2,
    q: "How far is the penalty spot from the goal line?",
    choices: ["12 yards (11 m)", "6 yards", "18 yards", "25 yards"],
    answer: 0,
    fact: "The penalty spot is 12 yards (11 metres) from goal. Only the goalkeeper can try to stop the kick.",
  },

  // ---------------------------------------------------- OFFSIDE
  {
    cat: "rules", diff: 2,
    q: "An attacker is offside if, when the ball is played, they are closer to the goal than the ball AND...",
    choices: [
      "The second-to-last opponent",
      "The referee",
      "The center circle",
      "Their own goalkeeper",
    ],
    answer: 0,
    fact: "Offside compares you to the second-to-last opponent (usually the last defender, since the keeper is often the very last). Level = onside.",
  },
  {
    cat: "rules", diff: 1,
    q: "Can you be offside in your OWN half of the field?",
    choices: ["No", "Yes", "Only at corners", "Only after halftime"],
    answer: 0,
    fact: "You can only be offside in the opponents' half. In your own half you're always onside.",
  },
  {
    cat: "rules", diff: 2,
    q: "What kind of free kick does the other team get for an offside offense?",
    choices: ["An indirect free kick", "A direct free kick", "A penalty", "A corner"],
    answer: 0,
    fact: "Offside is punished with an indirect free kick from where the offside player was involved in the play.",
  },
  {
    cat: "rules", diff: 2,
    q: "You CANNOT be offside directly from which of these?",
    choices: ["A throw-in", "A through ball from a teammate", "A cross from open play", "A pass from midfield"],
    answer: 0,
    fact: "There's no offside from a throw-in, a corner kick, or a goal kick — so attackers can sneak behind the defense on those! From normal passes and crosses, offside still applies.",
  },
  {
    cat: "rules", diff: 3,
    q: "Just standing in an offside position — is that automatically a foul?",
    choices: [
      "No — only if you get involved in the play",
      "Yes, always",
      "Only in extra time",
      "Only if you're the striker",
    ],
    answer: 0,
    fact: "Being in an offside position isn't an offense by itself. You're only penalized if you touch the ball, block an opponent, or gain an advantage.",
  },

  // ---------------------------------------------------- RESTARTS
  {
    cat: "rules", diff: 1,
    q: "When the WHOLE ball crosses the side line (touchline), what is the restart?",
    choices: ["A throw-in", "A corner", "A goal kick", "A penalty"],
    answer: 0,
    fact: "The ball must FULLY cross the line to be out. Then the team that didn't touch it last gets a throw-in.",
  },
  {
    cat: "rules", diff: 2,
    q: "For a legal throw-in, the thrower must...",
    choices: [
      "Use both hands, ball over the head, both feet on the ground",
      "Use one hand only",
      "Throw from the knees",
      "Kick it in instead",
    ],
    answer: 0,
    fact: "Both hands, ball brought from behind and over the head, and both feet staying on the ground (on or behind the line). Otherwise it's a foul throw.",
  },
  {
    cat: "rules", diff: 2,
    q: "Can you score a goal DIRECTLY from a throw-in?",
    choices: ["No", "Yes", "Only against the keeper", "Only in extra time"],
    answer: 0,
    fact: "No — the ball must touch another player first. If you throw it straight into a goal, it doesn't count.",
  },
  {
    cat: "rules", diff: 2,
    q: "Can you score a goal DIRECTLY from a corner kick?",
    choices: ["Yes", "No", "Only with your head", "Only from the near post"],
    answer: 0,
    fact: "Yes! A goal straight from a corner is so cool it has a name — an 'Olimpico'.",
  },
  {
    cat: "rules", diff: 2,
    q: "A DEFENDER puts the ball over their own goal line (and it's not a goal). What's the restart?",
    choices: ["A corner kick", "A goal kick", "A throw-in", "A penalty"],
    answer: 0,
    fact: "If the defending team touches it last before it crosses their goal line, the attackers get a corner kick.",
  },
  {
    cat: "rules", diff: 2,
    q: "An ATTACKER puts the ball over the opponents' goal line (and it's not a goal). What's the restart?",
    choices: ["A goal kick", "A corner", "A throw-in", "A free kick"],
    answer: 0,
    fact: "If the attacking team touches it last before it goes over the goal line, the defending team gets a goal kick.",
  },
  {
    cat: "rules", diff: 3,
    q: "If the referee stops play for an injury with NO foul, how does play restart?",
    choices: ["A drop ball", "A penalty", "A throw-in", "A corner"],
    answer: 0,
    fact: "When there's no foul, the ref restarts with a 'drop ball' — usually given back to the team that last had it.",
  },

  // ---------------------------------------------------- GOALKEEPER
  {
    cat: "rules", diff: 1,
    q: "Who is the ONLY player allowed to use their hands — and only inside their own area?",
    choices: ["The goalkeeper", "The captain", "The striker", "Anyone"],
    answer: 0,
    fact: "Only the goalkeeper can handle the ball, and only inside their own penalty area. Outside the box, even the keeper can't use hands.",
  },
  {
    cat: "rules", diff: 3,
    q: "A teammate deliberately KICKS the ball back to their own keeper, who picks it up. What's the call?",
    choices: [
      "Indirect free kick to the other team",
      "Nothing, that's fine",
      "A goal kick",
      "A penalty",
    ],
    answer: 0,
    fact: "This is the 'back-pass rule'. A keeper can't use hands on a ball a teammate deliberately kicks to them — it's an indirect free kick.",
  },
  {
    cat: "rules", diff: 3,
    q: "About how long can a goalkeeper hold the ball in their hands before it's an offense?",
    choices: ["About 6 seconds", "30 seconds", "1 minute", "As long as they like"],
    answer: 0,
    fact: "Roughly 6 seconds. Holding on too long to waste time gives the other team an indirect free kick.",
  },

  // ---------------------------------------------------- DANGEROUS PLAY & OTHER OFFENSES
  {
    cat: "rules", diff: 2,
    q: "A high, dangerous kick near another player's head (with no contact) is called...",
    choices: ["Dangerous play", "A clean tackle", "A header", "A handball"],
    answer: 0,
    fact: "Dangerous play (like a high boot near someone's head) gives the other team an indirect free kick — even though no one was touched.",
  },
  {
    cat: "rules", diff: 2,
    q: "When a foul happens but the fouled team still has a great attack going, the ref may let play continue. This is the...",
    choices: ["Advantage rule", "Offside rule", "Back-pass rule", "Six-second rule"],
    answer: 0,
    fact: "The 'advantage' lets play go on if stopping it would actually help the team that committed the foul. The ref waves both arms forward.",
  },

  // ---------------------------------------------------- GAME STRUCTURE
  {
    cat: "rules", diff: 1,
    q: "How many players does each team have on the field, including the goalkeeper?",
    choices: ["11", "9", "10", "12"],
    answer: 0,
    fact: "Eleven per side, including the keeper. That's why it's 'eleven versus eleven'.",
  },
  {
    cat: "rules", diff: 1,
    q: "A goal counts only when the WHOLE ball...",
    choices: [
      "Crosses the goal line between the posts and under the bar",
      "Touches the net",
      "Reaches the keeper",
      "Is kicked hard",
    ],
    answer: 0,
    fact: "Every bit of the ball must cross the line. If part of the ball is still on the line, it's NOT a goal yet.",
  },
  {
    cat: "rules", diff: 2,
    q: "A normal World Cup match is two halves of how many minutes each?",
    choices: ["45 minutes", "30 minutes", "40 minutes", "60 minutes"],
    answer: 0,
    fact: "Two 45-minute halves = 90 minutes, plus 'stoppage time' added on for any pauses.",
  },
  {
    cat: "rules", diff: 2,
    q: "The extra minutes added at the end of each half for stoppages are called...",
    choices: ["Stoppage (added) time", "Overtime", "Halftime", "The shootout"],
    answer: 0,
    fact: "Also called injury time. The ref tracks time lost to injuries, subs and celebrations, and adds it back on.",
  },
  {
    cat: "rules", diff: 3,
    q: "In a knockout match still tied after 90 minutes, what comes FIRST?",
    choices: [
      "Extra time (two 15-minute halves)",
      "A penalty shootout",
      "A coin flip",
      "A replay tomorrow",
    ],
    answer: 0,
    fact: "First comes extra time: two 15-minute halves. If it's STILL tied, then it goes to a penalty shootout.",
  },
  {
    cat: "rules", diff: 2,
    q: "In a penalty shootout, how many kicks does each team take before 'sudden death'?",
    choices: ["5", "3", "10", "1"],
    answer: 0,
    fact: "Each team takes 5 penalties, alternating. If still level, it's sudden death — one each until someone misses.",
  },
  {
    cat: "rules", diff: 3,
    q: "At the 2022 World Cup, how many substitutions could each team make in normal time?",
    choices: ["5", "3", "7", "Unlimited"],
    answer: 0,
    fact: "Five subs (in up to three stoppages), with a sixth allowed if the game goes to extra time.",
  },
  {
    cat: "rules", diff: 3,
    q: "What does 'VAR' stand for?",
    choices: [
      "Video Assistant Referee",
      "Very Aggressive Run",
      "Vertical Attack Rule",
      "Victory After Replay",
    ],
    answer: 0,
    fact: "The Video Assistant Referee reviews replays to fix clear mistakes on goals, penalties, red cards, and mistaken identity.",
  },
  {
    cat: "rules", diff: 3,
    q: "What is the fewest players a team can have before the match must be abandoned?",
    choices: ["7", "5", "9", "10"],
    answer: 0,
    fact: "A team needs at least 7 players. If too many are sent off or hurt and they drop below 7, the match can't continue.",
  },
];
