// Hand-authored World Cup history trivia.
// Each question: { cat, diff (1 easy → 3 hard), q, choices[], answer (index), fact }
// Facts are shown after answering so kids learn even when they miss one.
// Categories: champions, hosts, records, legends, usa

window.WC_QUIZ_TRIVIA = [
  // ---------------------------------------------------------------- CHAMPIONS
  {
    cat: "champions", diff: 1,
    q: "Which country has won the most World Cups?",
    choices: ["Brazil", "Germany", "Argentina", "Italy"],
    answer: 0,
    fact: "Brazil has won 5 World Cups (1958, 1962, 1970, 1994, 2002) — more than any other nation.",
  },
  {
    cat: "champions", diff: 1,
    q: "How many World Cups has Brazil won?",
    choices: ["3", "4", "5", "6"],
    answer: 2,
    fact: "Five! Brazil's golden years: 1958, 1962, 1970, 1994, and 2002.",
  },
  {
    cat: "champions", diff: 2,
    q: "Who won the 2022 World Cup in Qatar?",
    choices: ["France", "Argentina", "Brazil", "Croatia"],
    answer: 1,
    fact: "Argentina beat France on penalties in one of the greatest finals ever — Lionel Messi finally lifted the trophy.",
  },
  {
    cat: "champions", diff: 2,
    q: "How many World Cups have Germany and Italy each won?",
    choices: ["2", "3", "4", "5"],
    answer: 2,
    fact: "Both Germany and Italy have 4 titles each — just behind Brazil's 5.",
  },
  {
    cat: "champions", diff: 2,
    q: "Which country won the very first World Cup, in 1930?",
    choices: ["Brazil", "Uruguay", "Argentina", "Italy"],
    answer: 1,
    fact: "Uruguay won the first World Cup in 1930 — and they hosted it too!",
  },
  {
    cat: "champions", diff: 2,
    q: "Which European country won its FIRST World Cup in 2010?",
    choices: ["Spain", "Netherlands", "Portugal", "Belgium"],
    answer: 0,
    fact: "Spain won its first-ever title in 2010 in South Africa with its famous 'tiki-taka' passing style.",
  },
  {
    cat: "champions", diff: 2,
    q: "Which country has reached the most World Cup finals but only won one (in 1966)?",
    choices: ["England", "Netherlands", "Hungary", "Sweden"],
    answer: 0,
    fact: "England's only title came in 1966, when they hosted and beat West Germany 4–2.",
  },
  {
    cat: "champions", diff: 3,
    q: "Only TWO continents have ever produced a World Cup winner. Which two?",
    choices: [
      "Europe and South America",
      "Europe and Africa",
      "South America and North America",
      "Europe and Asia",
    ],
    answer: 0,
    fact: "Every champion has come from Europe (UEFA) or South America (CONMEBOL). No African, Asian, or North American team has ever won.",
  },
  {
    cat: "champions", diff: 3,
    q: "How many World Cups has Argentina won?",
    choices: ["2", "3", "4", "1"],
    answer: 1,
    fact: "Argentina has 3 titles: 1978, 1986, and 2022.",
  },
  {
    cat: "champions", diff: 3,
    q: "France has won the World Cup twice. In which two years?",
    choices: ["1998 & 2018", "1998 & 2006", "1986 & 2018", "2006 & 2018"],
    answer: 0,
    fact: "France won at home in 1998 and again in Russia in 2018.",
  },

  // -------------------------------------------------------------------- HOSTS
  {
    cat: "hosts", diff: 1,
    q: "How many countries are hosting the 2026 World Cup?",
    choices: ["1", "2", "3", "4"],
    answer: 2,
    fact: "2026 is the first World Cup shared by THREE nations: Canada, Mexico, and the United States.",
  },
  {
    cat: "hosts", diff: 1,
    q: "Which of these is NOT a host of the 2026 World Cup?",
    choices: ["United States", "Mexico", "Canada", "Brazil"],
    answer: 3,
    fact: "The 2026 hosts are the USA, Mexico, and Canada — Brazil hosted back in 2014.",
  },
  {
    cat: "hosts", diff: 2,
    q: "How many teams will play in the 2026 World Cup — the biggest ever?",
    choices: ["32", "40", "48", "64"],
    answer: 2,
    fact: "2026 expands to 48 teams and 104 matches — up from 32 teams in 2022.",
  },
  {
    cat: "hosts", diff: 2,
    q: "Which country hosted the 2022 World Cup?",
    choices: ["Russia", "Qatar", "Brazil", "South Africa"],
    answer: 1,
    fact: "Qatar hosted in 2022 — the first World Cup held in the Middle East and the first played in winter.",
  },
  {
    cat: "hosts", diff: 2,
    q: "Which country hosted the FIRST World Cup held in Africa, in 2010?",
    choices: ["Nigeria", "Egypt", "South Africa", "Morocco"],
    answer: 2,
    fact: "South Africa hosted in 2010 — remembered for the buzzing vuvuzela horns!",
  },
  {
    cat: "hosts", diff: 2,
    q: "Mexico is hosting in 2026. How many times will Mexico have hosted the World Cup?",
    choices: ["First time", "Second time", "Third time", "Fourth time"],
    answer: 2,
    fact: "Mexico hosted in 1970 and 1986 — 2026 makes it the first country to host three times.",
  },
  {
    cat: "hosts", diff: 3,
    q: "There was NO World Cup in 1942 and 1946. Why?",
    choices: [
      "World War II",
      "Not enough teams",
      "A money problem",
      "Bad weather",
    ],
    answer: 0,
    fact: "World War II (1939–1945) forced the cancellation of both the 1942 and 1946 tournaments.",
  },
  {
    cat: "hosts", diff: 3,
    q: "Which two countries co-hosted the 2002 World Cup — the first in Asia?",
    choices: [
      "China and Japan",
      "South Korea and Japan",
      "Japan and Thailand",
      "South Korea and China",
    ],
    answer: 1,
    fact: "South Korea and Japan shared hosting in 2002 — the first World Cup in Asia and the first co-hosted by two countries.",
  },
  {
    cat: "hosts", diff: 3,
    q: "The USA hosted the World Cup once before 2026. What year?",
    choices: ["1986", "1990", "1994", "1998"],
    answer: 2,
    fact: "The USA hosted in 1994 — it still holds the record for highest average attendance ever.",
  },

  // ------------------------------------------------------------------ RECORDS
  {
    cat: "records", diff: 2,
    q: "The 'Golden Boot' is given to the player who does what?",
    choices: [
      "Scores the most goals",
      "Makes the most saves",
      "Runs the fastest",
      "Wins the final",
    ],
    answer: 0,
    fact: "The Golden Boot goes to the tournament's top goalscorer.",
  },
  {
    cat: "records", diff: 2,
    q: "Who won the Golden Boot at the 2022 World Cup with 8 goals?",
    choices: ["Lionel Messi", "Kylian Mbappé", "Harry Kane", "Cristiano Ronaldo"],
    answer: 1,
    fact: "France's Kylian Mbappé scored 8 goals in 2022, including a hat-trick in the final!",
  },
  {
    cat: "records", diff: 3,
    q: "Who scored the most goals in World Cup history (16 total)?",
    choices: ["Pelé", "Ronaldo", "Miroslav Klose", "Just Fontaine"],
    answer: 2,
    fact: "Germany's Miroslav Klose scored 16 World Cup goals across four tournaments (2002–2014).",
  },
  {
    cat: "records", diff: 3,
    q: "The 'Golden Glove' award is given to the best WHAT?",
    choices: ["Striker", "Goalkeeper", "Defender", "Young player"],
    answer: 1,
    fact: "The Golden Glove honors the tournament's best goalkeeper. Argentina's Emiliano Martínez won it in 2022.",
  },
  {
    cat: "records", diff: 3,
    q: "Most goals by one player in a SINGLE World Cup is 13. Who did it in 1958?",
    choices: ["Pelé", "Just Fontaine", "Gerd Müller", "Eusébio"],
    answer: 1,
    fact: "France's Just Fontaine scored 13 goals in the 1958 tournament — a record that still stands.",
  },
  {
    cat: "records", diff: 3,
    q: "Which country has played in EVERY single World Cup tournament?",
    choices: ["Germany", "Italy", "Brazil", "Argentina"],
    answer: 2,
    fact: "Brazil is the only nation to appear at all 22 World Cups (1930–2022) — the most consistent threat in history.",
  },
  {
    cat: "records", diff: 3,
    q: "What is the fastest goal in World Cup history — about 11 seconds — scored by Hakan Şükür in 2002?",
    choices: [
      "For Turkey",
      "For Brazil",
      "For Germany",
      "For South Korea",
    ],
    answer: 0,
    fact: "Turkey's Hakan Şükür scored after just ~11 seconds against South Korea in 2002 — the fastest ever.",
  },

  // ------------------------------------------------------------------ LEGENDS
  {
    cat: "legends", diff: 2,
    q: "Which legend is the only player to win THREE World Cups?",
    choices: ["Maradona", "Pelé", "Cristiano Ronaldo", "Zidane"],
    answer: 1,
    fact: "Brazil's Pelé won in 1958 (aged just 17!), 1962, and 1970 — the only player with three winner's medals.",
  },
  {
    cat: "legends", diff: 2,
    q: "Who scored the famous 'Hand of God' goal and the 'Goal of the Century' in 1986?",
    choices: ["Pelé", "Diego Maradona", "Lionel Messi", "Ronaldinho"],
    answer: 1,
    fact: "Argentina's Diego Maradona did both against England in the 1986 quarterfinal — minutes apart!",
  },
  {
    cat: "legends", diff: 2,
    q: "Which player led Argentina to the 2022 title and finally won the World Cup?",
    choices: ["Ángel Di María", "Lionel Messi", "Sergio Agüero", "Julián Álvarez"],
    answer: 1,
    fact: "Lionel Messi won the Golden Ball (best player) and lifted the trophy in 2022.",
  },
  {
    cat: "legends", diff: 3,
    q: "Who won the Golden Ball as best player of the 2018 World Cup, leading Croatia to the final?",
    choices: ["Luka Modrić", "Kylian Mbappé", "Harry Kane", "Eden Hazard"],
    answer: 0,
    fact: "Croatia's Luka Modrić was named the best player of 2018 even though France won the final.",
  },
  {
    cat: "legends", diff: 3,
    q: "Which Brazilian striker scored both goals in the 2002 final, completing a huge comeback from injury?",
    choices: ["Ronaldinho", "Romário", "Ronaldo (Nazário)", "Rivaldo"],
    answer: 2,
    fact: "Ronaldo scored both goals in the 2002 final vs Germany and won the Golden Boot with 8 — a famous redemption story.",
  },
  {
    cat: "legends", diff: 3,
    q: "Zinedine Zidane scored TWO headers in the 1998 final. Which country did France beat?",
    choices: ["Italy", "Brazil", "Germany", "Argentina"],
    answer: 1,
    fact: "Zidane headed in two goals as France beat Brazil 3–0 in the 1998 final in Paris.",
  },
  {
    cat: "legends", diff: 3,
    q: "Spain's 2010 winning team was famous for a passing style nicknamed what?",
    choices: ["Catenaccio", "Tiki-taka", "Total Football", "Gegenpressing"],
    answer: 1,
    fact: "'Tiki-taka' — short, quick passes to keep the ball — defined Spain's 2010 champions.",
  },

  // ---------------------------------------------------------------------- USA
  {
    cat: "usa", diff: 2,
    q: "What is the FARTHEST the USA men's team has ever gone at a World Cup?",
    choices: ["Won it", "3rd place", "Quarterfinals", "Round of 16"],
    answer: 1,
    fact: "The USA finished 3rd at the very first World Cup in 1930 — reaching the semifinals.",
  },
  {
    cat: "usa", diff: 3,
    q: "In the last 50 years, the USA's best run was reaching the quarterfinals. In which year?",
    choices: ["1994", "2002", "2010", "2014"],
    answer: 1,
    fact: "In 2002, the USA reached the quarterfinals, losing 1–0 to Germany.",
  },
  {
    cat: "usa", diff: 2,
    q: "Which confederation does the USA play in?",
    choices: ["CONMEBOL", "CONCACAF", "UEFA", "AFC"],
    answer: 1,
    fact: "The USA, Mexico, and Canada all play in CONCACAF — North and Central America and the Caribbean.",
  },
  {
    cat: "usa", diff: 3,
    q: "Which famous goalkeeper made a record 16 saves for the USA against Belgium in 2014?",
    choices: ["Brad Friedel", "Tim Howard", "Kasey Keller", "Matt Turner"],
    answer: 1,
    fact: "Tim Howard's 16 saves vs Belgium in 2014 set a World Cup record for a single match.",
  },

  // -------------------------------------------- MORE CHAMPIONS (variety pack)
  // Spreads questions across all the great winners, not just Brazil.
  {
    cat: "champions", diff: 1,
    q: "Which country lifted the trophy at the 2018 World Cup in Russia?",
    choices: ["Croatia", "France", "Belgium", "England"],
    answer: 1,
    fact: "France won in 2018, led by a young Kylian Mbappé — their second title after 1998.",
  },
  {
    cat: "champions", diff: 2,
    q: "Which country was the FIRST-ever World Cup winner, back in 1930?",
    choices: ["Brazil", "Italy", "Uruguay", "Argentina"],
    answer: 2,
    fact: "Uruguay won the first World Cup in 1930 — and has won twice (1930 and 1950).",
  },
  {
    cat: "champions", diff: 2,
    q: "Italy has won the World Cup four times. When was their most recent title?",
    choices: ["1994", "2006", "2010", "1982"],
    answer: 1,
    fact: "Italy's four titles: 1934, 1938, 1982, and 2006 (beating France in the final).",
  },
  {
    cat: "champions", diff: 2,
    q: "Germany won its most recent World Cup in 2014. Where was it held?",
    choices: ["Brazil", "South Africa", "Russia", "Germany"],
    answer: 0,
    fact: "Germany won in 2014 in Brazil — famously thrashing the hosts 7–1 in the semifinal.",
  },
  {
    cat: "champions", diff: 2,
    q: "Which country has won exactly TWO World Cups — in 1930 and 1950?",
    choices: ["Uruguay", "Argentina", "France", "Spain"],
    answer: 0,
    fact: "Uruguay won in 1930 and 1950. Their 1950 win in Brazil is called the 'Maracanazo'.",
  },
  {
    cat: "champions", diff: 2,
    q: "France has won 2 World Cups. Which year was their FIRST?",
    choices: ["1998", "2006", "1986", "2018"],
    answer: 0,
    fact: "France won its first title at home in 1998, beating Brazil 3–0 in the final.",
  },
  {
    cat: "champions", diff: 2,
    q: "Argentina has 3 World Cup titles. Which is their MOST RECENT?",
    choices: ["1978", "1986", "2014", "2022"],
    answer: 3,
    fact: "Argentina won in 1978, 1986, and most recently 2022 with Lionel Messi.",
  },
  {
    cat: "champions", diff: 2,
    q: "England has won the World Cup once. In which year?",
    choices: ["1962", "1966", "1970", "1990"],
    answer: 1,
    fact: "England won its only title in 1966, on home soil, beating West Germany 4–2.",
  },
  {
    cat: "champions", diff: 2,
    q: "Besides Brazil, which is the only OTHER country to win 4 World Cups (along with Germany)?",
    choices: ["Argentina", "Italy", "France", "Spain"],
    answer: 1,
    fact: "Both Italy and Germany have 4 titles each, second only to Brazil's 5.",
  },
  {
    cat: "champions", diff: 2,
    q: "Spain won its only World Cup in 2010. Who did they beat in the final?",
    choices: ["Germany", "Netherlands", "Brazil", "Italy"],
    answer: 1,
    fact: "Spain beat the Netherlands 1–0 after extra time, Andrés Iniesta scoring the winner.",
  },
  {
    cat: "champions", diff: 2,
    q: "Which country has finished RUNNER-UP a record three times without winning (1974, 1978, 2010)?",
    choices: ["Netherlands", "Hungary", "Sweden", "Croatia"],
    answer: 0,
    fact: "The Netherlands has reached three finals (1974, 1978, 2010) but never won the trophy.",
  },
  {
    cat: "champions", diff: 3,
    q: "Which country did France beat on penalties to win the 2022 final... wait — who actually WON 2022?",
    choices: ["France", "Argentina", "Brazil", "Croatia"],
    answer: 1,
    fact: "Argentina won 2022, beating France on penalties after a 3–3 thriller.",
  },
  {
    cat: "champions", diff: 3,
    q: "Germany (including as West Germany) first won the World Cup in which year — 'The Miracle of Bern'?",
    choices: ["1954", "1966", "1974", "1990"],
    answer: 0,
    fact: "West Germany won in 1954, beating Hungary — known as the 'Miracle of Bern'.",
  },
];
