// Ants & Artistry — catalog dashboard
// Reads assets/images/manifest.json (generated by catalog.py) and renders an
// inventory + roadmap. Roadmap targets/notes persist in localStorage.

const ROADMAP_KEY = 'ants-artistry-roadmap';

function loadRoadmap() {
    try { return JSON.parse(localStorage.getItem(ROADMAP_KEY)) || {}; }
    catch { return {}; }
}
function saveRoadmap(rm) {
    localStorage.setItem(ROADMAP_KEY, JSON.stringify(rm));
}

let MANIFEST = null;
let roadmap = loadRoadmap();

init();

async function init() {
    try {
        const res = await fetch('assets/images/manifest.json?t=' + Date.now());
        MANIFEST = await res.json();
    } catch (e) {
        document.getElementById('generated').textContent =
            'Could not load manifest.json — run `python3 catalog.py` first.';
        return;
    }
    render();

    document.getElementById('plan-add').addEventListener('click', addPlanned);
}

// Build a global view: base type -> { have, category, variants[] }
function buildTypes() {
    const types = {};
    for (const cat of MANIFEST.categoryOrder) {
        for (const item of MANIFEST.categories[cat]) {
            if (!types[item.name]) {
                types[item.name] = { name: item.name, category: cat, have: 0, variants: [] };
            }
            types[item.name].have += 1;
            types[item.name].variants.push(item);
        }
    }
    // Include planned-only types from the roadmap that don't exist yet.
    for (const name of Object.keys(roadmap)) {
        if (!types[name]) {
            types[name] = { name, category: roadmap[name].category || '—', have: 0, variants: [], planned: true };
        }
    }
    return types;
}

function render() {
    const s = MANIFEST.summary;
    document.getElementById('generated').textContent =
        'Manifest generated ' + new Date(MANIFEST.generated).toLocaleString();

    // Stat cards
    const plannedGaps = countGaps();
    document.getElementById('stats').innerHTML = `
        ${statCard(s.totalImages, 'Total Images')}
        ${statCard(s.totalTypes, 'Unique Types')}
        ${statCard(MANIFEST.categoryOrder.length, 'Categories')}
        ${statCard(plannedGaps, 'Roadmap Gaps')}
    `;

    // Category bars
    const max = Math.max(1, ...Object.values(s.byCategory));
    document.getElementById('category-bars').innerHTML =
        MANIFEST.categoryOrder.map(cat => {
            const n = s.byCategory[cat];
            const pct = Math.round((n / max) * 100);
            return `<div class="bar-row ${n === 0 ? 'empty' : ''}">
                <span class="cat-name">${cat}</span>
                <div class="bar-track"><div class="bar-fill" style="width:${pct}%"></div></div>
                <span class="cat-count">${n}</span>
            </div>`;
        }).join('');

    renderTable();
}

function statCard(num, lbl) {
    return `<div class="stat-card"><div class="num">${num}</div><div class="lbl">${lbl}</div></div>`;
}

// How many roadmap targets are unmet (sum of remaining needed)
function countGaps() {
    const types = buildTypes();
    let gaps = 0;
    for (const t of Object.values(types)) {
        const target = roadmap[t.name]?.target || 0;
        if (target > t.have) gaps += 1;
    }
    return gaps;
}

function renderTable() {
    const types = buildTypes();
    const names = Object.keys(types).sort();
    const body = document.getElementById('inv-body');

    body.innerHTML = names.map(name => {
        const t = types[name];
        const entry = roadmap[name] || {};
        const target = entry.target || 0;
        const note = entry.note || '';
        const pct = target > 0 ? Math.min(100, Math.round((t.have / target) * 100)) : (t.have > 0 ? 100 : 0);
        const cls = target === 0 ? (t.have > 0 ? 'done' : 'none')
            : (t.have >= target ? 'done' : (t.have > 0 ? 'partial' : 'none'));
        const progLabel = target > 0 ? `${t.have}/${target}` : (t.have > 0 ? `${t.have}` : '0');

        const variants = t.variants.length
            ? t.variants.map(v => `<img src="${v.src}" alt="${v.label}" title="${v.label}">`).join('')
            : '<span class="none">—</span>';

        return `<tr data-name="${name}">
            <td><span class="type-name ${t.planned ? 'planned' : ''}">${name}</span>${t.planned ? '<span class="badge-planned">planned</span>' : ''}</td>
            <td class="cat-cell">${t.category}</td>
            <td class="have-cell">${t.have}</td>
            <td><input type="number" class="target-input" min="0" value="${target}" data-field="target"></td>
            <td><div class="progress-wrap"><div class="progress-track"><div class="progress-fill ${cls}" style="width:${pct}%"></div></div><span class="progress-label">${progLabel}</span></div></td>
            <td><input type="text" class="note-input" placeholder="idea / variant notes…" value="${escapeAttr(note)}" data-field="note"></td>
            <td><div class="variants">${variants}</div></td>
        </tr>`;
    }).join('');

    // Wire up inline edits
    body.querySelectorAll('input').forEach(inp => {
        inp.addEventListener('change', (e) => {
            const name = e.target.closest('tr').dataset.name;
            const field = e.target.dataset.field;
            roadmap[name] = roadmap[name] || {};
            if (field === 'target') roadmap[name].target = parseInt(e.target.value) || 0;
            if (field === 'note') roadmap[name].note = e.target.value;
            // carry category for planned-only types
            const types = buildTypes();
            if (types[name]) roadmap[name].category = types[name].category;
            saveRoadmap(roadmap);
            render();
        });
    });
}

function addPlanned() {
    const nameInput = document.getElementById('plan-name');
    const targetInput = document.getElementById('plan-target');
    const name = nameInput.value.trim().toLowerCase().replace(/\s+/g, '-');
    if (!name) { nameInput.focus(); return; }
    const target = parseInt(targetInput.value) || 1;
    roadmap[name] = { ...(roadmap[name] || {}), target };
    saveRoadmap(roadmap);
    nameInput.value = '';
    render();
}

function escapeAttr(s) {
    return String(s).replace(/"/g, '&quot;').replace(/</g, '&lt;');
}
